### ISSUE TITLE
"ScreensaverEnginer" would like to use your current location.

### ISSUE THREAD

**Issue by frozentsbgg** [JohnCoates/Aerial#1005]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: 13' 2016 Macbook pro
- [x] macOS version:  Mojave 10.14.6
- [x] Monitor setup: Internal Monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

When attempting to test the Screensaver, or the screensaver enables via timer. Weather is unable to determine my location and doesn't appear. Upon waking the device, I receive a popup 'ScreenSaverEngine' would like to use your current location.' Regardless of my input, it still occurs.

Weather works normally when inputting a manual location.

**Comment by glouel** [comment]
Hi @frozentsbgg 

So, the popup is pretty normal, you need to explicitly allow Aerial (or more precisely, macOS's ScreenSaverEngine that "hosts" Aerial which is a plugin to it, technically speaking) access to your location services so that it can locate you.

Once you've allowed it, it should work as expected (macOS tells Aerial your location, then Aerial uses that location to ask for your local weather). 

I suggest you try the "Test" button in the preference panel after setting back to use current, the popup should pop there (unless you denied it earlier). Let me know if you still have an issue after that.

**Comment by frozentsbgg** [comment]
The issue is that, regardless of me allowing it. It still doesn't work.
The popup appears every time aerial closes.

**Comment by glouel** [comment]
> The issue is that, regardless of me allowing it. It still doesn't work.
> The popup appears every time aerial closes.

Ha ok, sorry looks like I misunderstood. I'll assume you've allowed then but it keeps popping up right ? I'll try to replicate the issue in a Mojave VM, there may be something specific to that OS. Because a screensaver is a plugin (not an app), it depends - for everything security - from it's hosting app (in that case ScreenSaverEngine). That changed in Catalina.

So first thing I'd suggest, can you try the test button there : 

![Capture d’écran 2020-05-31 à 21 00 48](https://user-images.githubusercontent.com/37544189/83360496-0731c680-a382-11ea-8f37-af0319015db0.jpg)

I'm 99% sure that this one should work as this is the same thing that used to work fine in Mojave in the Time tab for location services. 

If that one works, I'd suggest going to the Security settings in macOS (sorry for the french screenshot). 

![Capture d’écran 2020-05-31 à 20 56 53](https://user-images.githubusercontent.com/37544189/83360526-347e7480-a382-11ea-9557-b249195c381c.jpg)

Make sure you pick location services on the left, then on the right try to look for that ScreenSaverEngine. Because it's part of the system, you may need to make sure you've allowed macOS to use your location for it to work. 

Let me know if the Test button works, and I'll try to get back to you tomorrow when I get a chance to replicate on a Mojave VM .

**Comment by frozentsbgg** [comment]
Test/Preview didn't work till I changed the setting in Security Settings.
Once it did, It worked perfectly :)

Thanks for the help and time @glouel.

**Comment by glouel** [comment]
Awesome, usually just saying yes to the popup should have changed that setting for you, but sometimes macOS is weird... thanks for following up!
