### ISSUE TITLE
White dot at the bottom left corner

### ISSUE THREAD

**Issue by shawnpooh** [JohnCoates/Aerial#1018]
Just noticed there is a white dot at the bottom left corner, when Aerial screen saver turns on. But when I play the video file with my local player, it doesn't show up. I don't know if this just happens to me. Any idea why?

**Comment by glouel** [comment]
Hi @ShawnPooh 

Yep, there's a very faint white dot in the bottom/left corner. Long story short, this is a workaround for a bug with Intel graphics where if I a video starts playing in the screensaver, without drawing something on screen first, there's occasional tearing/garbling of the video output (see here https://github.com/JohnCoates/Aerial/issues/600).

So that dot comes from there. It used to be enabled only on High Sierra, but the bug comes and goes with each dot release of macOS, so I ended up enabling it all the time, I tried to make it very faint so it doesn't bother too many people but looks like you noticed ;) 

I could probably try and make it less noticeable but that's the best workaround I found for that recurring bug.

**Comment by ShawnPooh** [comment]
Thank you for your reply! Now I know it’s not just me and why it happens. I panicked when I noticed it coz I just bought a new one(^^;

**Comment by glouel** [comment]
Yeah it kinda look like a dead pixel, sorry about the fright ;) I'll try to think about maybe having it disappear after a few seconds in next version.

**Comment by ShawnPooh** [comment]
> Yeah it kinda look like a dead pixel, sorry about the fright ;) I'll try to think about maybe having it disappear after a few seconds in next version. 

No worries. It’s just a minor thing. Since I know it’s not just me, I’ll get use to it. Really enjoy this screensaver. It’s amazing!
