### ISSUE TITLE
Feature Request: Keyboard shortcut to exclude current video from future playback

### ISSUE THREAD

**Issue by byalextran** [JohnCoates/Aerial#1020]
I know Aerial supports using the right arrow to skip a video, if possible I'd love to see an additional keyboard shortcut to exclude a video from future playback. 

For example, if a video is playing that I don't like, I could hit the down arrow which would uncheck that video in the settings and not play it again. It would then remove it from the cache and save space for more favored videos. 

With the ever growing list of videos, this feature would allow users to quickly curate screensavers to just ones they want to see. Otherwise, it's tedious to manually uncheck a video from the settings. Especially since it's difficult (if not impossible?) to know which video just played and the corresponding name in the settings.

**Comment by glouel** [comment]
Hi @byalextran 

So the problem is, starting with Catalina, and still in Big Sur, Aerial can no longer intercept keyboard presses. So I'm a bit reluctant to add functionalities that are limited to only past OS releases (that I no longer have around to develop on/test, furthermore).  

With 2.0 however, I'm doing a complete overhaul of the video list so hopefully you can spot a lot more easily the videos you want to enable/disable. So maybe that will lower that need.

**Comment by byalextran** [comment]
aww, bummer. curse you catalina (and big sur)! 😅

and yeah, if there's a way for the screensaver to display the name of the video (that matches what's in the settings), that would help in this case. something like china - day - great wall 1. 

thanks!

**Comment by glouel** [comment]
@byalextran check out beta1, there's a specific button to hide the videos you don't like :) 

![Capture d’écran 2020-07-30 à 10 49 32](https://user-images.githubusercontent.com/37544189/88902462-880e2100-d252-11ea-981d-5ab058bc0bd1.jpg)

https://github.com/JohnCoates/Aerial/releases/tag/v2.0.0beta1

There are many other changes so make sure you read the release notes.

**Comment by byalextran** [comment]
@glouel you're a miracle worker! just went through and hid a bunch of videos. super easy/quick process. thanks a bunch! great job with the 2.0 UI refresh.
