### ISSUE TITLE
Fans spinning at full speed during Aerial playback

### ISSUE THREAD

**Issue by hsiktas** [JohnCoates/Aerial#1023]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Air (13-inch, Mid 2012)
- [x] macOS version: 10.15.6 (19G73)
- [x] Monitor setup: Just the built-in display.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

A few minutes after Aerial enables, I can hear the fan of my 2012 MacBook Air spin up very audibly at full speed.
I guess that this is related to GPU acceleration, and I remember that in an older version of Aerial, fan noise was not an issue (even with an external monitor connected). 

Here is what intel Power Gadget shows after I forced TurboBoost to be disabled while Aerial runs:
![image](https://user-images.githubusercontent.com/4571159/88081668-01d24a80-cb81-11ea-9d7f-51571085248e.png)
Please note how the GPU is running at full speed.

And here the CPU usage in iStat Menus:
![image](https://user-images.githubusercontent.com/4571159/88081818-3ba35100-cb81-11ea-91f5-de71569d04ca.png)

I stopped using Aerial ~1 or 2 years ago, but I can't remember an issue like this. Is there maybe a way to enforce software decoding?
The selected video format is 1080p H264, and I already downloaded all videos into the cache.

**Comment by glouel** [comment]
Hi @hsiktas 

Hardware acceleration from Intel GPUs doesn't always work for some reason, especially with some of the newer videos. This is something I noticed too on my 2011 MBA. 

I would recommend that you try to open a video that spinned up your fan with QuickTime player (you can right click a video in Aerial), and see if you get the same issue. 

Long story short, I think that the new videos may use a higher H.264 profile that's not handled correctly by Intel's IGP, even in 1080p.

**Comment by kai-myklebust** [comment]
Hi, I have the same problem, but it has only occurred after i upgraded to Big Sur and Aerial v.2.0.0beta9. (I did both at the same time so cannot rule out which one is the issue)
The fans are spinning up and the CPU temperature rises very soon after the screen saver starts and I can see right after it stops that the legacyScreenSaver-x86_64 (ScreenSaverEngine) process was very active. 
The temperature does not rise when running the same video in QuickTimePlayer, but don't know if this is because it uses the NVIDIA GPU in QuickTimePlayer and maybe the Intel GPU on screensavers?

- [x] Mac model: MacBook Pro (Retina, 15-inch, Late 2013), 2,3 GHz Quad-Core Intel Core i7, NVIDIA GeForce GT 750M 2 GB GPU
- [x] macOS version: macOS Big Sur version 11.0 Beta (20A5343j) first public beta
- [x] Monitor setup: Built-in + external (2560x1440)

**Comment by glouel** [comment]
@kai-myklebust a few things:

- If you were on 1.9.X before, there's nothing that changed in 2.0.0 regarding video playback, so what you get with 1.9.X and 2.0.0 should be exactly the same (barring any mishap with the current macOS SDK I used to compile 2.0.0). If you use the new updater you can quickly go back and forth between beta/release to double check : https://github.com/glouel/AerialUpdater

- In general, my understanding is, Apple is pretty much always using the decoding units (QuickSync) from Intel's CPU, even if a GPU is present (it's a fixed unit not really tied to the GPU part of the CPU). Aerial uses macOS's API for playback (AVFoundation/AVKit) and we can't change the GPU used for decoding when there are two (believe me I tried !). It's also my understanding QuickTime does the exact same thing and as far as I know, there's no option to pick the GPU there ?

In general and prior to Big Sur, what you got in Aerial was 100% what you got in Quicktime (modulo your number of screens, if you play multiple videos obviously, that's another story). So it's a bit weird that you are seeing a different result between QuickTime and Aerial. I've noticed *many* bugs with video decoding in Big Sur so this may just be the Big Sur betas, although I can't confirm that one.

So you can quickly check back 1.9.2 to double check but I'd put that more on the current state of Big Sur, it's still very early and has many rough parts.

**Comment by kai-myklebust** [comment]
Sorry for the late answer, I had problems going back to 1.9.2. But after some time it just worked again. I love the AerialUpdater.

> So you can quickly check back 1.9.2 to double check but I'd put that more on the current state of Big Sur, it's still very early and has many rough parts. Let me know how it goes.

It also happens it in 1.9.2 and the new v2 betas.

> Edit : What about fan speed when you are in the new 2.0.0 UI ? If you select a video it starts playing if it's cached, you can run Activity Monitor alongside to get a sense of what's happening.

It sometimes happens in the new UI and also directly on the front page of the screensaver tab in system preferences (on the page where you click the "screen saver options..."), but never consistently. It almost always uses between 15-30% CPU but only sometimes that is enough to spin the fans, so maybe something else is also happening so the fans spin up. Sometimes the same video spins the fans up and sometimes it doesn't. I haven't found some consistency in when what happens.

Due to the problem with even installing the screensaver at times and other weird problems. I will attribute this to Big Sur beta problems and come back if it happens later on.

**Comment by glouel** [comment]
@kai-myklebust fan spinning is up to the system, based on internal temperature, so there are tons of factors with what you were doing previously, what the rest of your OS is doing, etc. 

The fact that the CPU load is about 10-30% indicates to me it's more a general Big Sur beta issue than anything else. Video playback still seems shaky in beta 4, it throws a tons of errors in console for things internal to their code so my guess is they rewrote parts of it and may not be fully done.
