### ISSUE TITLE
Aerial screen saver stopped working. Once, then started up again.

### ISSUE THREAD

**Issue by MBA-15owner** [JohnCoates/Aerial#1038]
#### General troubleshooting tips
Before logging an issue please check that:
- [x ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x ] Mac model: MacBook Air 2015 13"
- [x ] macOS version: Catalina 10.15.6
- [x ] Monitor setup: 13"

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request
 Aerial screen saver stopped working.

**Comment by glouel** [comment]
@MBA-15owner 

I tried to answer you on the previous message, so please answer this message, if you don't reply to me I can't help you.

If you go into System Preferences and Screen Savers, you"ll see something like this:

![Capture d’écran 2020-08-11 à 10 19 02](https://user-images.githubusercontent.com/37544189/89874606-5b47fb00-dbbc-11ea-9016-f2a3562c0fd7.jpg)

- Is Aerial selected on the left (purple arrow). 

- What do you see in the preview (in green)

- What happens when you click the button (blue)

Your title now says it stopped working once, but works again ? So... does that mean it's fixed for now and still works as expected ?
