### ISSUE TITLE
Little problem with Yosemite 10.10

### ISSUE THREAD

**Issue by jcp25** [JohnCoates/Aerial#1052]
Version 1.7
MacMini with 10.10
Both standard and sea videos 
-
Sometimes the screen black out with only the clock ticking around the screen.
Moved the mouse, back to screen saver and OK till next time.
But... Looks like it's coming from one of the videos.
Actually not a real problem.
Any idea?
Chris

**Comment by glouel** [comment]
@jcp25 so with 1.7 I'll have to check back and let you know. 

In general, first if you think it's a specific video all the time, try to let me know which one that is, it may help.

Second, when the screen blacks out, does it stay that way for multiple minutes ? I'm wondering if for some reason one video is incomplete on your disk and it's waiting out the next one, or if there's something else. 

Following our exchange on macg, can you go look into Console.app and try and find a crash log for 2.0.0 so I can investigate ? 

Thanks !

**Comment by jcp25** [comment]
I tried to find the culprit but no avail!
When the screen blacks out it stays that way... Till I move the mouse.
When it first happened, deleted caches and dl again a few times over 2 weeks but no change. So I don't think it's coming from an incomplete video.
I thought that the problem may come from a video in another format not supported by 10.10. As everything works fine with another mac using 10.13.

Version 2.0.0 on 10.10 -> system not supported.

Thx
Chris

**Comment by jcp25** [comment]
Did what I should have done before. Checked by hand every single video.
Two of them won't open in QuickTime Player:
---
comp_GMT329_113NC_396B_1105_CHINA_v04_SDR_FINAL_20180706_F900F2700_SDR_2K_AVC.mov -> China Night
and
b2-4.mov -> SF Night Downtown and Sutro Tower
---
Took them off and I'll see how it works
I'll keep in touch
Chris

**Comment by glouel** [comment]
Hi Chris

Thanks for following up, so a couple of things: 

- both of these are H.264, and "should" theoretically play on 10.10. Especially the second one which is one of the oldest videos that Apple had (they no longer use that one in tvOS). But macOS/QuickTime/AVFoundation is weird sometimes. 

If you want to double check, you could try this link to download the video and try again in QuickTime : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-4.mov

I would be surprised that Aerial saved an incomplete file, as I probably had 0 report ever about that, but things happen. It's possible those two videos have issues. In that case that would definitely explain what you saw. 

- Regarding the < 10.12 for 2.0.0, it looks like I had bumped up the minimal version in Xcode. I did double check this morning, in order to support weather, I need 10.10 minimal, so 10.9 I'll definitely have to drop. There is another thing that require 10.11 in the new UI, I'll have a look if I can workaround it and let you give it a shot, I'll update you on this.

**Comment by glouel** [comment]
Sorry to close this so late, but I ended up closing support for anything below 10.12, as I just can't manage it. It's already super hard to keep everything working everywhere on 10.12+ to 11.

I highly recommend updating to a newer macOS, if necessary using the tools that enable support on older macs : http://dosdude1.com/software.html
