### ISSUE TITLE
Bad Crash

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1070]
Running Aerial v2.0.1 on a mid-2018 Mac Mini running macOS 10.15.6

I had Aerial settings open to Overlays prefs, and started screensaver to check a font size. 

I clicked my mouse to stop the screensaver, entered my password, and my system was completely frozen. No keyboard response, no clicking. Mouse could move for a while, then stopped. I needed to hard-restart computer.

**Comment by glouel** [comment]
So just to clarify, this is "normal", as of Catalina, that's how macOS kills the 3rd party screen saver, sending a SIGKILL signal to legacyScreenSaver, which is certainly weird but that's how they do things now I guess. 

What's even weirder is how iLife-SlideShow-Extension comes to the mix. I guess that legacyScreenSaver actually loads that one at startup, my guess is it includes either helpers, or the code to some of their old screensavers Apple rewrote for Catalina. 

But this still happens all the time in Big Sur : 
Aug 25 13:15:12 iMac-de-Guillaume-2 com.apple.xpc.launchd[1] (com.apple.ScreenSaver.iLife-Slideshow-Extension[84070]): Service exited due to SIGKILL | sent by iLifeSlideshows[84070]
Aug 25 13:15:17 iMac-de-Guillaume-2 com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Engine.legacyScreenSaver.x86-64[84069]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.

I'll be closing this and centralise all the slowdown/crashes report in the other issue, thanks for the report.
