### ISSUE TITLE
External storage options missing

### ISSUE THREAD

**Issue by custa1200** [JohnCoates/Aerial#1075]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac Pro
- [x] macOS version: 10.14.6
- [x] Monitor setup: Internal 5K

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I used to be able to download and store all the videos on an external storage device i.e. my NAS and point Aerial to that folder. In the latest version this doesn't;t seem available anymore. I'd like to have the option back. Being that my machine only has 1Tb of internal storage offloading anything I can from it is an advantage.

**Comment by glouel** [comment]
@custa1200 please try version 2.0.3, I think I got it correct, I should have resurected that option. But since I can't test it I'm not 100% sure so please report if it doesn't work : 

![Capture d’écran 2020-08-24 à 23 44 40](https://user-images.githubusercontent.com/37544189/91099546-cf29df00-e663-11ea-89ea-6d37ffed2a67.jpg)

You'll have to check that box and then click the pick folder button that will appear.
