### ISSUE TITLE
Aerial only plays a single cached video although download videos is disabled

### ISSUE THREAD

**Issue by Lapsusone** [JohnCoates/Aerial#1108]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Air mid-2013
- [ ] macOS version: 10.15.6
- [ ] Monitor setup: Single external monitor (clamshell) 1440p

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Aerial only plays a single video that is cached although the setting to download videos is disabled. That single video plays every time the screensaver is enabled and loops indefinitely.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5283783/AerialLog.txt)

**Comment by glouel** [comment]
Hi @Lapsusone 

So, if you disable automatic video downloads, you have to download videos yourself. What happened here is that Aerial cached one video as a "last resort" measure and it only plays that since you don't allow it to download new ones. 

So either download a few videos yourself (in the main video list) or enable automatic downloads (and set a limit if you are concerned about disk space).

**Comment by Lapsusone** [comment]
What if I want to only stream videos and not cache them?

**Comment by glouel** [comment]
This is not an option. Streaming is massively unreliable and not supported by Apple servers so it's been removed.

**Comment by Lapsusone** [comment]
OK thanks 💯
