### ISSUE TITLE
Feature Request: bring back the streaming-only option

### ISSUE THREAD

**Issue by qkw24** [JohnCoates/Aerial#1110]
### Feature Request
I miss the old versions that videos are streamed directly on each run, the benefits are:

- Does not occupy disk space (it's expensive to upgrade your Mac's SSD on most modern Macs)

- Get to see different videos **on each run**, without having to wait for cache rotation

While streaming-only will make the screensaver stall when your Internet is down or slow, but that's a trade off that I'm happy to make. It would be great that "streaming-only" option can have its place in settings page, so that user can choose what they want.

**Comment by glouel** [comment]
I've had this conversation many times already on discord and here, short answer is no, I'm not bringing that back, sorry. 

Two points for you to consider : 
- You are willing to make some tradeoffs for your own usage. That's fine for you, but I'm the one that has to handle the complaints and support, if I provide a feature people will expect it to work and I already have a hard time maintaining everything.
- Streaming is not only not supported by Apple servers, it's their servers and their bandwidth you are using for your convenience. Maybe that's fine for you. But what happens when Apple decides to pull their videos from being freely available because Aerial users, collectively, increase their traffic to a point they start noticing ? Aerial has to be a "good citizen" with resources that aren't its own. I have to balance that when it comes to features. 

A 5 GB rotating daily rotating cache will give you pretty much all the benefits from streaming and that's what I support.
