### ISSUE TITLE
Can't switch a Local video from night to day

### ISSUE THREAD

**Issue by Sigmerr** [JohnCoates/Aerial#1111]
MBP 2020
macOS 10.15.6
Default Monitor

I remember a while ago we were able to switch videos between night and day (as in set some videos to play at night, others during the day). Are we unable to assign dates to videos anymore?

**Comment by glouel** [comment]
Are you talking about the builtin videos or your own Local videos?

**Comment by Sigmerr** [comment]
> Are you talking about the builtin videos or your own Local videos?

Local vids

**Comment by glouel** [comment]
Right now there's no editor for this, there used to be one but since then I've added more statuses. So at the moment in order to do that you need to edit a json file.

Go into Settings > Advanced then Open in Finder

In there you'll find a folder with your Local source name. Inside, edit the entries.json. You can replace day by night or sunrise or sunset.

**Comment by Sigmerr** [comment]
That worked, thanks for your time mate
