### ISSUE TITLE
150%+ CPU usage while screensaver is active from VTDecoderXPCService

### ISSUE THREAD

**Issue by ReagentX** [JohnCoates/Aerial#1116]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (Retina, 15-inch, Mid 2015)
- [x] macOS version: 10.15.7 (19H2)
- [x] Monitor setup: N/A

#### Description of issue / Feature request

All SDR 4K HEVC videos use too much CPU, specifically in `VTDecoderXPCService `

**Comment by glouel** [comment]
Hi @ReagentX 

Yes, your Mac CPU doesn't support the hardware decoding of those 10 bit HEVC videos, that's why you get high usage. On that Mac (Mid 2015), I'd recommend 1080p H.264. There's a help bubble next to the video format choice in Settings > Advanced that will tell you more about what your Mac supports.
