### ISSUE TITLE
Blank screen after running OnyX

### ISSUE THREAD

**Issue by nadesco** [JohnCoates/Aerial#1128]
For some reason Aerial displays a blank screen after running OnyX (ver 3.6.8) and rebooting. This has happened twice. I tried uninstalling all Aerial files then reinstalled afresh but to no avail. To get it working again I had to reinstall from a Time Machine back up. 

I looked at Issue #1105 [A fix for the blank screen appearing after installing the screen saver](https://github.com/JohnCoates/Aerial/issues/1105) but the workaround of adding extra Little Snitch rules didn't work. I'd already downloaded the videos to cache anyway.

Couldn't find a way to add screenshots so have listed the OnyX settings. These are the ones which are checked.

**Maintenance**
Rebuilding
- LaunchServices
- dyld's shared cache
- XPC cache
- CoreDuet database
- Spotlight index
- Mail's mailbox (rebuild the index)

Cleaning
- System
- Applications

Misc. options
- Maintenance scripts
- Fonts cache
- Junk items
- Recent items
- Trash 

Cleaning (Options)
- System
- Boot cache
- Kernel and extensions cache
- Components cache

Applications
- Applications cache
- Java and Java Applets cache

Would any one of these settings cause Aerial _not_ to work properly? If so I will uncheck it / them and try again.

Mac 10.14.6 (Mac Mini with BenQ monitor), Aerial 2.1.1.

Thanks

edit; At first I thought the problem was caused by the latest Security (006) and Safari updates (like a month or two ago), but I installed them separately and checked Aerial before running OnyX. They seemed to check out ok.

**Comment by glouel** [comment]
Hey @nadesco 

I'm not particularly familiar with OnyX but there has been issues with some tools of the sort with previous versions of Aerial. They are mostly fixed assuming you are running Catalina/Big Sur but since you are using 10.14.6 there are extra options available to you that may cause this.

From your list, "Applications cache" or "extensions cache" is the potential issue, because this may wipe Aerial's "cache" folder and thus put you in a black screen situation, wiping everything, and you may have a compounded effect with Little Snitch in that case. Assuming you are using defaults settings you should still be fine but obviously something is wrong here. 

So, first thing first, if you go to the Settings > Cache in Aerial, can you tell me using the "Show in Finder" where does your cache point to ? Do you have "Manually pick location" checked or not in here ?

Second, in Settings > Advanced, make sure debug log is enabled, and press "Show in Finder", where is that path ? 

That may narrow it down buy my gut feeling is, OnyX wipes Aerial's files quite simply. The new defaults should prevent this on new installs but you may have different settings so let me know about the paths I asked about and we'll start from here.

**Comment by nadesco** [comment]
Hi Guillaume,

Thanks for your response. 
Using the instructions you gave the route to Cache is  ~/Library/Application Support/Aerial/Cache 
"Manually pick location” is disabled.

In Advanced, clicking Show Log in Finder points to AerialLog.txt being in the same Aerial folder as above.

**Comment by nadesco** [comment]
>That may narrow it down buy my gut feeling is, OnyX wipes Aerial's files quite simply.

Btw, after I ran OnyX the first time and got the blank screen I later found that all the cached .mov files were still in the Cache folder, so I didn’t have to re-download them. Not sure what to make of that. Perhaps I should simply reset all settings but will wait for your reply.

**Comment by glouel** [comment]
Ok so, your cache paths should be safe. Usually cleaning app wipe  ~/Library/Caches/ which was the previous folder Aerial was using for storing the videos, but I changed it explicitely for this.

Since you mention you still had the videos, it's hard for me to guess what went wrong here. Aerial also needs a few files that are stored in ~/Library/Application Support/Aerial/, but there's 0 reason those would be deleted while the cache folder remains intact. 

If you feel like restoring once more, I would love a debug log of that first failed startup, maybe that would tell me what goes wrong, if not I'll try to have a look later this week.

**Comment by nadesco** [comment]
I tried this ...
Clicked Reset All Settings in Advanced
For some reason it took a number of attempts and closing/opening of System Preferences before Aerial actually reset. 
Until that time my preferred videos continued to show in Favourites and other preferred settings did not change back to default. Eventually it did reset so I ran OnyX. After a reboot I noticed that all videos were deleted from the Cache folder (unlike before). Not sure but a Little Snitch setting might have prevented Aerial from downloading new videos on previous attempts, although that shouldn’t have mattered because .mov videos were still in Cache. Anyway I downloaded a couple and manually restored the rest to Cache from a backup. This time it worked as expected.

Out of curiosity I thought I’d retry the Reset All Settings button. First I added a few videos to Favourites and enabled a couple of extra Overlays to make sure they would revert back to factory settings. After clicking Reset, two windows appeared, “Reset all settings?” and “Settings set to defaults” which would indicate that everything was set to default. But after closing System Preferences and reopening I found that the preferences I’d set a few minutes ago were still in place. I tried to reset it quite a few times but the 3 videos in Favourites and non-default Overlays remained as before. 

I then deleted all folders and files to do with Aerial, rebooted and reinstalled it. I repeated the above but no change, the Reset function doesn’t function as it should on 10.14.6. 
I’m not familiar with code but had a quick look at the AerialLog.txt file and found this:  Using dot workaround for video driver corruption

**Comment by glouel** [comment]
Hey again, let me try and answer your questions. 

> I tried this ... Clicked Reset All Settings in Advanced For some reason it took a number of attempts and closing/opening of System Preferences before Aerial actually reset. Until that time my preferred videos continued to show in Favourites and other preferred settings did not change back to default. 

Ok so just to clarify this, in order to fully restart Aerial, you need to close the whole System Preferences, not just Aerial's panel. It's a bit weird but until you fully restart System Preferences it's still in memory. 

>Eventually it did reset so I ran OnyX. After a reboot I noticed that all videos were deleted from the Cache folder (unlike before). 

Ok so I guess that's it then, OnyX deletes the Application Support folder. That's a weird one, deleting `~/Library/Caches/` is considered fine, but `~/Library/Application Support`, not really. That's explicitly why I moved there, because other tools don't wipe it. 

As to which option does that from the one on your list, I guess you need to check their manual or FAQ if they have any, but in general I would recommend, not just for Aerial but for all your software to not use the option that wipe that folder's content. Usually stuff in Application Support can still be regenerated but it's really not something one should do on macOS.

> Not sure but a Little Snitch setting might have prevented Aerial from downloading new videos on previous attempts, although that shouldn’t have mattered because .mov videos were still in Cache. Anyway I downloaded a couple and manually restored the rest to Cache from a backup. This time it worked as expected. 

Ok great and very likely for little snitch. It may be stuck downloading files from githubusercontent (for the video manifests) hence the black screen. I need to make some specific error messages for little snitch users, it's really a pain the way they handle screensavers. 

> Out of curiosity I thought I’d retry the Reset All Settings button. First I added a few videos to Favourites and enabled a couple of extra Overlays to make sure they would revert back to factory settings. After clicking Reset, two windows appeared, “Reset all settings?” and “Settings set to defaults” which would indicate that everything was set to default. But after closing System Preferences and reopening I found that the preferences I’d set a few minutes ago were still in place. 

Ok so I may need to double check that, assuming you did fully close System Preferences. Settings can be finicky on some versions of macOS and off the top of my head I can't remember how I'm doing it. There's a caching system in macOS when it comes to settings and you need to do things in a specific way to get it to wipe the cache, which I may not be doing correctly, I'll have a look. 

> I tried to reset it quite a few times but the 3 videos in Favourites and non-default Overlays remained as before. I then deleted all folders and files to do with Aerial, rebooted and reinstalled it. I repeated the above but no change, the Reset function doesn’t function as it should on 10.14.6. 

Ok so just to clarify, settings are not stored in Application Settings, they are in Preferences (but just deleting the file won't do, because of the cache thing I mentionned earlier). 

> I’m not familiar with code but had a quick look at the AerialLog.txt file and found this: Using dot workaround for video driver corruption

So that one, completely separate, and very normal to see (if you look closely you'll see a faint white dot bottom right corner of the screen when Aerial runs, it's that workaround to avoid garbled graphics output on some Macs).

**Comment by nadesco** [comment]
Thanks for taking the time to go through that post, it was helpful.

> Ok so just to clarify this, in order to fully restart Aerial, you need to close the whole System Preferences, not just Aerial's panel. It's a bit weird but until you fully restart System Preferences it's still in memory.

I made sure to fully close System Preferences each time, I wasn’t just closing the panel. I even rebooted once, yet the preferences I’d set continue to remain, except, that is, for the one time I was able to reset it which seemed to clear the blank screen problem (giving access to the cache), and a slow startup time. 
Anyway the original issue is now sorted which is the main thing. The Reset is still buggy though, at least on my machine, but it doesn’t really affect anything so no problem. I’ll also uncheck those 2 boxes in OnyX that you referred to, it’s handy to know. If you’d like to look at the AerialLog.txt file for any reason then let me know.
Thanks again for your help.

**Comment by glouel** [comment]
Hey sorry for the late reply, glad the main issue is fixed.

I did look at my code to reset settings and indeed basically it's not correct. I need to think about it a bit more on how to properly fix that. Thanks for the detailed report again.

**Comment by nadesco** [comment]
No worries. Thanks for all your hard work.

**Comment by glouel** [comment]
Very late but I fixed the reset issue for next version ;)
