### ISSUE TITLE
Videos Don't Load Ad-Hoc on Big Sur

### ISSUE THREAD

**Issue by mewing** [JohnCoates/Aerial#1131]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 13" 2017 Four Thunderbolt 3 Ports
- [x] macOS version: Big Sur 11.0.1
- [x] Monitor setup: Two external, VX3276-FHD Display, 31.5", 1920x1080, and Dell U2720Q Display, 27", 3840x2160

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5550817/AerialLog.txt)

#### Description of issue / Feature request

I upgraded from Catalina, and Aerial failed to update, I was on 1.6 so I uninstalled and reinstalled to the latest version. Every time I launch, I get a black screen. If I download the videos locally, they work, but I have extremely limited space. Previously, I would download them as they played in the old version, and this works for me, as I have no bandwidth constraints, but it seems like they do not work at all unless I pre-download videos. Is this feature no longer available?

Note I do not have any third party Firewall, or even the native MacOS one, enabled.

**Comment by mewing** [comment]
I see in the FAQ this was removed, unfortunate.

**Comment by glouel** [comment]
Hey there, just to give you a bit more info on what you said

> I upgraded from Catalina, and Aerial failed to update, I was on 1.6

Yep so Catalina introduced new security mechanisms that broke auto updates, that's why you were stuck there with a really old version. And that's why there's a new standalone updater (Aerial Companion) to fix that issue with V2, you can find it here : https://aerialscreensaver.github.io/

> so I uninstalled and reinstalled to the latest version. Every time I launch, I get a black screen. 

I did see your note about not using a firewall, black screen can still happen in some scenarios like trying to force streaming.

> If I download the videos locally, they work, but I have extremely limited space. Previously, I would download them as they played in the old version, and this works for me, as I have no bandwidth constraints, but it seems like they do not work at all unless I pre-download videos. Is this feature no longer available?

So as you've seen, streaming is no longer available for a lot of reasons. But there's now a new rolling cache option + cache limit that you can configure so it uses minimal disk space and still give you something very close to streaming while keeping a very small cache.   

![Capture d’écran 2020-11-17 à 11 34 34](https://user-images.githubusercontent.com/37544189/99379821-71efa380-28c9-11eb-8042-bd72c3b6363f.png)

You can go as low as 1 GB if you want, though at least 2 GB would probably be what I'd recommend. 

Note there's also a bug currently in the rotation system that's fixed in the latest beta (if you use companion, you can pick desired version > beta to get the latest one).
