### ISSUE TITLE
Newest beta dismounts external drives 

### ISSUE THREAD

**Issue by cneb1** [JohnCoates/Aerial#1138]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Late 2014 Mac mini
- [ ] macOS version: Big Sur
- [ ] Monitor setup: ViewSonic 27

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I will try to reinstall to see if it fixes the issue, but when running Aerial Companion (latest beta) all 4 externals from my external bay dismounted. All were formatted as APFS and one is broken into 2 partitions. Upon restart, received a kernel panic. Disconnected external and got back into macOS but takes forever for Disk Utility to show internal drives and externals never mounted after reconnecting. After using Option+R took disk utility close to 5 minutes to finally show the external drives and now running First Aid. I’d recommend pulling for now as I’m hoping I didn’t lose terabytes of data, first time a beta of Aerial has created this issue.

**Comment by glouel** [comment]
Hey @cneb1 

Sorry to hear that. Were you doing something specific with Companion when you saw your issue ? Companion doesn't do much if anything to disks that I can think of ? It could be something else happened around the same time. If you have more info please let me know. 

The only thing that I can think of is Companion checks if you are running it from a volume that starts with the name Aerial (to make sure you don't run it from the disk image). It simply checks the bundle path and warns you if that's the case, which is harmless and not touching the disks directly either.

**Comment by cneb1** [comment]
No worries, things happen. From the menu bar I went to start the app for the first time and right when I did my 4 drives/5 volumes immediately disappeared. Maybe coincidence, but odd it happened right when it went to pull up System Preferences to pull up the options. May I send you the log file later tonight? Right now running First Aid on all my drives in Safe Boot.

**Comment by glouel** [comment]
Thanks for your detailed explanation. Please take care of your disks first, and let me know when you have time. 

Log file would be in `~/Library/Application Support/AerialUpdater` but only if you enabled debug logs there (sadly I didn't enable them by default for everyone). 

One question I may ask, were you using 1.2 before trying 1.2.1beta (it had the new icon too) ? I'm looking at the changes in startup, the only thing I changed was in 1.2 and that was removing the old Companion (which was named Aerial.app) from `/Applications`. Maybe I'm doing something wrong in here though I'm not quite sure where. 

Your volumes weren't system disks I assume ? 

Did you move your /Applications folder to one of those ? 

Sorry for the questions, just trying to figure out what may have happened to you. Best of luck.

**Comment by cneb1** [comment]
You’re welcome!

To answers your questions, I installed 1.2 and moved directly to the newest beta with the new icon. 

No system disk. Here’s a breakdown of the 4 drives.

CCC (Carbon Copy Cloner) drive
iTunes media drive 
File Server 1TB/3TB Time machine drive (this is the partitioned drive)
Media Backup

Applications drive is on the McIntosh HD which is a Fusion Drive. 

All drives are APFS

While in macOS Big Sur 11.0.1 I tried each drive individually and none mount. If in recovery mode, Disk Utility sees them and ran first aid on them all. Only one drive was bad and was repaired. I performed a reset of the SMC and PRAM and now in Safe Boot all drives mount and running repairs. Will see what happens after I finish in Safe Boot. 

I will keep you posted, as you said it may be a coincidence, but it is odd that in recovery mode Disk Utility can see the drives and all come back fine so that rules out hardware issue with the drives or the OWC USB 3.0 external case.

**Comment by cneb1** [comment]
Not sure if this helps you, but found this after getting data and drives back up and running. Took going into Safe Boot, moving data between drives and erasing them. I should have grabbed a screenshot, but drives had no issues before the hiccup, but showed errors with overallocation(?). As mentioned if this was hardware I would imagine that the drives would still show errors even now or would not be mountable when back into macOS. After running the program from the menu bar, as mentioned early that’s when all the drives dismounted, no pop up from macOS of being removed improperly. Also the only time Disk Utility could see the drives was when in Recovery Mode and in Safe Boot. Before working on the drives to get them to mount, I moved Aerial Companion (the newest beta to the Trash), and you’ll see the Aerial Log still shows some activity today. 

I wish I could provide more information and while I would test again, I just don’t have it in me to try again just in case I can’t retrieve my data after a second go around. 

I love your product and I’m by no means upset with what happened, I understand the risk of running a beta and while I can’t attribute it fully to hardware or truly to the beta, but it seems odd that when the only thing running was the app and when I selected Launch from the drop-down at the time this happened. I wanted to let you know just in case others experience the same. Here is breakdown on the hardware and version of macOS at the time.

Late 2014 Mac mini 2.6 Ghz Intel Core i5, 8GB Ram, 1.12TB Fusion drive running macOS Big Sur 11.0.1 with a 42.99GB Boot Camp Partition (all updates applied)

1TB WD Black Drive used for Carbon Copy Cloner
1TB WD Black Drive used for File Server
4TB WD Black Drive used for iTunes Media
4TB WD Black Drive split into two partitions - 1TB for random data, 3TB for Time Machine backups

All external drives were originally in HFS+, but converted to APFS when able to do so by macOS.

Drives housed in an OWC Mercury Elite Pro Qx2 and connected via USB and nothing else connected via USB at that time as keyboard and mouse are wireless.

Thank you for your quick response, and feel free to reach out if you have any additional questions.

Sincerely,
-Chris

**Comment by glouel** [comment]
First, good to hear your data is safe (I hope I read that correctly) and really sorry again that this happened to you. 

> Not sure if this helps you, but found this after getting data and drives back up and running. Took going into Safe Boot, moving data between drives and erasing them. I should have grabbed a screenshot, but drives had no issues before the hiccup, but showed errors with overallocation(?). 

I see. I'm not super familiar but it looks like overallocation is one of those complex APFS issues that aren't handled very gracefully when they happen, I found this background information and possible explanation of why you had to erase/reformat  : https://superuser.com/questions/1437767/how-to-resolve-apfs-overallocation-error-from-volume-vm-without-reformatting-d#1468415

This doesn't explain *why* the whole thing happened at all, but at least that's a good symptom that we can try and track back.

Question : Did every drive show an over allocation error or just one ? 

> As mentioned if this was hardware I would imagine that the drives would still show errors even now or would not be mountable when back into macOS. 

I'll come back to that a bit later but I think it's important to separate a few things: 
- hard drive physical health : Disk Utility will only give you a very basic hard drive health check *if it can* by running the quick S.M.A.R.T diagnostic check. But since you are running disks over USB, it likely does not. Here's an example with a SSD connected over USB 3.0 : 

<img width="1016" alt="Capture d’écran 2020-12-07 à 15 53 40" src="https://user-images.githubusercontent.com/37544189/101365950-b062f780-38a4-11eb-9012-f3006e90a3c0.png">

You can see here for the S.M.A.R.T status, it says "Non géré" here in french which means "Unavailable", while it should say "Verified". This is probably not interesting to you but basically most tools can't read S.M.A.R.T diagnostic status over USB. AFAIK only advanced tools like smartmontools (https://www.smartmontools.org) can sometimes read that info, and it's not a given. I did check their database quickly and it doesn't look like they reference your OWC model although it still may be supported. Long story short, Disk Utility won't be able to report your hard drives physical health so don't rely on that. 

But all of this is independent of whether the drive is mountable/readable or not. You can have a drive that starts failing with bad sectors, but is still mountable/readable. To be clear I don't think that is what happened here at all, but I'd rather separate that.

- filesystem health : Per your comment above, you did experience at least one such issue with one of your APFS containers (if not all). This is what Disk Utility checks for, so when it's not showing errors, it's at this level mostly that you should read that. 

- the SATA controller in the OWC thing : I quickly looked it up and couldn't find the model of the controller on your enclosure, but reading the specs, it strongly looks like a JMicron chip. It's my understanding that you are running it in independent mode and not using any of the RAID modes. 

> After running the program from the menu bar, as mentioned early that’s when all the drives dismounted, no pop up from macOS of being removed improperly. 

So just trying to piece what happened backward, I can see a few things that could cause the mass dismount : 

- macOS's USB Bot driver had a hickup/crashed and lost the connexion to the OWC, that in turn unmounted all drives.

- A power loss happened (could be a micro surge that only affected the enclosure). <- Seems really unlikely

- Maybe a drive had a hickup and disconnected and that throw the whole thing. I did found that note in the user manual from your enclosure (page 7, on Independant mode) : 

```
IMPORTANT: To avoid data corruption it is essential to unmount all drives and turn off the Qx2 before removing or adding a new drive. If you physically remove a drive from the Qx2 without powering it off first, any mounted drives will improperly unmount from the computer.
```

I'm only mentioning this because they explicitly talk about a mass unmount. This seems unlikely timing wise.

All in all, the lack of notification from macOS makes me think it's very likely that something somehow crashed the USB Bot driver. 

> Also the only time Disk Utility could see the drives was when in Recovery Mode and in Safe Boot. Before working on the drives to get them to mount, I moved Aerial Companion (the newest beta to the Trash), and you’ll see the Aerial Log still shows some activity today. 

So first, if you attached files by email, they will get ignored by Github, you need to attach from Github so they show up.

Second, it sounds like you have activity from Aerial (the screensaver) not from Companion which is not running. That's expected, trashing Companion will just trash companion, it won't uninstall Aerial (the screen saver). Makes sense ? 

So the log you are seeing is Aerial (screensaver) log. Aerial Companion's log is separate, it's in `~/Library/Application Support/AerialUpdater/Log.txt`. It is disabled by default though so you probably won't have it. 

> but it seems odd that when the only thing running was the app and when I selected Launch from the drop-down at the time this happened. 

HOLD ON. 

<img width="333" alt="Capture d’écran 2020-12-07 à 16 45 34" src="https://user-images.githubusercontent.com/37544189/101371951-a55f9580-38ab-11eb-8073-e4af0e8271da.png">

Are you saying you experienced the issue while pressing "Launch Now" in Aerial Companion (above in blue), and not just when starting up Aerial Companion (double clicking it ?) ? Did I get that wrong, cause I assumed you had the issue when launching Companion for the first time. So am I reading that correctly ? That precise one ? Or was it one of the experimental launch (windowed/desktop mode) ?

If you remember exactly which one you clicked, maybe it will help me narrow it down a bit. I tried reproducing with various USB enclosures attached today but didn't managed to get anything. 

> I wish I could provide more information and while I would test again, I just don’t have it in me to try again just in case I can’t retrieve my data after a second go around. I love your product and I’m by no means upset with what happened, I understand the risk of running a beta and while I can’t attribute it fully to hardware or truly to the beta, 

Well thanks again for the very detailed feedback you gave, it's always helpful, and for being extremely nice about it despite the horrible experience. And **please** don't try to launch Companion again for the time being, at the very least until we get a better idea of what happened. 

At that point I'm still not exactly sure what happened but if I had to guess, for some reason the macOS USB Bot driver crashed, causing the abrupt multiple disconnects, which corrupted in turn the APFS containers and made the volumes unmountable until you fixed them (and per the link at the very top, that's not an easy thing to do as you experienced).

In a perfect world, nothing an app does should be able to cause a system driver to crash, but bugs happen sometimes in macOS too. If you used the "Launch Now" button as I asked above (the old one), I will note that this button does something "slightly" unconventional, launching the screensaver "normally" requires a call to an undocumented API from Apple. So in order to do that, I do load the login framework from Apple and call a function inside called `SACScreenSaverStartNow`. 

This feature has been in Companion since the beginning though, but maybe a conjunction of stuff made that call bubble up the issue for you, somehow. It still seems fairly unlikely to me, but who knows ? That's the most plausible explanation I have for now, unlikely as it is. 

If you used one of the Experimentals Launch, I'd be even more puzzled. In that case Companion loads Aerial (the screensaver) itself and launches the view in a window. If anything, while there may be issues with my implementation of this (not being able to launch it multiple times, some memory leaks etc, which is why I called it a beta, I'm usually very conservative calling betas things that quite frankly I shouldn't) there's even less interaction with the system as it's just the app doing it's thing and not doing any system calls. 

If you can clarify to me exactly what part of the UI you clicked, and also what happened (besides the mass unmount), maybe there's something to glean here. I would highly recommend you launch Console.app too and look for any crash or hanging report from around the time of the issue, you may need to open the sidebar which is hidden by default, a screenshot here : 

<img width="1252" alt="Capture d’écran 2020-12-07 à 17 59 04" src="https://user-images.githubusercontent.com/37544189/101380523-e6f53e00-38b5-11eb-9fd3-c1b1f626a9ff.png">

Maybe a system log from around that time would tell more. If you right click System.log at the bottom, press show in finder, you'll find multiple log files : 

<img width="1025" alt="Capture d’écran 2020-12-07 à 18 00 27" src="https://user-images.githubusercontent.com/37544189/101380686-1e63ea80-38b6-11eb-8220-bda8832c5bda.png">

There's one per day (the old ones are gzipped), I would highly recommend you make a copy of all the files system.log for further investigation, if you can find the one from when your issue happened and want to send it to me I'll have a look, that log may likely contain the exact answer to what happened.  

Again, sorry this is very long but let me know if you can answer the various questions above, and if you have those log files cause they may be super important in the end.

**Comment by cneb1** [comment]
All good with the data and no worries at all. Things happen and I have a robust backup plan if needed, just didn’t feel like trying to download terabytes of data :-). I will answer your questions below in red for you.

**Comment by glouel** [comment]
> All good with the data and no worries at all. Things happen and I have a robust backup plan if needed, just didn’t feel like trying to download terabytes of data :-). I will answer your questions below in red for you.

Hey, again you can't do that by replying by email to github, I'm having a hard time reading it, can you edit on github ?

**Comment by cneb1** [comment]
Question : Did every drive show an over allocation error or just one ? 

**Interesting thing was all showed this, but the one time I got one drive to “show” in macOS before needing Safe Boot to fix it was my drive labeled File Server but the APFS container would appear/disappear constantly yet the Physical Drive stayed present in Disk Utility. When I tested each drive individually this was the only drive that did show but with odd behavior.** 

As mentioned if this was hardware I would imagine that the drives would still show errors even now or would not be mountable when back into macOS. 

**Correct and all drives have been behaving normally and Disk Utility checks out fine.**

the SATA controller in the OWC thing : I quickly looked it up and couldn't find the model of the controller on your enclosure, but reading the specs, it strongly looks like a JMicron chip. It's my understanding that you are running it in independent mode and not using any of the RAID modes. 

**If I recall it is JMicron and all are in independent mode.**

A power loss happened (could be a micro surge that only affected the enclosure). <- Seems really unlikely 

**No power loss and I do keep my equipment on an APC UPS for graceful shutdowns.**

Second, it sounds like you have activity from Aerial (the screensaver) not from Companion which is not running. That's expected, trashing Companion will just trash companion, it won't uninstall Aerial (the screen saver). Makes sense ? 

**Yes, makes sense.**

Are you saying you experienced the issue while pressing "Launch Now" in Aerial Companion (above in blue), and not just when starting up Aerial Companion (double clicking it ?) ? 

**Correct, after installing Aerial Companion Beta and selecting Launch Now from the drop-down menu is when the issue occurred.** 

**This was my next step to look into the Console app and see if that might help figure out what happened at that moment in time. I will take a look and let you know.**

**Comment by cneb1** [comment]
![Screen Shot 2020-12-07 at 1 51 06 PM](https://user-images.githubusercontent.com/16739307/101392067-41c96e00-3893-11eb-9e2c-eeb1b2365a1d.png)

Will take a look at system.log next for you.

**Comment by cneb1** [comment]
[system.log.txt](https://github.com/JohnCoates/Aerial/files/5654670/system.log.txt)

I see just 4 entries for Aerial which makes sense since this was a clean install as I did a fresh install of Big Sur a day or so before hand. I'm hoping this helps as there were no crash reports listed in Console. Again thank you for your help and as mentioned I love this app!

**Comment by glouel** [comment]
> **Interesting thing was all showed this, but the one time I got one drive to “show” in macOS before needing Safe Boot to fix it was my drive labeled File Server but the APFS container would appear/disappear constantly yet the Physical Drive stayed present in Disk Utility. When I tested each drive individually this was the only drive that did show but with odd behavior.**

This seems fairly consistent with what I read around 

> **Correct and all drives have been behaving normally and Disk Utility checks out fine.**

I think you may have missed part of my message above because you ended up replying to yourself. Disk Utility will likely **not** report any hard drive failure on a disk connected by USB. Check above for more details if interested. 

> **If I recall it is JMicron and all are in independent mode.**

Great.

> **No power loss and I do keep my equipment on an APC UPS for graceful shutdowns.**

Ok !

> **Correct, after installing Aerial Companion Beta and selecting Launch Now from the drop-down menu is when the issue occurred.**

Ok that's interesting. And so did the screen saver launch ? Did it fail to launch ? 

Just to be clear too, this is not beta related, that button works exactly the same in that beta that it did since early Companion versions so if it happened with the beta it could have with any prior versions. 

> **This was my next step to look into the Console app and see if that might help figure out what happened at that moment in time. I will take a look and let you know.**

Thanks for the log, do you remember around what time the issue occured so I can narrow it down a bit ?

**Comment by cneb1** [comment]
Sorry, I didn't include the Disk Utility and SMART portion, but yes I'm aware that Disk Utility does not report SMART status, so I plan to see if I can find something that can provide that information, if possible. I think in the past I used an app called SMART Reporter, but I don't think it has been updated in years.

I just walked through the options again from the drop down to refresh my memory, and it was the Open Settings function that I clicked on when the issue occurred since I recalled System Preferences popping up.

It was around 14:00.

**Comment by glouel** [comment]
> Sorry, I didn't include the Disk Utility and SMART portion, but yes I'm aware that Disk Utility does not report SMART status, so I plan to see if I can find something that can provide that information, if possible. I think in the past I used an app called SMART Reporter, but I don't think it has been updated in years.

No worries, just wanted to be sure you got that part of my message. 

> I just walked through the options again from the drop down to refresh my memory, and it was the Open Settings function that I clicked on when the issue occurred since I recalled System Preferences popping up.

Oh, thanks for remembering that, it may prove important. 

So what happens when you press that button is Companion uses AppleScript (!) to open System Preferences to the correct page (so that you see the screensavers and not the desktop, as both are in the same panel). It's possibly the less harmful piece of code in there.

I'm starting to wonder if the issue wasn't with System Preferences opening more than Companion, and some other module acting up. 

> It was around 14:00.

So I had a very very quick look, it's actually easy to track when System Preferences is launched in Big Sur as it generates a log entry:

```
Dec  7 21:02:46 iMac-de-Guillaume-2 AccountProfileRemoteViewService[1539]: objc[1539]: Class AOSUISpyglassAccountChangeHelper is implemented in both /System/Library/PrivateFrameworks/AOSUI.framework/Versions/A/AOSUI and /System/Library/PrivateFrameworks/AOSUI.framework/Versions/A/XPCServices/AccountProfileRemoteViewService.xpc/Contents/MacOS/AccountProfileRemoteViewService. One of the two will be used. Which one is undefined.
```

You can also narrow down a bit the times Aerial did run, so assuming it opened System Preferences to the correct page, you get entries from legacyScreenSaver at that point. 14:32 would be the first time legacyScreenSaver runs, does that sounds right to you? In any case I don't see much at first glance but I only had a quick look. 

Do you have system preferences panels that were installed by some other apps ? I do see you had backblaze, dropbox etc running too ? 

I think it's likely that something wrong happened when System Preferences was launched by Companion, more than something Companion did itself when you pressed that button. But I would expect to see something in the logs if something crashed and unless I'm not looking at the right time (it's a big log and those constant `Service exited due to SIGKILL` which seem to be a big sur thing as I have them here too), I don't see it.

**Comment by cneb1** [comment]
Sorry the date of the issue was on 12/5 not 12/7, but still around 14:00. Yes, but I don't recall getting those installed until after installing Aerial. I'm surprised there are no Crash Logs.

**Comment by glouel** [comment]
Sorry if I confused you with my paste above from the log entry, I pasted from my own system.log. I can confirm that your System.log file you sent me is from the 5th. 

Here's an extract : 

```
Dec  5 14:32:24 Chriss-Mac-mini legacyScreenSaver[4085]: getattrlist failed for /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver: #2: No such file or directory
```

This is the first time you launched Aerial that day I would guess (by launching the System Preferences panel and opening that tiny preview thing). The "error" is normal here. I do see this 4 seconds later :  

```
Dec  5 14:32:28 Chriss-Mac-mini com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.apple.DiskImageMounter.1152921500312152764.1152921500312152769(501)> [4321]
```

That by itself is not really indicative of anything but who knows at that point. I'll have a further look tomorrow.

Regarding Dropbox/Backblaze:

```
Dec  5 14:28:23 Chriss-Mac-mini com.apple.xpc.launchd[1] (application.com.getdropbox.DropboxMetaInstaller.49152.55500[3549]): Service exited due to SIGKILL | sent by Dropbox[3587]
```

```
Dec  5 14:21:13 Chriss-Mac-mini com.apple.xpc.launchd[1] (com.backblaze.bzserv): This service is defined to be constantly running and is inherently inefficient. 
```

I see those entries too. I would assume that was just before you installed Aerial Companion/Aerial from a quick look.

**Comment by cneb1** [comment]
Thank you for taking a look and yes it was a couple seconds after the System Preferences panel opened with the tiny preview window. Good thing I have a large monitor and the drives weren't covered and I saw them just disappear from the desktop and as mentioned no error pop up or notification from the OS that the drives dismounted. I will Google that string also to see what I can find.

**Comment by glouel** [comment]
Hey again, so I had a second look at your log and sadly couldn't find much more. 

From what's I've seen, the "Coalition cache hit" by itself is just some internal mechanism from launchd. What's significant by itself is launchd which is the system launcher from macOS. That line tends to pop when you launch or relaunch an app.

So 

```
Dec  5 14:32:28 Chriss-Mac-mini com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.apple.DiskImageMounter.1152921500312152764.1152921500312152769(501)> [4321]
```

highly suggests that DiskImageMounter for some reason was restarted. I still don't have any explanation for you but considering all the info we gathered so far, I'm inclined to say that's it's very likely that something in your System Preferences panel (or macOS) caused that issue, and not Companion who just launched said panel. 

The fact that it took a few seconds after the panel popped is also pretty significant in this because after clicking that button, as I said, Companion just launched it via AppleScript, then it should just idle back to doing absolutely nothing. So a likely explanation is that something happened with System Preferences (and maybe one of the extra panels you have installed that gets loaded when it's launched).

This may not be super helpful to hear, but that's my best assessment for now of the information you gave me. I'll still keep an eye on things going south with external drives but for now that's all I found.
