### ISSUE TITLE
Unable to use screensaver as second user on device (iMac)

### ISSUE THREAD

**Issue by swiftyseven-dev** [JohnCoates/Aerial#1141]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac 27" 2020
- [x] macOS version: v11.1
- [x] Monitor setup: built-in display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I have installed Aerial as the root/admin user for this machine. When I login to my child's account, the screensaver is not listed as an option. When attempting to install by running the `Aerial Companion.app`, it shows in the menu bar and notes that the plugin is not installed. After clicking the button to "Install" the plugin, this error screen appears:

<img width="328" alt="Screen Shot 2020-12-22 at 12 40 38 PM" src="https://user-images.githubusercontent.com/4438390/102918510-07e09600-4455-11eb-8385-373fba16556f.png">

I didn't see anything else related to multiple users. This is a personal/household device with no MDM except for Apple's own parental controls enabled.

**Comment by glouel** [comment]
Hey there @seventhaxis 

So because of the sandboxing sadly, Aerial needs (well, this is complicated but let's assume for that to be correct) to be installed for each users *and* have its own cache for each user, which is not great. That's part of the limitations of sandboxing introduced in Catalina. 

So that's why you need to install twice. As to that error, that's pretty weird, I'm not sure if it's the parental controls that blocks network for companion or something ?

I would suggest instead installing manually if you don't mind, please download this : https://github.com/JohnCoates/Aerial/releases/download/v2.2.4/Aerial.saver.zip

Then open the zip, double click, install for your user only (if you install for everyone it makes a mess). Then you should be good. 

I never tried a parental control account but I can give that a look next week if needed.
