### ISSUE TITLE
Auditioning a Video

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1148]
2018 Mac Mini
MacOS 10.15.7
Aerial 2.2.6

Next to the favorite star, I'd add to the each video thumbnail a "play" button that auditions that video, or else activates screensaver with that video loaded (or, if that's not possible, at least queues up that video so if we manually activate screensaver, that video plays).

**Comment by glouel** [comment]
Hey @Jimmbo 

Right now you can enable autoplay for previews in the settings, check here : 

![Capture d’écran 2021-01-26 à 19 56 52](https://user-images.githubusercontent.com/37544189/105891387-e1dc8180-6010-11eb-850d-1ab2ec4850c7.jpg)

It will autoplay cached videos when selected. This is how it was initially but I ended up disabling it by default because... I don't remember. Someone complained I guess. When it's disabled, adding a button to start preview is something that definitely should be added yep. I'll think about it.

**Comment by Jimmbo** [comment]
Thanks, John! I supposed there was a way to do it. But my proposed way would be more intuitive.

I'd at least suggest defaulting the setting you just mentioned "on".

Thanks again! App's looking great, and I really like the new web site!

**Comment by glouel** [comment]
It's Guillaume lol. I know the repo is still under John's name (long story...) but I'm the one taking care of Aerial now. 

And thanks for what you said about the website, the FAQ and many of the content was made by @ZV00 which deserves a lot of praise for it. 

I'll have to check about why I disabled autoplay, I think on was a better default but there was a reason somehow.

**Comment by Jimmbo** [comment]
Sorry, Guillaume, we've spoken many times, I'm embarrassed. John's just easier to spell!

One ridiculously minor thing. When previewing, it would be nice (for ADD people) to know how much more there is to go. If previews could include a time clock without you needing to do a lot of work, it would be neat. It's not worth more than like a minute of extra work, though, obviously....

**Comment by glouel** [comment]
This is defaulted to true in next version
