### ISSUE TITLE
"legacyScreenSaver" in Location Services Menubar

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1149]
2018 Mac Mini
MacOS 10.15.7
Aerial 2.2.6

After activating screensaver, a location services icon apears up in my menubar to tell me Aerial checked my location. That's ok, I did give permission. But can't Aerial be identified as "Aerial" rather than "legacyScreenSaver"? This way sounds dodgy (plus the dodgy capitalization and spacing).

[Screenshot](http://i.imgur.com/8GxtrYn.png)

**Comment by glouel** [comment]
In Catalina, Apple made a new screensaver API (for good reasons, the old one is a security risk), but didn't make it public. So for "old" screensavers, that includes 3rd party like Aerial, but also some Apple screensavers, they made a "bridge" called `legacyScreenSaver.appex`. That's what you are seeing here. I've been waiting for Apple to make it public so I can port Aerial to the "new" API, but that didn't happen yet, even with Big Sur. 

This is why many features no longer work in Catalina and later (skipping a video by pressing right arrow key is the classic example). 

Until Apple provides a better API, I can't change it, because it's literally how macOS works. Is it weird ? Yes, but I can't do anything about it. I did open many radars with Apple about it but so far, still nothing.

Side note, the name isn't dodgily capitalized, it's just how system stuff is capitalized. If you dig around screensavers, many other 1st party screensavers show up under `iLifeSlidshows.appex`

**Comment by Jimmbo** [comment]
Ah, one of those things. Got it!

It's certainly not _so_ bad from the user's end...
