### ISSUE TITLE
Feature request: Allow to only stream videos and not download them

### ISSUE THREAD

**Issue by ikonted** [JohnCoates/Aerial#1154]
I really liked the feature on version 1.9.2 where you didn't need to download videos, but the videos would stream. 
Now it is true that sometimes the streaming didn't work, but most of the time it worked and i had random videos every time, which i enjoyed a lot. I have a base model mac, 128 gb its not a lot especially when you use xcode you need every byte available. The trade-off of the streaming not being 100% was okay for me as long as i didn't had to waste precious space. 

For this reason i downgraded after updating a long time ago. And thought this issue maybe resolved with the newer versions and also liked the companion app idea. Now i can't downgrade for some reason. I have to specify a cache which theoretically would show me the same screen-savers the whole day. And the screen savers are also wasting space.

**Comment by glouel** [comment]
> The trade-off of the streaming not being 100% was okay for me as long as i didn't had to waste precious space.
 
For you, sure, but this is not exactly mindful of Apple's bandwidth. Aerial is tolerated by Apple so far, they haven't made any move to obfuscate the location of their videos, and I'm trying not to give them any reason to change that. 

A rolling cache is a decent compromise (it's how the Apple TV works) and can be set to 1/2 GB which is quite manageable. I have no plan to bring streaming back again, sorry. 

> Now i can't downgrade for some reason. 

In order to downgrade you'll need to uninstall companion first so it doesn't auto update you every time (that's the point). And restart System Preferences obviously after downgrading, per your other issue.
