### ISSUE TITLE
Feature Request: Scriptable message overlay

### ISSUE THREAD

**Issue by klamike** [JohnCoates/Aerial#1157]
#### Description of issue / Feature request

It would be pretty cool to be able to display the output of a bash script as an overlay. You should also be able to set how often the script is run (cron-like interface or every x sceonds).

I read over some issues and I see sandbox limitations are usually the reason this sort of thing wouldn't work. As a workaround, perhaps the overlay can be set to watch a plain text file. Aerial could be configured to re-read the file every x seconds or as scheduled. Then the user could write a script that outputs to that text file so changes get picked up and displayed as an overlay. Does that sound feasible?

**Comment by glouel** [comment]
@klamike 

So I'm not 100% sure of what we can do, in general unix permissions are a bit less strict than the sandboxing stuff (although it's catching up), but here's what I know: 
- I'm 100% sure we can launch processes via terminal. Aerial does use tar from /bin and a few other tools. I also experimented with a couple of other stuff and launching in general is fine. There are some questions to what those sub processes can actually do with regards to the sandbox, but the general idea, roughly possible, though it's all in the details. If you can launch a script that can't do anything, it's not super useful. + all the constraints from sandbox apply to the location of the script, can't be in Desktop/Documents/Downloads, and I can't put an up a file picker dialog to pick a .sh because, sandbox !
- The text file should be even more straightforward, though the constraints on its locations/picker are the same as what I mentionned above.

I'll keep that in mind and no timing on this, but I'll investigate this soonish.

**Comment by glouel** [comment]
@klamike still in the process of implementing this but it looks like this should work fine, I will probably have a beta up before the end of the week.

**Comment by glouel** [comment]
It's working, beta later today : 

![Capture d’écran 2021-03-03 à 14 48 56](https://user-images.githubusercontent.com/37544189/109815770-4d2cfb00-7c30-11eb-86f9-a7c753fa3dcb.jpg)

**Comment by glouel** [comment]
That's literally what I was just adding/testing ;) 

<img width="385" alt="Capture d’écran 2021-03-03 à 16 17 06" src="https://user-images.githubusercontent.com/37544189/109827355-eb728e00-7c3b-11eb-9c40-f3dae99e1b0c.png">

That beta will remove weather as it's kinda broken now with Yahoo quitting on us, I'll ping you when ready, shouldn't be long.

**Comment by klamike** [comment]
Beautiful. Can't wait!

**Comment by glouel** [comment]
Beta is up, if using Companion, switch "Desired version" to beta and update. 

Direct link : https://github.com/JohnCoates/Aerial/releases/download/v2.2.8beta1/Aerial.saver.zip

**Comment by klamike** [comment]
I just got it installed and this is awesome! Thanks for your work!! 

One bug/limitation: I tried using a long-ish running script and noticed that the seconds counter on the Time overlay stops ticking for a bit while the bash script is running. So I tried the script `watch date` which displayed the message `Error opening terminal: unknown.` though it kept the clock ticking.

**Comment by glouel** [comment]
Regarding lag, very possible, I'm not running the script asyncly here so it's likely blocking while running. How long is your script execution ? 

Regarding `watch`, did you install it ? `watch` is not available on macOS by default. But generally, the script needs to end for it to work, which from what I remember of watch, is not how watch works. Just run date in your script.

**Comment by glouel** [comment]
Ok it's fixed for next build

I try not to push 2 builds a day but if you want I'll make a build for you that doesn't appear on Companion. Let me know.

**Comment by klamike** [comment]
Yep, I just tried `watch` to see how it reacts to scripts that don't end. The actual script that I'm looking to run takes about 6 seconds.

I'm happy to wait a few days for the async fix - no need to make a special build. Thanks for your amazing work!

**Comment by glouel** [comment]
@klamike new beta is up with the fix. Also include the new weather provider in beta so if you have issues with weather, disable it.

**Comment by klamike** [comment]
Awesome! Thanks again for your work.
