### ISSUE TITLE
Huge Container Folder

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1158]
I understand this isn't an all-purpose tech support line for screensaver issues, but ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver
seems to hold 42gb of data (and, apparently, growing, as I'm nearly out of drive space), and I have my Aerial cache limited to 32.4gb.

Is this related to Aerial? I'm running v2.2.6 in Catalina, Aerial Companion v1.2.

**Comment by glouel** [comment]
That folder is for the data of every "old style" screensaver, which include Aerial but also all 3rd party and some 1st party from Apple. 

It's quite possible though that Aerial is the one taking up that space. Can you make a screenshot of your Settings > Cache so I can check something ? I've had reports of cache going over the limit that I haven't had time to fully investigate. Thanks !

**Comment by Jimmbo** [comment]
[Here's the screenshot.](http://i.imgur.com/UM94n1t.png)

**Comment by glouel** [comment]
OK that seems ballparkish (though a bit above, but not 42 GB), did you happen to have bought some of the video packs possibly ? That could account for a few extra gigs, those videos aren't part of the cache. 

Double check the size of the path from my edit above, and tell me what that reports if you can, thanks.

**Comment by Jimmbo** [comment]
Yes, I bought the "everything" package of add-ons. I'm surprised and mildly unhappy that the cache limit doesn't restrain add-ons. I see (maybe mistakenly) Aerial as a platform, not a data set, so I would expect my cache setting to cover everything flowing through that platform.

That folder is 41.56gb.

**Comment by glouel** [comment]
Ok so that explains it. 

I understand your mild unhappiness, in a perfect world, those packs would be downloadable at will and part of the cache. That's how I built everything for Aerial. But that's not how they chose to operate, they wanted those packs to be a 1 time download after you buy them and for Aerial to not "cache" those (rotate aka delete/redownload) . So I've added the ability to have "non-cached" videos, and this made everything super complicated.

The size that those packs take is shown in the sources list, but that's mildly helpful. I think I should probably take that size into account and maybe show an extra bar in the screenshot I asked you, so it shows there the size used by those extra videos. 

Part of the reason I don't count it as part of the cache limit is, if you set your cache to 5 GB (the default), then buy the videos, if those are larger than 5 GB total (like, someone like you who bought everything) you'd never see any other video... 

I don't have an elegant solution for this that doesn't include a bunch of support one way or another. But adding more information is probably a good start.

**Comment by Jimmbo** [comment]
More info is always more good!

Now that I have a sense of your headache with this issue, If I were you I’d just let this imperfect compromise stand for a while. Maybe you’ll have fresh ideas about the higher-level “mission” and how you want to implement other content. Unforeseen ideas or developments may force your action, one way or another. 

But in the long run, if nothing substantive changes and this remains an annoyance, I think it makes little sense for an open source dev to kill himself to fully optimize conditions for a third party provider. 

For now, it sounds like you’re not killing yourself and many of us are enjoying the third party content, so I’d urge you to leave it alone rather than risk digging yourself in deeper with fixes over fixes over fixes! But, yeah, please explain better.

**Comment by glouel** [comment]
Been a while but here's how I "fixed" this in upcoming 2.5, I simply added the information about the packs to the Cache page which is also a lot more prominent in the sidebar which has been unified : 

![Capture d’écran 2021-12-31 à 17 22 29](https://user-images.githubusercontent.com/37544189/147832365-baa3e3c8-004c-42d5-82a9-28647668156b.jpg)

This should make things slightly more clear. 

Moving the cache in Monterey will move everything (cache + packs which are internally separate) to the new location, as discussed in the other issue.

**Comment by glouel** [comment]
Fixed in 3.0
