### ISSUE TITLE
Missing videos and another location issue

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [JohnCoates/Aerial#1161]
I replaced my old Mac with a new one and installed Mojave.

Tonight I moved the cache of 1080p videos to a different location and then switched the video format to 4K and re-downloaded all videos in the hi-rez format.

But eight out of nine of the videos in tvOS 10 are missing because evidently they aren't available in 4K. In that event it would be nice if Aerial had the option to download videos in their highest resolution so that none were missing. I'd rather they played in 1080p than not at all. I don't have a 4k monitor anyway, and will probably buy a 2k one.

I seem to be having Location issues again. When I clicked the Test button it said I needed to enable Location Services. So I enabled that and checked ScreenSaverEngine, and then clicked Aerial's time test button, but it still wasn't able to obtain my location. Under Sierra it displayed a "Success" window.

The log says **2021-03-16 02:56:54.519 : Location services enabled**.

But with L.S. enabled and Aerial set to play videos by time, there's no option to detect my location and play only those videos that correspond to my time of day - I must manually select one of four times.

I thought this was resolved in the 2.2.7beta1 release, but maybe it was only resolved for Sierra? Should I install 2.2.6  now that I'm on Mojave?

![Aerial could not get location in Mojave](https://user-images.githubusercontent.com/15519219/111284942-8b66e900-8638-11eb-9c75-33b37aa87105.jpg)

What is the icon on the right? It looks like fire and appears on many videos. If it's supposed to represent hot videos..._why?_

![Aerial icons](https://user-images.githubusercontent.com/15519219/111286417-1694ae80-863a-11eb-8286-29fc1c06149e.jpg)

When I click in the preview pane, the cursor disappears until it's moved. Unless the cursor is over the text or black boxes in the upper left corner, then it stays on screen. Not a problem, just odd.

What exactly does the **Downward Rotation** button do? All I see is the video preview flashes and a Downloading window flashes in the lower left corner. Is it only relevant for streaming videos, not locally-cached ones?

macOS 10.14.6
Aerial 2.2.7beta1

**Comment by glouel** [comment]
> But eight out of nine of the videos in tvOS 10 are missing because evidently they aren't available in 4K. In that event it would be nice if Aerial had the option to download videos in their highest resolution so that none were missing. 

This is exactly how Aerial works. It will download/play whatever is the best/closest format available to what you pick. If you are not using a managed Cache and downloading your videos manually, using one of the download buttons will do the trick. 

If that fails, make sure you give the relevant permissions in Little Snitch to Aerial and not restrict to a particular server. The tvOS 10 videos are, if I recall, on another server from Apple (not sylvan). 

> I seem to be having Location issues again. When I clicked the Test button it said I needed to enable Location Services. So I enabled that and checked ScreenSaverEngine, and then clicked Aerial's time test button, but it still wasn't able to obtain my location. Under Sierra it displayed a "Success" window.

Afaik you need : 
- WiFi
- Location services enabled globally
- Location services enabled for ScreenSaverEngine (for when it runs full screen)
- and and Mojave I would guess, probably Location services enabled for System Preferences for the test button to work (Aerial is hosted by System Preferences on that OS if I recall)

> The log says **2021-03-16 02:56:54.519 : Location services enabled**.
> ![Aerial could not get location in Mojave](https://user-images.githubusercontent.com/15519219/111284942-8b66e900-8638-11eb-9c75-33b37aa87105.jpg)

What else does it say ? It can be enabled (globally) and still get denied. The box implies we get denied which can happen for many reasons, we don't get an explanation from macOS. Check my list above.

> I thought this was resolved in the 2.2.7beta1 release, but maybe it was only resolved for Sierra? Should I install 2.2.6 now that I'm on Mojave?

Keep at least that build I made for you. Or jump on the more recent betas but don't rollback to 2.2.6 as this doesn't have the fix for your very specific usage scenario. 
 
> What is the icon on the right? It looks like fire and appears on many videos. If it's supposed to represent hot videos..._why?_

It represents nature. It's the closest icon available in SF Symbols 1. Each video can be categorized by scene type, that's what you are seeing :

<img width="179" alt="Capture d’écran 2021-03-16 à 12 11 52" src="https://user-images.githubusercontent.com/37544189/111299924-ce34bb00-8650-11eb-8f88-b28c06a5868f.png">

> ![Aerial icons](https://user-images.githubusercontent.com/15519219/111286417-1694ae80-863a-11eb-8286-29fc1c06149e.jpg)

> When I click in the preview pane, the cursor disappears until it's moved. Unless the cursor is over the text or black boxes in the upper left corner, then it stays on screen. Not a problem, just odd.

You will need to elaborate on what pane you are talking about, I'm not sure I'm following ?

> What exactly does the **Downward Rotation** button do? All I see is the video preview flashes and a Downloading window flashes in the lower left corner. Is it only relevant for streaming videos, not locally-cached ones?

It will download all the missing videos you picked from "Currently playing".

**Comment by GitTheHellOutaHere** [comment]
As stated, I downloaded all available videos in 4k - the cache is 32 GB. But the 1080p ones are still missing.
I can copy them over from the 1080p backup folder, but as you confirmed, Aerial should "download/play whatever is the best/closest format available to what you pick." **BUT IT DOESN'T.**

They're the first ones in the 1080p Cache folder: b1-3 to b8-3.

I forgot again that location services only works via wifi (why is that?). Since I'm connected to Ethernet, my wifi is usually off. After enabling it, Aerial displayed my coordinates, and after disabling it Aerial still showed my location. All good there.

I'd never heard of SF Symbols so I Googled it.  Version 1 contains over 2400 symbols and the first one shown on [this page](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) is a leaf.  
![SF Symbols 1 leaf](https://user-images.githubusercontent.com/15519219/111868587-b7ed6e80-8972-11eb-8ee4-735d36ed77c4.jpg)

That's obviously a much better choice for Nature than fire (except in SoCal, where fires have burned most of the leaves), as well as for for Countryside.  I assume that with 2400+ available, there wouldn't be a need to use the same one for multiple categories as now, and that more suitable ones can be found. But since that seems like an incredibly  easy solution, perhaps you have good reason for using the ones you did?

The preview pane is to the right of the videos list.

![Aerial preview pane](https://user-images.githubusercontent.com/15519219/111870177-0bfc5100-897b-11eb-998f-f3ab12ddd822.jpg)

**Comment by glouel** [comment]
> As stated, I downloaded all available videos in 4k - the cache is 32 GB. But the 1080p ones are still missing.
> I can copy them over from the 1080p backup folder, but as you confirmed, Aerial _should_ "download/play whatever is the best/closest format available to what you pick." **BUT IT DOESN'T.**

I'm trying to help you here, I'd appreciate a bit of courtesy.

I'm not sure you read my answer from above, I asked you what happened if you manually try do download one for example : 

> If that fails, make sure you give the relevant permissions in Little Snitch to Aerial and not restrict to a particular server. The tvOS 10 videos are, if I recall, on another server from Apple (not sylvan).

The tvOS 10 videos are on a separate server for which you may not have a Little Snitch rule. This could likely be your issue. I did look it up for you and it's likely : 

```a1.phobos.apple.com```

> ![Aerial missing 1080p](https://user-images.githubusercontent.com/15519219/111870291-c1c79f80-897b-11eb-9472-a9c9163777ca.jpg)

It's very likely you are blocking the server, the fact that there's no thumbnail is a pretty clear sign (those are generated by grabbing the first frame of the video online if the video isn't cached. 

As I said, I would recommend not setting strict rules in your firewall unless you are willing to look up what traffic it denies and fix the issue. I'd recommend checking if other hosts are denied too. 

> I forgot again that location services only works via wifi (why is that?). 

Most location services rely at least in part in a WiFi database. As for the specifics of Apple's implementation, maybe Apple has a description of how it works somewhere. 

> I'd never heard of SF Symbols so I Googled it. Version 1 contains over 2400 symbols and the first one shown on [this page](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) is a leaf.
> ![SF Symbols 1 leaf](https://user-images.githubusercontent.com/15519219/111868587-b7ed6e80-8972-11eb-8ee4-735d36ed77c4.jpg)

Leaf is part of SF Symbols version 2, not 1, which is why I'm not using it. 

Aerial is migrating to native SF Symbols 2 rendering everywhere right now, starting with multi-color icons for weather : 

![110677238-3577e880-81d5-11eb-8e2c-caff14bfa0c8](https://user-images.githubusercontent.com/37544189/111871874-9bf6c680-898c-11eb-9ee6-94bb6e50f74b.jpg)

but that will be limited to Big Sur for the time being. As of right now older OSes are limited to the fallback system currently in place. This may change at some point but the export library I rely on is limited to version 1, so that's what we get for now on old OSes.

> The preview pane is to the right of the videos list.

I see. So that part of the screen is a video player (that may be paused based on your settings in the advanced pane), that's likely why you're seing the cursor disappearing.

**Comment by GitTheHellOutaHere** [comment]
I'm not sure why you thought I was being rude, but I wasn't tying to be. I appreciate all the work you put into this project!

![I sorry kitten](https://user-images.githubusercontent.com/15519219/111888011-c10d2880-89d0-11eb-9bb7-63c29828990b.jpg)


The Google link I clicked said SF Symbols 1.1 Update, so I thought that's what I was looking at. But it must've been v2. Found an [old page for v1](https://developer.apple.com/news/?id=11212019a), but the download has been replaced with v2.1.

I do see that the missing videos are all from the "Online" category. If I right-click on Online and select "cache missing videos," all that happens is the selection moves from "Online" to "Currently Playing."
No connection attempts are shown in the Little Snitch network monitor, so it seems Aerial doesn't try to download those missing videos. Perhaps the URLs have changed and Aerial doesn't know where to go?

Cache is set to automatically download all videos.

You're correct that the 1080p ones are on a different server.
[This](https://s1.mzstatic.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json) is the 1080p json. The phobos.apple links all resolve to s1.mzstatic.com links. The [4K videos are on sylvan.apple](https://sylvan.apple.com/Aerials/2x/entries.json).

In Little Snitch, Aerial Companion, System Preferences and ScreenSaverEngine aren't blocked.

I just noticed that the brightness setting doesn't seem to do anything whether the slider is all the way to the left or right. I set California Dolphins as the only favorite and set Aerial to only play favorites. Then I  started the screensaver with the slider to the left a few times, and then start it with it moved to the right a few times. I didn't notice any difference. I tried again with Approaching Burg Khalifa, which is already dark, but it didn't get darker. It would be nice if there was a preview as there is for vibrance.


...that part of the screen is a video player (that may be paused based on your settings in the advanced pane), that's likely why you're seing the cursor disappearing.

Makes sense.

**Comment by glouel** [comment]
> I'm not sure why you thought I was being rude, but I wasn't tying to be. I appreciate all the work you put into this project!

No worries, I probably misread your message. 

> The Google link I clicked said SF Symbols 1.1 Update, so I thought that's what I was looking at. But it must've been v2. Found an [old page for v1](https://developer.apple.com/news/?id=11212019a), but the download has been replaced with v2.1.

Yep as usual with Apple they move on quickly and don't keep the old stuff around. If you are curious the old version of the tool is here : https://developer.apple.com/design/downloads/SF-Symbols.dmg 

The subset of icon is pretty slim when it comes to nature, they now actually have a new Nature category in SF Symbols 2 which makes it a lot better (and multi-color icons). 

Currently I export SF Symbols 1 as PDFs and use that for icons on all systems (you can only natively use these in Big Sur which I'm starting to add), but the library doesn't handle SF Symbols 2 yet. I may have to move to another export solution at some point as the project is no longer maintained (https://github.com/davedelong/sfsymbols) and I don't know enough about fonts to fix whatever is up. 

> I do see that the missing videos are all from the "Online" category. If I right-click on Online and select "cache missing videos," all that happens is the selection moves from "Online" to "Currently Playing."
> No connection attempts are shown in the Little Snitch network monitor, so it seems Aerial doesn't try to download those missing videos. Perhaps the URLs have changed and Aerial doesn't know where to go?

I think Little Snitch may put these in a special category called fullscreen apps or something, I keep hearing complaints about it works differently than usual apps. 

> Cache is set to automatically download all videos.
> 
> You're correct that the 1080p ones are on a different server.
> [This](https://s1.mzstatic.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json) is the 1080p json. The phobos.apple links all resolve to s1.mzstatic.com links. The [4K videos are on sylvan.apple](https://sylvan.apple.com/Aerials/2x/entries.json).

Ok so, try this : 
- Go to cache settings, put on manual (you can switch back afterwards)
- Come back to main panel, pick tvOS 10 in the sidebar, press the arrow next to a file
- If that fails, attach the part of the log, it may contain information

But I triple checked and it works here : 

<img width="354" alt="Capture d’écran 2021-03-21 à 00 11 21" src="https://user-images.githubusercontent.com/37544189/111888253-22d29000-89db-11eb-83bf-2a9700ff9336.png">

So I'd suggest repeating the process with LS shut off just to test this specifically too. 
 
> In Little Snitch, Aerial Companion, System Preferences and ScreenSaverEngine aren't blocked.

They do block screensavers in a separate way, though I'm not 100% sure this applies to OS prior to Catalina. Basically they auto deny because they can't prompt you, and to make matters worse it doesn't show up where people expect it. If all else fails shut it down during the test above. I tried to reach them about how their handling of screensaver could be improved but it was obviously low priority for them with the many changes happening with Big Sur and removal of kernel extensions. 

> I just noticed that the brightness setting doesn't seem to do anything whether the slider is all the way to the left or right. I set California Dolphins as the only favorite and set Aerial to only play favorites. Then I started the screensaver with the slider to the left a few times, and then start it with it moved to the right a few times. I didn't notice any difference. I tried again with Approaching Burg Khalifa, which is already dark, but it didn't get darker. It might be nice if there was a preview as there is for vibrance.

Are you using a 3rd party screen ? Basically brightness control only works with internal screens (Macbooks/iMacs). There are some 3rd party libraries that can do that with some 3rd party monitors, but they no longer work with Apple Silicon hardware as the DCC commands can no longer be sent through the I2C, so until they fix that I'm not adding that feature. More info here : https://github.com/kfix/ddcctl/issues/86#issuecomment-734523004

**Comment by GitTheHellOutaHere** [comment]
Nothing called fullscreen anything in LS.

I have a LOT of Apple connections blocked - for crap like gamed, studentd, sharingd, touristd, rtcreportingd, Photos Agent, imagent, Siri,  etc. etc. etc.

But I didn't see anything that looked like it should block Aerial downloads and even if it did, there should be a blocked attempt showing up in red.

So it crossed my mind that perhaps the built-in firewall is blocking connections. I turned it off and immediately all the missing videos were shown and when I clicked an arrow the video downloaded from a1.phobos.apple.com. Then I clicked the button to download all videos and they began downloading. I stopped since I can copy them from the backup, and re-enabled the firewall.

At least we've got that figured out!

![Happy Yay Clapping - Stephen Colbert](https://user-images.githubusercontent.com/15519219/111889206-5ad9d300-89db-11eb-819f-d7eafb735a86.gif)

**Comment by glouel** [comment]
> Nothing called fullscreen anything in LS.

I think it's starting with Catalina only then that they added that feature.

> I have a LOT of Apple connections blocked - for crap like gamed, studentd, sharingd, touristd, rtcreportingd, Photos Agent, imagent, Siri, etc. etc. etc.
> So it crossed my mind that perhaps the built-in firewall is blocking connections. I turned it off and immediately all the missing videos were shown, and when I clicked an arrow the video downloaded from a1.phobos.apple.com. Then I clicked the button to download all videos and they began downloading. I stopped since I can copy them from the backup, and re-enabled the firewall.
> At least we've got that figured out!

Ha finally ! Great to hear. So that was the "global" firewall rule set from Little Snitch where phobos ended up being blocked, am I understanding this right ? 

In any case, glad that's resolved.

**Comment by GitTheHellOutaHere** [comment]
No, it was the Mac firewall in System Preferences > Security & Privacy.

**Comment by glouel** [comment]
@GitTheHellOutaHere looks like I missed your edit about Brightness. It only works with built in Apple screens right now, so iMacs, or Macbooks are fine. External displays won't work. I probably need to add a message about that somewhere

While there was a workaround for this, the API that would enable that is no longer available on Apple Silicon, so we'll see what comes up at WWDC this year.
