### ISSUE TITLE
Aerial stuck showing the same video over and over again

### ISSUE THREAD

**Issue by zurdyo** [JohnCoates/Aerial#1163]
Hi there,
It's happened a few times that Aerial gets stuck on the same video, repeating it over and over again, albeit closing the app, putting the computer in sleep or rebooting. Every time I launch Aerial, it's that same video.

The only way to get it "unstuck" is to hide those specific videos, but whenever I make them visible again, then Aerial goes back to looping them again.  

Thanks!

Z

- iMac Pro 
- macOS 11.2.2

**Comment by glouel** [comment]
Hey @zurdyo 

That's weird. Can you tell me : 
- which version of Aerial are you running ?
- maybe a screenshot of your cache settings, that screen : 
 
<img width="1098" alt="Capture d’écran 2021-03-17 à 12 30 06" src="https://user-images.githubusercontent.com/37544189/111460648-82e7de80-871c-11eb-83da-4ca04acf27c5.png">

- and check if you have debug logs enabled (check advanced at the bottom of that screen), and if so attach one here so I can investigate ? 

Also if you know which videos specifically get stuck it may help me narrow it down. Thanks !

**Comment by zurdyo** [comment]
Hi @glouel, thanks for the reply.

I'm running version 2.2.6.

This is the screenshot:

<img width="1098" alt="Screenshot 2021-03-17 at 15 09 15" src="https://user-images.githubusercontent.com/16038140/111480903-be8da300-8732-11eb-8bda-101c493e852f.png">

This is the log:

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/6156971/AerialLog.txt)

**Comment by glouel** [comment]
Ok so, looks like you are in manual mode according to your screenshot, and probably only have one or a few videos downloaded. 

So in that mode, you need to download videos yourself, like the name implies, it's manual, which is why you're probably only seeing one. If you want to keep manual mode, either download all the videos (if you can afford the space, it's north of 30 GB), or pick the ones you like in the main UI and click the download button next to them to start the download, like this : 

<img width="1109" alt="Capture d’écran 2021-03-17 à 16 00 59" src="https://user-images.githubusercontent.com/37544189/111488958-02d07180-873a-11eb-85ce-51263132d958.png">

You can also right click a category in the sidebar (like a location say, Dubai) and press "Cache Missing videos".

What you might want though, is for Aerial to download videos on its own, in that case, check that box in the screenshot that says automatically download videos, you can set a cache limit, and if Aerial should periodically replace videos in the cache with fresh ones.  

Let me know if that clears things up.

**Comment by zurdyo** [comment]
Hey Glouel,
Yes, it does. I actually had 3 videos in that folder and it still got stuck on one only. I guess that when they're so few, this might happen. Thanks for clearing things up for me. I'm putting in automatic. 
Ciao!
