### ISSUE TITLE
Fan starts spinning very loudly as soon as screensaver starts

### ISSUE THREAD

**Issue by T3Ni** [JohnCoates/Aerial#1181]
I have a 13-inch MacBook Pro from 2018 with macOS Big Sur installed. Latest Aerial version 2.3.3.

As soon as the screensaver starts, my fans start spinning loudly and the MacBook starts to get hot. It never stops, even if I leave the screensaver on for hours.

Now, I do understand about background tasks running while the screensaver is on, however, that doesn't seem to be the problem here.

The issue does not occur when I use one of the stock screensavers. It does appear no matter which video quality I select for Aerial (even on 1080p H264). The interesting part is that the fans start spinning even when I use "Launch Aerial Fullscreen on this monitor" in the experimental features or press on "Preview" in the Settings.

If I open the video from the Cache folder in Quicktime on full screen, no fan can be heard even after a long time of it playing, even with 4K HEVC.

Around 20 seconds after the screensaver comes on, even just when clicking "Preview" in the Settings, the fans start spinning loudly and the MacBook starts to get hot.

All videos are cached. I do not use Little Snitch. I do not use iCloud Photos. I do not have a second monitor attached. I do not use any overlays or anything at all, the only option that is activated is "Show with Clock" in the settings.
This issue has persisted at least since upgrading to macOS Big Sur. I remember that a long while ago the screensaver would run and everything is completely quiet. However, I can not pinpoint to when exactly this changed.

Any idea what could possibly cause this problem? Please help. This is driving me crazy.

**Comment by glouel** [comment]
@T3Ni the only known reason I can think of would be if you had the _High Quality Text Rendering_ enabled. For some reason, on some systems, it causes massive CPU usage in Big Sur, never was able to find out why. 

Please check if that's enabled or not for you, it used to be enabled by default for everyone, I did change it however to disabled by default come Big Sur, but if you had a previous install you may have it enabled (or enabled it yourself) : 

<img width="1048" alt="Capture d’écran 2021-06-04 à 15 54 22" src="https://user-images.githubusercontent.com/37544189/120812703-846fb880-c54d-11eb-8c74-9104b225ab3b.png">

Let me know if that does the trick, if not we'll try and investigate. Thanks !

**Comment by T3Ni** [comment]
@glouel  Thanks Guillaume for your help. Unfortunately, "High Quality Text Rendering" is not enabled. I tried to enable and disable it again to see if it makes a difference. Sadly with no success. Any other ideas maybe?

There is one thing I should maybe mention. I am manually overwriting the MBP resolution to display in 1920x1200 HiDPI, which is not supported out of the box on 13-inch MacBooks. However, I've been doing this for years, even before, when Aerial did not cause the fans to go crazy. I don't think this would have anything to do with the way the MBP acts.

**Comment by glouel** [comment]
@T3Ni Ok, that was worth a shot !

Just to make sure it's not the resolution thing, can you send me a log (enable it in advanced, and you can get the file from the button there) after launching it once, just so I can check around and see what it says regarding resolution, there may be some issue around that with something I'm not handling correctly.

**Comment by T3Ni** [comment]
@glouel Sorry, Guillaume for the late reply. I let the screensaver run a couple of time so you get a comprehensive log. You find it attached.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/6602500/AerialLog.txt)

**Comment by glouel** [comment]
No worries. Just to clarify, you are *not* using an external screen, correct ? 

What I see is, you're running 1920x1200 points with a backing scale factor of 2, which is macOS's complicated way of saying you are running your native 2560x1600 as a 3840x2400 (4K+) pixels screen. Is that correct ? 

While it's certainly taxing a bit the GPU because it needs to scale things up and down, I don't believe that should be *more* of an issue for Aerial than it would be for Quicktime. 

Off the top of my head your CPU is probably a Kaby Lake or Coffee Lake which has, again as far as I remember, native decoding for H.265 10 bit, which is what Apple uses for what's called "4K HEVC" in Aerial. So you should have very low CPU usage and full fixed unit decoding. 

I just tripled checked things here using Activity Monitor and the "Launch Fullscreen" function in Aerial Companion. 

**Note : because it's super experimental still, I'd highly recommend that when doing that comparison, you quit and relaunch Companion just to be safe.**

First, this is Aerial running overlays (they have a higher cost because of transparent shadows) : 

![aerial with text](https://user-images.githubusercontent.com/37544189/120895680-6aea7180-c61e-11eb-82c5-ed94334f3431.png)

There are 3 things to track, WindowServer is what's doing the whole desktop composition. So that's displaying, scaling, etc. It's the usually the major power user on Intel Macs and what has the most CPU and GPU usage. Then should come Aerial Companion, and VTDecoderXPCService. This should have a very low CPU usage **if** you are correctly using fixed function video decoding. 

Now this is QuickTime, running the same video : 

![QT](https://user-images.githubusercontent.com/37544189/120895827-08de3c00-c61f-11eb-8051-03543498abe0.png)

You can notice it's noticeably lower, but the first one was not horrible to the point of sending fans spinning hard. 

Now this is Aerial again, same video, with all overlays disabled : 

![aerial without text](https://user-images.githubusercontent.com/37544189/120895903-578bd600-c61f-11eb-9535-d9bfeaded794.png)
 
and that's comparable to QuickTime now.

So, could you please try the last two things here, run quicktime fullscreen (that matters !) and make a screenshot of Activity monitor with the three things visible, and do the same for Aerial Companion in full screen mode, and we'll see if we can glean what sends your fans spinning.

**Comment by T3Ni** [comment]
@glouel There is no external screen connected and never was. Your statement regarding the resolution upscaling is correct. Also correct about the MBP using the Coffee Lake architecture with native HEVC support.

Here is Activity Monitor with Quicktime running in fullscreen (4K HEVC):

<img width="912" alt="Screen Shot 2021-06-06 at 3 41 29 AM" src="https://user-images.githubusercontent.com/85352019/120903759-9b5ff900-c67a-11eb-9907-0ca0f502613d.png">

Here it is with "Launch Fullscreen" in Aerial:

<img width="868" alt="Screen Shot 2021-06-06 at 3 45 27 AM" src="https://user-images.githubusercontent.com/85352019/120903774-b6326d80-c67a-11eb-9abb-4d23a4ee6906.png">

Last but not least here is Activity Manager after running the screensaver from "Preview" in Settings for a while:

<img width="868" alt="Screen Shot 2021-06-06 at 3 47 34 AM" src="https://user-images.githubusercontent.com/85352019/120903790-cd715b00-c67a-11eb-8be4-79ac49882eaa.png">

In the last screenshot you can see two VTCDecoderXPCService instances. This is likely because the video was displayed in the Settings app as well as on fullscreen after pressing "Preview" at the same time.

For the life of me I can't see anything that would explain the fans going crazy like this every time. Note that when I took the second and third screenshot, the fans were already spinning quite fast and noticeably loud.

**Comment by glouel** [comment]
> @glouel There is no external screen connected and never was. Your statement regarding the resolution upscaling is correct. Also correct about the MBP using the Coffee Lake architecture with native HEVC support.

Good !

> Here is Activity Monitor with Quicktime running in fullscreen (4K HEVC):
> Here it is with "Launch Fullscreen" in Aerial:

I'd say it's pretty comparable and overall, pretty low CPU usage, you are broadly 80+% idle, I can't see why you'd feel any difference at least from this. 

> Last but not least here is Activity Manager after running the screensaver from "Preview" in Settings for a while:
> 
> <img alt="Screen Shot 2021-06-06 at 3 47 34 AM" width="868" src="https://user-images.githubusercontent.com/85352019/120903790-cd715b00-c67a-11eb-8be4-79ac49882eaa.png">
> 
> In the last screenshot you can see two VTCDecoderXPCService instances. This is likely because the video was displayed in the Settings app as well as on fullscreen after pressing "Preview" at the same time.

Yep and you can also see two legacyScreenSaver, one hosted by `ScreenSaverEngine` (the fullscreen one) and one hosted by System Preferences (the tiny one). That's how it works nowadays (it wasn't always the case, sometimes it would share the same instance of the screensaver but sandboxing threw everything out) so nothing special to see here, though even here with two instances you are still 80% idle.

> For the life of me I can't see anything that would explain the fans going crazy like this every time. Note that when I took the second and third screenshot, the fans were already spinning quite fast and noticeably loud.

That's puzzling to me as well, I can't see anything from the CPU usage that would justify things getting loud. For all intents and purpose you're near idle. 

I'd recommend installing iStatMenus : https://bjango.com/mac/istatmenus/ you can see various temperatures there, maybe that would tell us something. There's also the free intel Power Gadget https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html

Try to see if you spot any difference with those (again comparing QuickTime and one instance of Aerial, don't do two by using full screen preview on top), maybe ? 

It's also possible Apple changed something on the fan curve mechanism, although, that would be surprising.

**Comment by glouel** [comment]
Closing this, feel free to reopen if you need more help, hopefully upgrading to Monterey fixed it
