### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by 3Dortal** [JohnCoates/Aerial#1183]
#### Required information
- [ ] Mac model: iMac 2017 or 2019
- [ ] macOS version: 10.15.7
- [ ] Monitor setup: built in

#### Description of issue / Feature request
I am trying to reinstall this app yet it seems I am unable to delete all related files,
and com.apple.ScreenSaver.Engine.legacyScreenSaver keeps recreating itself inside of /Library/Containers

is this normal should I carry on? I have little experience with these things...

**Comment by glouel** [comment]
@3Dortal legacyScreenSaver is part of how modern macOS runs the "old style" (so called legacy, anything that ends with `.saver` instead of `.appex`) of screensavers, which includes all 3rd party screensavers, and most Apple's built in screensaver. 

So that container will get recreated anyway, even if you don't use Aerial. See here at the bottom for more details on fully uninstalling/reinstalling : https://aerialscreensaver.github.io/installation.html

**Comment by 3Dortal** [comment]
I see,
as I tried to clean everything the actual screensaver would still be there
no matter what I tried it seems its just part of macOS now I don't know exactly if its aerial or something else
I thought it might be connected guess ill need to try something else, any way thanks

**Comment by glouel** [comment]
> I see,
> as I tried to clean everything the actual screensaver would still be there
> no matter what I tried it seems its just part of macOS now I don't know exactly if its aerial or something else
> I thought it might be connected guess ill need to try something else, any way thanks

Ok maybe I wasn't clear but `legacyScreenSaver.appex` is part of macOS yes, and so is that container folder you are mentioning. If you delete it, it will be recreated next time you launch pretty much any screensaver.

What's happening is, since Catalina, macOS no longer launches screensavers like Aerial (or others) directly, they added a sandboxing mechanism and that's `legacyScreenSaver.appex`. 

Does this make more sense ?
