### ISSUE TITLE
feature request: set playback speed (slower) 

### ISSUE THREAD

**Issue by amlaerxcus** [JohnCoates/Aerial#1187]
I really love Aerial and bought the content from jetsoncreative, it really is mesmerizing. 
I would love to have one more option: adjustable playback speeds for the content. (either in general or for each clip)
Some clips play in real time and especially cars are quite "too fast" in comparison to the slow motion content, to really have this nice slow motion effect everyone is loving, it would be lovely if the playback speed could be set to 75% in the settings. 
Also, it would make the clips a little longer and there would be more time to "feel" the place :)
#

**Comment by glouel** [comment]
Hey there @amlaerxcus 

Did you buy their content when they released or recently ? Because they modified the videos some time ago to make them slower precisely based on this feedback.

Regarding playback speed, it's definitely something I've considered but since they slowed many of their videos I didn't think there would be much demand for that. So let's make sure first you got the new versions.

**Comment by amlaerxcus** [comment]
Hey @glouel thanks so much for the reply! Yes I actually just bought them last week, so I should have the updated versions. I just double checked some footage and now I'm beginning to double guess myself. For example, in the shot "forestville", there are two cars passing over the bridge and it looks like they are on original speed. You can see this on a couple of scenes, but I also might be wrong.

**Comment by amlaerxcus** [comment]
In the scene "Pont de basulu" (Spain) you can definitely see the people moving in normal speed, also the flags wave in real time. A slider for the playback time, like you did with the vibrance filter would be just nice in these cases. But even without it, I think aerial its a brilliant tool and I'm very thankfull you developed it! :)

**Comment by glouel** [comment]
Yep so just to give a bit more explanation, my understanding is, their content was of varying relative speed and what they did was slow most of them and make them all consistent to each other, but some may not be slowed (my understanding was that some didn't look good if slowed too much from their point of view).

I would add though that I don't believe most Apple videos are slowed down, what gives that impression is that they tend to be shot from a far distance (most are shot from a plane I believe, while Jetson used drones, LAX is a great example I think, the planes taxiing look pretty real time to me) and tend to look farther out. The closer you are to what you are observing the faster it goes, there's a Hawaii video (Honopu I think) that's shot from closer to the sea, the waves look pretty normal and the closer you get to the shore the faster things seem to go. This one was shot by a drone it would seem and feels much closer to Jetson's. 

Anyway, back to your idea, I did check again and it should be possible for me to control the playback rate, I'll put it on my list of things to try and let you know, it may take some time though, as this may conflict with some other stuff from what I read. And yep would be implemented the same way as the vibrance filter. 

I'll keep you posted.

**Comment by glouel** [comment]
Well I had some free time this morning and it was much easier than I thought, that should be in Aerial's next beta, sometime later today : 

<img width="1329" alt="Capture d’écran 2021-07-08 à 13 53 43" src="https://user-images.githubusercontent.com/37544189/124917526-3b9b9b80-dff4-11eb-8fa6-e9802e958a3b.png">

Basically you can set playback speed live in the preview (assuming you have auto playback in advanced) and directly see what you'll get. Goes from 0.01x to 2x, there are guides for quarter speeds (so 0.25, 0.5, 0.75 etc...). If you set an arbitrary or too low speed though, the result isn't great as the playback gets jittery. There's not much I can do about that and that's why I didn't put the feature in at first. I do think 0.5 is very acceptable though, and so are other combinations depending on the speed of the original video. 

I think there are still bugs, at the very least with videos with multiple location information (so that's mostly older Apple videos) that will not appear at the correct time. Some other overlays may have issues too.

I have another bug to fix first related to Apple Music integration, songs that you are playing from outside your library miss the artwork, so I'll try to fix that before sending the beta. I'll update here when it's out.

**Comment by glouel** [comment]
It's out, if you use Aerial Companion, set it to beta, version 2.3.4beta4 includes the aforementioned fixes, let me know how it goes for you !

Be aware that if you try speeding up videos, depending on how old is your mac, it can be super taxing. Slowing down makes it easier if you have to use CPU decoding on older mac which is a great side effect.

I may tweak a bit how this works, but it's mostly there.

**Comment by glouel** [comment]
Available now for everyone in 3.0
