### ISSUE TITLE
Feature Request: Changing Storage Location + External Disks

### ISSUE THREAD

**Issue by cansurmeli** [JohnCoates/Aerial#1188]
Hello.

I think it would be really beneficial if Aerial allowed to store the downloaded videos in a different location; especially, an external disk.

My computer stands still almost always and it doesn't have a lot of storage space; let alone for 4K videos. Rather than downloading videos into it or keep streaming them so that my bandwidth gets unnecessarily used, it would be much more efficient to store them in an external drive where storage is no issue. Sure, there is caching as well but I really don't want to waste any space when I really have to carefully consider how to manage 256 GBs.

Obviously, in the end, it is the taste of every Aerial user but it is worthwhile to develop such an option.

Plus, as an additional feature to the above, there could be a one single video stored locally on the computer to play continuously if the external drive could not be located so that the user isn't left alone with a black screen.

What do you think?

Best regards.

**Comment by glouel** [comment]
Hey @cansurmeli 

This is possible but only on some operating systems, because of sandboxing restrictions. Anything before Catalina (Mojave etc) you can set your folder as you wish in the cache settings. However on both Catalina and Big Sur, Apple imposed some restrictions on screensaver that made that impossible. 

The good news is, they fixed it in Monterey. And Aerial is already updated for that, so that option is available again for users on the macOS beta, and it will be for everyone else this fall.

![Capture d’écran 2021-07-12 à 21 48 26](https://user-images.githubusercontent.com/37544189/125347285-09bf6780-e35b-11eb-8094-dfd9eba997a3.jpg)

**Comment by cansurmeli** [comment]
Hey @glouel 

Thanks for the quick answer.

Oh, shoot, I forgot about all of Apple's restrictions for a second. You're right. But it's nice to hear about changes in Monterey! I hope that's not something momentary on Apple's side and makes it into the release.

**Comment by glouel** [comment]
They added some extra entitlements to the new thing that sandboxes screensaver, so I think it's here to stay. But fingers crossed 🙈
