### ISSUE TITLE
Why I can start Aerial when I push touchID button on my MacBook Pro M1 ?

### ISSUE THREAD

**Issue by moykin** [JohnCoates/Aerial#1189]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
M1 MacBook Pro
- [x] macOS version: 
BigSur 11.5.2
- [x] Monitor setup:
Standart + dell 24

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Why I can't start Aerial when I push TouchID or use command+control+Q and my video doesn't start

**Comment by glouel** [comment]
> #### General troubleshooting tips
> Before logging an issue please check that:
> 
> * [x]  You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
> * [x]  Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
> * [x]  Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).
> 
> If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.
> 
> #### Required information
> In order to help us sort your issue, we ask that you provide the following information:
> 
> * [x]  Mac model:
>   M1 MacBook Pro
> * [x]  macOS version:
>   BigSur 11.5.2
> * [x]  Monitor setup:
>   Standart + dell 24
> 
> If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).
> 
> #### Description of issue / Feature request
> Why I can't start Aerial when I push TouchID or use command+control+Q and my video doesn't start

Sorry for the late reply, saw it the other day but completely forgot to answer you.

I don't have a Mac with TouchID but Cmd + Ctrl + Q will lock your screen, and I suppose TouchID does the same thing. 

And this never starts the screensaver in recent macOS, it pops the login screen. You can confirm that while selecting a built in macOS screensaver instead of Aerial, you'll see the exact same thing.

Screensavers don't decide when they launch, this is all on macOS. What you want is to setup a hot corner to launch the screensaver with this button : 

![Capture d’écran 2021-08-30 à 16 14 11](https://user-images.githubusercontent.com/37544189/131353465-5df849b5-5f2e-4bb8-a9ce-16ba5d8f1c7a.jpg)

This way you can start your screensaver whenever you want.
