### ISSUE TITLE
Feature Request tvOS 15 screen savers

### ISSUE THREAD

**Issue by joeldonaldson** [JohnCoates/Aerial#1191]
Looking forward to seeing the new tvOS 15 screen savers in Aerial!

**Comment by glouel** [comment]
It’s already here, check the latest beta 🎉

**Comment by glouel** [comment]
@Breault720 depends on your cache settings & now playing. I will soon simplify all this because I made it way too complex, to try and accommodate every single request from people. 

Can you tell me what you have in here : 

<img width="1098" alt="Capture d’écran 2021-10-07 à 19 16 44" src="https://user-images.githubusercontent.com/37544189/136432802-f63fbab3-0a87-4ddc-94ad-0618456a62ad.png">

**Comment by Breault720** [comment]
Looks like some time before my first comment and now, the tvOS 15 vids became available.

**Comment by glouel** [comment]
Ok great so, in that case, they will download automatically indeed. 

Quick tip, if you just want to play the new ones for some change, you can do this : 
<img width="1109" alt="Capture d’écran 2021-10-08 à 10 00 00" src="https://user-images.githubusercontent.com/37544189/136520039-637dddce-5b1f-452c-9fe9-2f0299761da1.png">

Select plays source > tvOS15 and you'll only have the new ones playing. And you can force download them using the button on the right. 

I really need to make this a bit more intuitive !

**Comment by glouel** [comment]
This is available now in 3.0, and you can pick multiple locations at once, finally ;)
