### ISSUE TITLE
Always samples from all videos instead of filtered selection

### ISSUE THREAD

**Issue by Argon-** [JohnCoates/Aerial#1206]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac 2015
- [x] macOS version: macOS 11.6
- [x] Monitor setup: 2, one external
- [x] Aerial 2.3.4beta8

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Aerial seems to ignore my settings with regard to the selected/filtered videos. Basically, no matter what I do it always samples from all videos, not the category I selected. It also shows hidden videos. Additionally, there seem to be two sets of settings: one for the regular settings dialog and one for the experimental one. The mentioned problem exists even when both settings are set identical.
Moreover, resetting the settings from within the app settings doesn't work. It still remembers its settings. I can nuke them by deleting the plist files and resetting the plist cache but that doesn't help unfortunately.

There are two log files:
`Library/Application Support/Aerial/AerialLog.txt`
`Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/AerialLog.txt`
I suppose the former corresponds to the experimental settings and upload the latter one here: https://gist.github.com/Argon-/1dcdb65a9b445d085bd91cf38b66a63e
There's a lot of "Empty playlist, not good" in there. However, not sure why. I properly marked favorites and the app remembers these. I also selected other categories, e.g. "Nature", which doesn't work either.

**Comment by Argon-** [comment]
So I tested some more and downloaded 3 videos manually (auto download is disabled):

    2021-12-17 16:33:31.374 : Playlist raw count: 23 raw cached count 3 isRestricted: true restrictedTo: night
    2021-12-17 16:33:31.374 : Final count : 2

This means Aerial only considers downloaded videos as valid option? I assumed I can also operate completely through streaming. The randomly picked videos (in case of an empty playlist) aren't downloaded either and streamed on the fly.

**Comment by glouel** [comment]
Hey there

I'll try to have a more thourough look at this over the weekend but to give you a very quick update, it looks like you are using both the regular (screen saver mode) and experimental mode (via companion, the full screen mode). 

So yes, the experimental mode does NOT share any setting with the regular Aerial on 11.6. This is a sandboxing limitation that was introduced in Catalina. 

As to your issue, if I had to guess, it's possible your cache is already full. Aerial in general will not empty your cache of favorited videos. So let's say you have 23 favorites, but change settings to only play night dubai videos, you may end up in a case where your cache is full (so no further download) of favorited videos (so no cleanup of those, I assume you like those), yet your settings want stuff that's different from your favorites.

Does that make sense ? Short answer is, make sure you configure both experimental and regular if you use both and understand they are totally separate on macOS 11.6 because of the sandboxing restriction. Then make sure whatever setting you put don't conflict with your favorites. 

 Hope that narrows things down a bit.

**Comment by Argon-** [comment]
I can assure my cache was not full. In fact, I carefully monitored it to not download anything. So far, whenever there is no video downloaded (zero cache), then the log reports "Empty playlist, not good" for every selection I've tried. Only when there are some videos downloaded will there be a non-empty playlist and this playlist always only contains cached videos. No non-cached videos are considered.

**Comment by glouel** [comment]
Ok I have to rush out in a bit but I'll try to give you a quick explanation of how it's supposed to work. If you are using a recent beta it's quite possible that something is broken, but it's more likely that the playlist generation, because Aerial has soooo many options that can interfere with it, can be insanely counter intuitive. I'm hoping to make that a bit more understandable in next version.

With that said (and taking also into account what I said about experimental being completely separate), taking your example above : 

`Playlist raw count: 23`

This is based on your selection at the top of Aerial's settings, where it says "Aerial currently plays". This count is, how many videos in Aerial's database fit your basic criteria (like "Location" "Dubai" has 6 videos total). 

`raw cached count 3`

This one is how many of those 23 videos are cached currently, here 3.

`isRestricted: true restrictedTo: night`

In settings "Time", it look like you enabled the time restriction (show night videos at night, etc). This will reduce again the playlist to give you the final count : 

`Final count : 2`

This is how many videos Aerial can play, fitting with all your criterias. 

The playlist generation only considers cached videos as in general, Aerial never streams (unless as a complete last resort, Apple servers are fairly bad with streaming, tvOS periodically downloads too and is bundled with a default video, LA night).

So how do you get new videos ? A few things should happen : 

- Before playing a new video, Aerial will look if your cache is full and if it is, will try to free some space from videos that are NOT favorited and does NOT fit your basic criteria (Location Dubai for example). <- This is broken in the latest betas FYI
- After playback started, IF you have "Automatic downloads" enabled, Aerial will queue a video do be downloaded. This happens at every playback start, which means it will slowly fill up. 

If you disable Automatic downloads, well, it will only play what you manually downloaded (which means probably only what you favorited), assuming again they fit the criterias. If nothing fits, that's when you get the empty playlist message. 

Makes sense ?

**Comment by Argon-** [comment]
That makes sense indeed! 
But it's also a little counter-intuitive because none of this is indicated in the setup screen. To illustrate my on-boarding: I was greeted by the setup screen and chose "manual" downloading. Nowhere does it mention that it prefers to only play local videos. So I have it installed and preconfigured now and I think now comes the problem that sets the wrong expectations: without fiddling much, I test it instantly. And it works. No videos downloaded and it works, great!
But now I start to fiddle around, hide some videos, create a playlist. And now... it doesn't work? Well at least regarding my filters. I always get videos (despite having none downloaded).
If there were no stream-fallback I would've never assumed it should work with zero cache. Because it does work with zero cache but only for all videos. From a user perspective the app works, videos work, just my filters are ignored. :) 

My suggestion: display an explicit warning when cache is zero but the user narrows the videos down (filters). I'd also mention this in the setup screen when you select the download strategy but many people will overlook that so an explicit warning in the problematic case (filters but zero cache) might help more.
Personally, however, I'm more in favor of an option to just stream when cache is zero but still respect my filters. Currently, when cache is zero you "take away" my filters, not the videos - they still work. Just not the ones I wanted to see. If preventing streaming is critical, then the error-case for this situation (zero cache) should be no videos, not no filters.

**Comment by glouel** [comment]
I understand how it's counter intuitive and I'll see how to improve that in some way or another.

No video is not a good experience, though it's misleading, I understand that. It's also kind of something I need to keep for people that don't disable automatic downloads as it's a core part of the fallback mechanisms in place.  A warning message may be a better way to fix that without breaking everything, I'll think about it, thanks for the suggestions.
