### ISSUE TITLE
Issue with Bartender and companion

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#1214]
thank you! one thing to note--when i was troubleshooting the cache issue, i saw the menubar icon in bartender as a new item which bartender sandboxes until you move it into the items it actively manages. but when i moved it, i could never get it to actually show up. and now it's gone completely. 

/guy

_Originally posted by @gteague in https://github.com/JohnCoates/Aerial/issues/1210#issuecomment-1015871964_

**Comment by gteague** [comment]
i stopped companion and reran it and confirmed that the menubar item shows up if bartender is quit and it works. also, it shows up when you show the bartender 'hidden items' (although i've dragged it to the 'active items' shelf), but clicking it doesn't yield any action. i'm running bartender v4.1.27 and i even did a hard reset (power toggle), so it would seem to be something changed in the way bartender 'sees' the app now. good luck! /guy

**Comment by gteague** [comment]
sorry to spam the thread, but since i posted the above the companion menubar icon suddenly showed up and is working. i had already tried resets and a power reset and bouncing the systemui daemon and none of those had any effect. and bartender didn't update.

the only thing i did was try a feature of bartender which lets it display items when they're updated and indeed i did get it to show up using that feature by telling it i wanted it to show if the icon image stayed static instead of changing. but although i could see it, the dropdown didn't work. but now it's working and i removed that update function. one anomaly left is that i can't move the position on the menubar using the drag method in bartender, but i was able to move it using the command+drag apple method although i don't know if it'll survive a restart.

so whatever the problem is or was, things are very nearly working now.

/guy

**Comment by gteague** [comment]
sorry to be back once again (!) but i've discovered that 4 more of my menubar items managed with bartender have stopped working as well. i conclude that his latest public beta of monterey i installed about 3 days ago has broken something in bartender--i don't think it's your problem at all. 

hope this saves you some troubleshooting time. :) 

/gu6y

**Comment by glouel** [comment]
Ha good to know, thanks for the heads up !

**Comment by gteague** [comment]
ok, hopefully last comment needed. bartender 4 updated to 4.1.29 today and it has resolved all my issues since i installed the latest public beta several days ago. hopefully it will resolve any issues with ariel menubar icon not showing up or functioning for everyone else as well. /guy

**Comment by glouel** [comment]
Great to hear it was on their side. Thanks for letting me know, take care
