### ISSUE TITLE
wrong preview image

### ISSUE THREAD

**Issue by 0x5e** [JohnCoates/Aerial#1228]
![image](https://user-images.githubusercontent.com/5144674/154809006-9ded0bd7-0451-4b7c-b4d5-0adf05e3ac6e.png)
![image](https://user-images.githubusercontent.com/5144674/154809166-bf8778c3-4ecd-406b-8b92-8a20299296b3.png)

**Comment by glouel** [comment]
Hey @0x5e 

This can happen when the previews are generated, usually it fixes itself as you scroll around. When all the previews have been generated (this depends on your network connections) it shouldn't be an issue again.

**Comment by 0x5e** [comment]
Hi @glouel ,
This is a simple issue often appears on iOS Apps. I can help fix this when I'm free.
I'm in China and download takes a long time, this issue will make app experience really terrible.

**Comment by glouel** [comment]
Yep if you think you can help fix it, don't hesitate if you have some time to do so.

I think the problem is especially complicated in China as Apple servers are either slow or blocked. The thumbnails are generated by fetching the beggining of each file and that can take a lot of time in that case. Thanks !

Thanks for offering to help in any case, take care

**Comment by 0x5e** [comment]
https://github.com/JohnCoates/Aerial/blob/c2a93e3240cefd1f0be2ef4c6d57cac2cfd10a5f/Resources/MainUI/VideosViewController.swift#L725-L732

In the `Thumbnails.get` complete block, the cell may be reused. Maybe we can add a `cell.video == video` protection here?
