### ISSUE TITLE
Homebrew installation does not install for all users

### ISSUE THREAD

**Issue by ChrisNRodman** [JohnCoates/Aerial#1229]
- MacBook Air (M1, 2020)
- Version 12.2.1 (21D62)
- Built-in Retina Display

Hi there,

It looks like when you install the app via a Homebrew cask, it only installs for the user for which Homebrew uses.  For example, if you install Homebrew via the 'admin' account and then you switch to a different user they cannot see the screensaver.  I could install using Homebrew and then use `sudo mv Aerial.saver/ /Library/Screen\ Savers/` but I'm not sure how that would play with updates going forward.

**Comment by glouel** [comment]
Hey @ChrisNRodman 

I'm not sure if it's possible to provide both choices via homebrew, as I mostly inherited the cask and I just try to keep it updated. I understand it's not great to have each user install the saver but that's what I would recommend, so you can maintain auto updates. Moving the file will likely break homebrew and you'll be getting 2 Aerials at next update. 

This is a bit of a side note, but I think it's important to explain that installing for all users won't work as you expect. With Catalina Apple went hard on sandboxing and installing for all users has lost a lot of it's interest. Before Catalina, if you installed for all users, all users could share the same cache, and I could automatically set that up. Catalina broke that, siloing every user to their own sandbox and cache.  

With Monterey you can set a common cache for multiple users again, but it has to be set manually by the user, I'm not allowed to set that up automatically because of sandboxing (which strictly remains per user). Same goes with settings which strictly remain per user. 

So all of that makes installing for all users not something I usually recommend, because the only thing you save is the size of the .saver and there are lots of unintended consequences that are hard to explain. 

That's why with Companion I also only support installing per user today.  

Hope that explains the situation a bit.

**Comment by ChrisNRodman** [comment]
Hi Guillaume!

That explains a lot.  Makes total sense.  Thanks for your hard work on this project.
