### ISSUE TITLE
Spotify Now Playing isn't Showing Up

### ISSUE THREAD

**Issue by scepterdoescode** [JohnCoates/Aerial#1235]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- Mac model: MacBook Pro (13-inch, M1, 2020)
- macOS version: macOS Monterey 12.2.1
- Monitor setup: Single Monitor

#### Description of issue / Feature request
Hello! I want to address this issue that's been skeptical to me. To keep things short, I use Spotify for music, and I've set the music provider with Spotify instead of Apple Music. The problem is that the Now Playing doesn't show up on the screensaver itself.

**Comment by glouel** [comment]
Hi @scepterdoescode 

So just to confirm, two things : 
- Are you using the macOS app for Spotify playback ? That's required for me to grab the tracks
- When Aerial starts it can't detect the currently playing track (because of security restrictions). It should however display any subsequent track from your playlist

Can you confirm that with those two it doesn't work ? I don't use Spotify personnally but unless they changed their client it worked on previous versions.

**Comment by scepterdoescode** [comment]
Hi there! I use the Spotify macOS app, and apparently it works on subsequent tracks. Don’t know why it happens, but I just discover it last night.

**Comment by glouel** [comment]
Ok then, that's "normal". I hope to have a workaround for the current track at some point, macOS makes it hard. It will require Companion to be installed though.
