### ISSUE TITLE
Setting panel disappears

### ISSUE THREAD

**Issue by YunfangHou** [JohnCoates/Aerial#1241]
Using beta version.
The Screen Save setting panel disappears.
<img width="1142" alt="ScreenShot 2022-04-22 at 09 59 41" src="https://user-images.githubusercontent.com/53991651/164673955-fa745c9c-9372-4540-af21-30808d7150df.png">

**Comment by glouel** [comment]
Hi @YunfangHou 

Do you remember by any chance if  you unchecked some videos in More Videos ? I believe this bug appears if you uncheck all the video sources. 

This should be fixed in next version, but in the meantime, you can reset your settings by opening terminal and pasting this (close system preferences first) :

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
```

**Comment by toddmcintire** [comment]
> Hi @YunfangHou
> 
> Do you remember by any chance if you unchecked some videos in More Videos ? I believe this bug appears if you uncheck all the video sources.
> 
> This should be fixed in next version, but in the meantime, you can reset your settings by opening terminal and pasting this (close system preferences first) :
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
> ```

I was having the same exact bug and this completely fixed the issue for me, thanks!

**Comment by YunfangHou** [comment]
> Hi @YunfangHou
> 
> Do you remember by any chance if you unchecked some videos in More Videos ? I believe this bug appears if you uncheck all the video sources.
> 
> This should be fixed in next version, but in the meantime, you can reset your settings by opening terminal and pasting this (close system preferences first) :
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
> ```

The terminal command solve it.

Also, I got to reproduce the bug. First, I download many videos in Setting of Desktop Wallpaper section. Since the settings of Desktop Wallpaper and Screen Saver are independent, those video can not be shown in Screen Saver. 

To solve this problem: 
1. I change the Desktop Wallpaper cache folder location to `Macintosh HD/Users/Shared` folder as you advised.
2. I added the `cache` of Desktop Wallpaper as a video source in the Setting of Screen Saver. 
3. I selected the `sources` in Now Playing in Screen Saver Setting.
4. Preview Screen Saver: Totally nothing. Black screen.
5. Quit Aerial and reopen.
6. The bug appears.

**Comment by glouel** [comment]
To all, 3.0.9 is finally out, sorry for the delay, it should 100% fix that issue. 

@YunfangHou your strategy should work now. Note that one thing you could do on step 2 is set the cache location to `Macintosh HD/Users/Shared` instead of making a source. 

If you do, though, before anything else, you NEED to set the resolution to the same thing on both desktop and screensaver (for example, 4KHDR, in Advanced). Once you've done that, they can share the cache. I would probably recommend disabling "Automatically download videos" on the screensaver side (although, if you configure them the same way, it should still work).  

Both work and there are pros and cons : 

- It seems more elegant to make it a source because only one will "manage" your videos, download new ones, etc. This could be an issue if you use different settings for cache management (like one with unlimited downloads, one with 5 GB limit, which is why you should have one or both with Automatically download videos disabled). 
- The one big drawback is you lose some metadata by making it a source, including (off the top of my head) video names, the video descriptions, whether they are day or night, etc

Again, both should still be perfectly workable. The desktop mode experience is not as good as I want because settings aren't directly shared, so if you see other issues please let me know.  

Personally I run the second scenario here and haven't noticed any issues, but don't hesitate to report stuff.
