### ISSUE TITLE
Aerial does not install 

### ISSUE THREAD

**Issue by GoatEleven** [JohnCoates/Aerial#1247]
Howdy.

Newbie here.  I just installed, er, attempted to install Aerial.  Open the dmg file, drag to applications, go to my screensavers file, it is NOT there.  I tried all of the suggestions on the troubleshooting forums: opening/closing system preferences, restarting, multiple tries...it does NOT install.  I do not have any other savers installed besides the stock ones.  I do not have little snitch.  
Odd thing is I then gave up and went in to remove the app (which is indeed in the applications folder).  But it will not let me delete it and says it is "Open."  It does not show up on a force quit list.  If I try to move it to the trash, I get the same message:  It is "Open" and cannot delete.  

Mac OS 12.3.1
2019 iMac Retina 4k 21.5"

Gist: it is in the applications folder but NOT in the screensaver folder.  It claims to be "open" but it is NOT.  

Any idea?  Thanks.

**Comment by glouel** [comment]
Hey there. 

Sorry about the issue. I assume that after dragging `Aerial Companion.app`to `Applications`, you launched it ? 

Companion should show up in your menu bar here : 

<img width="460" alt="Capture d’écran 2022-05-12 à 20 17 50 1" src="https://user-images.githubusercontent.com/37544189/168142311-a1f461d8-8932-4cc2-ba6a-8c8d343db8f1.png">

It's likely why it says it's "open", because it's there.

If you click it, you'll see a menu that should prompt you to install the screensaver and that should solve your original issue (not seeing it in the screen saver panel). 

To uninstall, click the menu then exit at the bottom (or quit, I'm not sure I remember which). Then you'll be able to trash the app. 

If after uninstall, you want to still give it a shot, you can try manual install by downloading this file, then double clicking the Aerial.saver in your Downloads folder.

Let me know if that's any help

**Comment by GoatEleven** [comment]
D'oh.
This is correct.  I had looked everywhere in the folders, screensavers, Apps, etc. I had never looked UP at the top of the menu bar to see if it was there.  I was following the install instructions that showed it in the screensavers after install.  
Once I clicked on that, I could install it from there and it appeared in screensavers.  
All good now; thanks for the help.

**Comment by glouel** [comment]
No problem, was it the first time you tried it ? I thought that I popped a window the first time at launch, to setup various things and avoid that issue. In any case glad it's fixed, enjoy ;)
