### ISSUE TITLE
[Feature Request] Different Overlay settings for Wallpaper mode and Screensaver mode

### ISSUE THREAD

**Issue by daletman** [JohnCoates/Aerial#1258]
If I use Aerial as Wallpaper, I don't need to have the clock and Battery indicator visible.

**Comment by glouel** [comment]
This is fair. 

I could quickly bring a disable overlays under companion option. Thoughts ?

**Comment by daletman** [comment]
Yes that would be a quick solution. But maybe someone still wants to display Weather or Location on Desktop Wallpaper but additionally Battery and Clock with Screensaver.

Personally I can't really use the Wallpaper festure because I have an Intel MacBook which struggles enough to drive my 2 4K Display 😄

**Comment by glouel** [comment]
@daletman this is fixed in 3.1.4beta1 where there's a new setting top right : 

<img width="1144" alt="Capture d’écran 2022-10-16 à 17 57 13" src="https://user-images.githubusercontent.com/37544189/196045380-6fc3e80d-e174-4e81-a249-b5503a30a284.png">

Also if you are running macOS 12 or 13 already, I would recommend you try the latest Companion beta here : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b2
