### ISSUE TITLE
Blank screen w/ External display when Macbook lid closed on power adapter.

### ISSUE THREAD

**Issue by avlincoln** [JohnCoates/Aerial#1278]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- Mac model: 2021 Macbook Pro 14" M1 Pro
- macOS version: Monterey 12.6.2 (21G320)
- Monitor setup: LG UltraWide set as main display & built in retina display as extension.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

This issue was non-existent before 3.2.1.

Screen saver is blank screen when external display is set as main display and the MacBook lid is closed (while on power adapter).
If "Play videos on: All displays" is selected then it is okay but then both displays will have the screen saver especially while the MacBook lid is open instead of just the chosen main display which in this case is an external monitor.

**Comment by glouel** [comment]
Hi @avlincoln 

So I don't think I touched anything regarding monitor support in 3.2.1. Could you try and check if 3.2.0 is not doing the same thing  ? You can manually get old builds from here : https://github.com/JohnCoates/Aerial/releases

In general there are two reasons something like that would break : 
- some macOS point update messed something again
- I used a new Xcode SDK which broke stuff again

I know there has been a few issues with the latest Monterey updates but those were more around the login screen itself. 

So please try reverting to an old version first so we can try and narrow it down. Thanks !

**Comment by glouel** [comment]
Thanks @avlincoln and sorry for the delay, been super busy. 

My rough guess is that Aerial is not getting correct information on which screen is "main", but this might confirm the issue. I've put a new beta build, compiled with latest Xcode, so that could maybe magically solve things ? Who knows... 

Could you upgrade to https://github.com/JohnCoates/Aerial/releases/tag/v3.2.2beta1

Run it once and when it fails, and send me the AerialLog.txt file (you can get it by going into Advanced). This might help understand exactly what's happenning. 

Again, thanks for your patience.
