### ISSUE TITLE
Feature Request: rename Macos Login entry item to be more Aerial Specific

### ISSUE THREAD

**Issue by LukaszSolo** [JohnCoates/Aerial#1280]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: M1
- [x] macOS version: Ventura 13.1
- [x] Monitor setup: Retina

#### Description of issue / Feature request

Hi,

A tiny, but confusing detail after installation. If you go to macos Settings -> General -> Login items, there's entry listed as below:

![image](https://user-images.githubusercontent.com/1267372/213121778-12b41ba6-fe23-4528-b153-e839ada7c505.png)

By googling I arrived at the previous repo of the project, so I'm guessing it's coming from Aerial? 

It would be nice if it was renamed correctly, as I was this close to simply deleting it :)

**Comment by glouel** [comment]
Hey @LukaszSolo 

So Apple is doing something weird for applications signed by individual developpers and shows their name, instead of the app name for apps coming from the App Store, or signed using company certificates.

I still haven't found a workaround, you can look at this thread here, there's a beta that removes some of the pain, but not that specific one : https://github.com/AerialScreensaver/AerialCompanion/issues/51

Other software have the issue and I'm not entirely sure how to fix this yet, more here too : https://github.com/AerialScreensaver/AerialCompanion/issues/47#issuecomment-1368242312

**Comment by LukaszSolo** [comment]
Ah! I didn't think to search in Aerial Companion. Since you're aware of the issue and it's not on your plate to fix it :), I'll close the ticket. Thank you for quick reply!
