### ISSUE TITLE
(Feature Request (if feasible)) Sanoma like wallpaper option

### ISSUE THREAD

**Issue by Duckbilled** [JohnCoates/Aerial#1315]
#### An option like the native MacOS Sanoma screen saver fading into wallpaper

It would be amazing if Aerial could reflect Sanoma's ability to fade into a still wallpaper.

**Comment by Duckbilled** [comment]
Awesome! I figured out the speed slider (I am on beta), but could not get it to be still, nor did I find an existing FR.

**Comment by glouel** [comment]
For those who haven't tried it yet it looks like this !

![Capture d’écran 2023-08-10 à 14 53 48](https://github.com/JohnCoates/Aerial/assets/37544189/b4ce336e-df6a-4bc6-80a5-a2eedfa4d383)

@Duckbilled make sure you enable betas for Aerial itself too (I know it's a bit confusing), you need the latest Aerial beta (the screensaver) to get the slider to work. 

For best results, again with the beta, make sure you enable the macOS source which contains the 240 FPS assets.

![Capture d’écran 2023-08-10 à 14 56 45](https://github.com/JohnCoates/Aerial/assets/37544189/5b077a5e-9540-4d77-bbcc-045b06158c1f)

Then make sure in advanced you set to 240 FPS. 

![Capture d’écran 2023-08-10 à 14 57 01](https://github.com/JohnCoates/Aerial/assets/37544189/53efaf80-ce92-44b9-885d-e47dd287d4b8)

Then you'll get butter smooth slow wallpaper ;) What I'm working on right now is transitionning from full speed when in screen saver mode to either slow speed (which ever you pick) or paused. This requires however that I'm able to detect on which monitor we are running as a screen saver, and Apple broke that pretty badly. So that's a big blocker at the moment but yep, fingers crossed, that's my goal. We'll likely get per screen/space video too out of it when they fix it.

**Comment by Duckbilled** [comment]
Thanks for the swift replies. 

Just to clarify, I am running S**o**noma beta, and managed to slow down the video from another tvos set, but wasn't able to make it completely still. 

I have a look at the options you provided :)

**Comment by glouel** [comment]
Ha, misread you, press the pause button : 
 
![Capture d’écran 2023-08-10 à 15 11 20](https://github.com/JohnCoates/Aerial/assets/37544189/0f9122d8-b4ce-4b85-a1d0-ed4e565bff0c)

Right now there's a bug where it restarts itself after it wakes up from sleep though, this might be what you are referring to ? Right now you have to pause it again every time, bit of a pain but it should be fixed in next beta soonish.

**Comment by Duckbilled** [comment]
Nice, that sounds like what I am looking for, indeed. I keep an eye out for the next beta's

**Comment by glouel** [comment]
The pause thing is fixed in beta5 @Duckbilled

**Comment by Duckbilled** [comment]
I an going to give it a spin tonight!
