### ISSUE TITLE
MBP Intel, Sonoma: only main display selected (external), but Aerial always starts on both displays (internal AND external)

### ISSUE THREAD

**Issue by p3P4** [JohnCoates/Aerial#1346]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: Macbook Pro, 13-inch, 2018, Four Thunderbolt 3 Ports
- [X] macOS version: Sonoma 14.1.1
- [X] Monitor setup: internal + 1 external (LG 38" HDR WQHD)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I know this bug from early Ventura times ... on the recent versions it was fixed. Now the bug reappears on Sonoma.

Declared the external Display to primary and want to play Aerial only on the this display, if its connected.

The selection dialog shows the correct preview, but the videos always are played on both displays (independent mode), and the fans are spin up, because its intel.

**Comment by glouel** [comment]
Hi @p3P4 

First, can you check the steps on this post, to make sure Sonoma didn't disable Aerial for you ? Pay particular attention on the "show on all screens/spaces" :  https://github.com/JohnCoates/Aerial/issues/1345#issuecomment-1801799563

If all that is good, can you go into System Settings, displays, and make a screenshot of how you have aligned your screens ?

Right now there's an issue where you don't have much vertical overlap between your screens. It's very annoying and the workarounds we found don't work in some specific situations because of this.

**Comment by p3P4** [comment]
Aerial is enabled and settings see screenshots below:

￼


￼

**Comment by glouel** [comment]
Thanks, that does look fine. 

Because the workaround works on delaying stuff, it's possible I missed something around the screen disabled thing, I'll try to have a look tomorrow, see if I can replicate/fix and get back to you !

**Comment by glouel** [comment]
Hi again @p3P4 

I found the bug, for some reason it "kinda" worked if enabled for main display only (but not correctly) and I think that's why it wasn't reported earlier. 

Thanks for the heads up, I'll let you confirm it works for you but I'm fairly confident it's fixed in 3.3.5 : https://github.com/JohnCoates/Aerial/releases/tag/v3.3.5

**Comment by p3P4** [comment]
Wow - this was quick! Thank you, good work! :)

**Comment by anthonybaldaccini** [comment]
Aerial does not span on multiple displays? Any way to fix this?
