### ISSUE TITLE
Sonoma not spanning across two monitors

### ISSUE THREAD

**Issue by OneEyeMackay** [JohnCoates/Aerial#1355]
Mac mini 2023 M2
Sonoma 14.2.1
Twin Dell P2419H monitor

*Screen saver kicking in but showing as duplicated and not spanning across monitors*

Photo attached shows settings in companion and in system preeferences

The option to just select Ariel in screensavers isn;t there - you need to pick one of five options of specific folders

Thanks

Ross

Companion V 1.5.2
![Screenshot 2023-12-23 at 14 49 30](https://github.com/JohnCoates/Aerial/assets/154686064/eb3d9d55-61ca-463b-9842-31c1d722b19c)

**Comment by glouel** [comment]
Hi @OneEyeMackay 

What you selected is the Sonoma stuff by Apple, which is why you don't get Spanned. 

The real Aerial is there, Apple is just hiding it by default.

![Capture d’écran 2023-11-06 à 00 55 01](https://github.com/JohnCoates/Aerial/assets/37544189/bc6fdb7f-5678-4907-ade0-784ba971bff5)

- See the other section at the bottom
- Scroll all the way to the right, or press "Show All" (next to other)
- Then you can select Aerial. Make sure to check show on all spaces too, just like my screenshot.

**Comment by OneEyeMackay** [comment]
Thank you so much and my sincere apologies for my own stupidity. This is an instant fix … and I love the app!

I really appreciate your help and for your time to develop this product

Hope you have a lovely Christmas

Ross

**Comment by glouel** [comment]
No problem, I can tell you you are not the first one, the confusion between the macOS stuff and original Aerial is large, and Apple automatically enables their new thing when you upgrade to Sonoma to make things worse 😅

Wish you a wonderful xmas too ! Take care !
