### ISSUE TITLE
Does it support MacOSX 10.11?

### ISSUE THREAD

**Issue by marcmoore** [JohnCoates/Aerial#149]
Looks like it doesn't support.

**Comment by alistairmcmillan** [comment]
Works perfectly on 10.11 for me. In what way is it not working for you?

**Comment by marcmoore** [comment]
Restart my computer. And it's kind work now.

**Comment by r3wn5** [comment]
Hey,
A small heads up, I'm experiencing some problems on 10.11
A have iMac 27" 5K with a secondary monitor (DELL 24") and after a couple of seconds of screen saver, both screens stuck with the frame of the running screensaver. I think this is a bug on 10.11 because if I run it with no monitors connected it works wonderfully!

Hope this will be fixed. Thanks for this awesome screensaver!

**Comment by mastescarhead1** [comment]
Doesn't work on 10.11.2 beta though

**Comment by alistairmcmillan** [comment]
Closing as resolved.
