### ISSUE TITLE
Connection fail: Error Domain=NSURLErrorDomain Code=-1001 "The re...

### ISSUE THREAD

**Issue by jacobgraf** [JohnCoates/Aerial#155]
Getting this error about 30-60 seconds after clicking the "Download Now" option under cache settings.

The error is cut off so I can't see the whole thing. Can't resize the window and can't select the text to copy and past the whole thing.

**Comment by Markyt1977** [comment]
Domain eror
On Nov 9, 2015 10:43 AM, "Jacob Graf" <notifications@github.com> wrote:
>
> Getting this error about 30-60 seconds after clicking the "Download Now"
option under cache settings.
>
> The error is cut off so I can't see the whole thing. Can't resize the
window and can't select the text to copy and past the whole thing.

**Comment by Markyt1977** [comment]
On Nov 9, 2015 12:46 PM, "Markandconnie Tegeda" <markanconnie@gmail.com>
wrote:
>
> On Nov 9, 2015 12:46 PM, "Markandconnie Tegeda" <markanconnie@gmail.com>
wrote:
>>
>> Domain eror
>> On Nov 9, 2015 10:43 AM, "Jacob Graf" <notifications@github.com> wrote:
>> >
>> > Getting this error about 30-60 seconds after clicking the "Download
Now" option under cache settings.
>> >
>> > The error is cut off so I can't see the whole thing. Can't resize the
window and can't select the text to copy and past the whole thing.

**Comment by jacobgraf** [comment]
Not sure what happened, but I don't understand your replies.

**Comment by krohn** [comment]
I'm getting this "connection-fail-error" when trying to prefetch the videos (options > cache > download now). But this only happens while behind a firewall. No problems at home.
Are you behind a firewall, too?

Just a guess: The videos are downloaded from a source that can not be reached through port 80 / 443 and therefore blocked while behind a firewall?

**Comment by jacobgraf** [comment]
Yes, I am behind a pfSense firewall at home and work.

**Comment by jacobgraf** [comment]
@krohn Do you happen to be running a proxy of any sort on your network? (Squid, Squid3, etc?)

**Comment by krohn** [comment]
@jacobgraf 
Yes, at work I am behind a Squid and a firewall and a second one and this and that and and... Nearly everything is blocked ;-) Trying to download ends up in an timeout like described by you. 
At home, I have full access to the internet and the download works just fine.

I'm sure you'll see it in the logs of your pfSense Firewall what exactly is blocked and you should be able to define an exception if you have access to the pfSense configuration. 

If not, a dirty workaround might be: Find someone near you with full access, let him install and download the files. You'll find them in /Library/Caches/Aerial/. Copy them onto your machine and enjoy.
Good luck!

**Comment by bryandmlee** [comment]
I clean installed macOS High Sierra, and was going to re-download the Aerial videos, but it seems I now get this error too. I've tried on WiFi and on Ethernet (granted it's the same network), and turning of macOS's Firewall, but all to no avail. Any advice?

**Comment by alistairmcmillan** [comment]
@bryandmlee Are you running the [latest version of Aerial](https://github.com/JohnCoates/Aerial/releases)? Are you behind a corporate firewall or proxy?

**Comment by bryandmlee** [comment]
@alistairmcmillan Yup, I downloaded v1.2 on High Sierra (had been using that version since its release on El Cap/Sierra previously). It's my home network, and I had previously downloaded the Aerial videos fine. (I guess I should have just backed them all up offline before wiping my Mac, but I figured I would be able to redownload them.) The only other system protection I have is Sophos Home for Mac, though that's always been active on my system previously too.

**Comment by alistairmcmillan** [comment]
@bryandmlee Can you reach http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json in a web browser?

If you can reach that okay, can you reach http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov in a web browser?

**Comment by bryandmlee** [comment]
@alistairmcmillan Hmm yeah, both are fine.

**Comment by bryandmlee** [comment]
I just tried again, and Aerial cache started working. (Maybe it's because it's morning now where I am, perhaps the large file sizes triggered a temporary block last night when I was first trying, not sure.)

Came across a separate issue though, where System Preferences would keep unexpectedly shutting down (i.e. crashing) after the first video was downloaded. I checked out the manifest list .json and manually downloaded the second video to the cache folder, and tried the automatic caching again and it continued. Eventually System Preferences crashed again a few more times, but I just repeated the steps. Managed to finally get all 50 (non-duplicate) videos cached. (Oddly enough, the crashes happened on two Dubai and two Hawaii videos. Who knows.)

I guess we can close this/my case now. Thanks @alistairmcmillan for your help (and for posting the .json link)!
