### ISSUE TITLE
ScreenSaverEngine errors in Console

### ISSUE THREAD

**Issue by kgoldmann** [JohnCoates/Aerial#208]
I've been getting tons of these error messages in the Console:

03.02.16 13:29:03,585 ScreenSaverEngine[22225]: [13:29:03.585] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.33/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754

Full log here: http://pastebin.com/shN6E2CN

Am I wrong in assuming they are caused by Aerial?

**Comment by JohnCoates** [comment]
You're right that it's caused by Aerial. Looks like something is going wrong with loading. Is it working alright for you?

**Comment by kgoldmann** [comment]
It works perfectly. I have all the videos cached, might have something to do with that?

**Comment by GitTheHellOutaHere** [comment]
I've been seeing the same. I also have the files saved locally.

7/24/16 12:16:21.155 PM System Preferences[42967]: [12:16:21.138] FigDiskCacheRepositoryGetFileSize signalled err=-12625 (kFigDiskCacheRepositoryError_UnregisteredID) (Specified id not in the cache.) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/DiskCacheRepository/DiskCacheRepository.c line 1089
7/24/16 12:16:21.155 PM System Preferences[42967]: [12:16:21.155] <<<< FDCP_Limited >>>> FigLimitedDiskCacheProvider_CopyProperty: Error getting available cache size - -12625
7/24/16 12:16:21.155 PM System Preferences[42967]: [12:16:21.155] <<< FigByteStreamFactory >>> fbfs_CreateURLStreamAsync: switch from disk to memory backed because of insufficient disk space
7/24/16 12:16:21.296 PM System Preferences[42967]: [12:16:21.296] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:21.423 PM System Preferences[42967]: [12:16:21.423] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:21.725 PM System Preferences[42967]: [12:16:21.725] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:21.725 PM System Preferences[42967]: [12:16:21.725] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:24.722 PM System Preferences[42967]: [12:16:24.722] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:31.213 PM System Preferences[42967]: [12:16:31.213] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:31.805 PM System Preferences[42967]: [12:16:31.805] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:32.202 PM System Preferences[42967]: [12:16:32.202] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:32.788 PM ScreenSaverEngine[43081]: [12:16:32.787] FigDiskCacheRepositoryGetFileSize signalled err=-12625 (kFigDiskCacheRepositoryError_UnregisteredID) (Specified id not in the cache.) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/DiskCacheRepository/DiskCacheRepository.c line 1089
7/24/16 12:16:32.788 PM ScreenSaverEngine[43081]: [12:16:32.788] <<<< FDCP_Limited >>>> FigLimitedDiskCacheProvider_CopyProperty: Error getting available cache size - -12625
7/24/16 12:16:32.788 PM ScreenSaverEngine[43081]: [12:16:32.788] <<< FigByteStreamFactory >>> fbfs_CreateURLStreamAsync: switch from disk to memory backed because of insufficient disk space
7/24/16 12:16:32.829 PM ScreenSaverEngine[43081]: [12:16:32.829] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:32.830 PM ScreenSaverEngine[43081]: [12:16:32.830] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754
7/24/16 12:16:33.791 PM System Preferences[42967]: [12:16:33.791] FigClientHandledCustomURLProviderSendResponse signalled err=-12663 (kFigHTTPError_ParamErr) (No matching request found) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.206/Prototypes/FigHTTP/FigClientHandledCustomURLProvider.c line 754

**Comment by alistairmcmillan** [comment]
macOS is chatty. This is a "feature" of the operating system. Not much an individual screensaver can do about this.
