### ISSUE TITLE
Screensaver prevents display from sleeping

### ISSUE THREAD

**Issue by valerieosmith** [JohnCoates/Aerial#259]
In Settings > Energy Saver, I have my displays set to turn off after a time period. I noticed that my displays will never turn off when I use Aerial as a screensaver.

**Comment by valerieosmith** [comment]
I unchecked "Wake for Wi-Fi network access", and after a brief test of setting the screensaver to launch after 1 minute, and the display to sleep after 2 minutes, it seems to work. Closing this.

**Comment by alistairmcmillan** [comment]
Hi @valerieosmith, if your screens aren't turning off when you use Aerial, it could be because you are running an old version of the screensaver. That was a bug that John fixed a while ago.

You can get the most recent version (that fixes some other bugs and adds some features) here:
https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by valerieosmith** [comment]
@alistairmcmillan Great, thanks!
