### ISSUE TITLE
main tab is empty

### ISSUE THREAD

**Issue by iahu** [JohnCoates/Aerial#312]
Hi, anybody know why my `main` tab is empty ？Thanks.
![image](https://cloud.githubusercontent.com/assets/1704588/22144540/0c3b6a66-df39-11e6-90b9-2b03ff1982cf.png)

**Comment by alistairmcmillan** [comment]
Most likely you are getting this because the screensaver has been blocked from talking to Apple's servers. That's where it gets the videos and crucially the file that lists the videos.

If you have a local firewall like Little Snitch check that it hasn't blocked the screensaver.

If you are behind a corporate proxy/firewall it might have blocked the screensaver. In that case if you can connect your Mac (assuming it is a portable) to another network, you can cache all the files from the "Cache" tab and it'll run essentially in offline mode on your corporate network.

**Comment by iahu** [comment]
Thanks @alistairmcmillan. 
Can I download the videos via a browser, but not the Cache tab? tanks again.

**Comment by alistairmcmillan** [comment]
@iahu Are you behind a firewall or corporate proxy or something? If Aerial is being blocked by something out-with your control then the browser might be blocked too.

Can you get to http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json in a browser?

**Comment by iahu** [comment]
Yes, I can access your link.Thanks!
I use a corporation network, which maybe with a firewall.

**Comment by alistairmcmillan** [comment]
@iahu So what happens if you try one of the links in that file? For example http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

Do you see the movie play in your browser?

**Comment by iahu** [comment]
Yes, can play it. It must be a network firewall issues.

**Comment by alistairmcmillan** [comment]
@iahu Try deleting the screensaver and installing a fresh copy from [here](https://github.com/JohnCoates/Aerial/releases). Some times the Aerial.saver file can get corrupted.

If that doesn't work, if you are on a MacBook, try connecting it to another network (like your home network) and caching the files through that. Once the data is caching it should run quite happily without network access.
