### ISSUE TITLE
Aerial Screensaver - MacBook Pro OS Sierra

### ISSUE THREAD

**Issue by shaguib** [JohnCoates/Aerial#334]
Dear GitHub,

Hope this e-mail finds you well.

Kindly note that I was extremely excited to use the Apple TV's Aerial Screensaver on my MacBook Pro - OS Sierra -  10.12.3 (16D32)

After downloading the application and using it for a few days, it suddenly stopped working and told me that the Aerial version needs to be updated by th vendor.

Kindly advise...

Best Regards,

Shady Sherif.

**Comment by alistairmcmillan** [comment]
@shaguib There is a bug in macOS. It has been reported to Apple, but they haven't fixed it.

But there is an easy workaround.

1) Select Aerial in System Preferences. You may see that error message.
2) Close System Preferences with Aerial still selected.
3) Re-open System Preferences. You shouldn't see the error message.

Please try this and let us know how you get on.

You can read more about the bug here. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by curiopraxis** [comment]
10.12.1 - above workaround did not fix issue.

**Comment by alistairmcmillan** [comment]
@curiopraxis Did you definitely close System Preferences with Aerial selected and then reopen it? If so there are some other steps I'd like to you try to try to establish what is causing this error.

**Comment by alistairmcmillan** [comment]
No reply from @shaguib or @curiopraxis. Closing.

**Comment by djroed** [comment]
Unfortunately, I am having this problem too. New iMac out of the box running OS Sierra 10.12, upgraded to 10.12.6. Installed Aerial and got the dreaded message. Tried the fix a few times. Also deleted and reinstalled. I won't have this iMac after today, but I'd be interested in the other steps to try to establish what might be causing the error.

**Comment by djroed** [comment]
Quick follow up for those who might be looking for answer. I had given up on using Aerial, chose another screen saver, then left the machine alone and running. When I came back to it, about 30 minutes later, I opened the system prefs/screensaver and noticed that Aerial now showed a picture in the choose frame. I chose it and it worked. Maybe it needed time to populate a video? At any rate, that process worked and it's up and running in all it's splendor.

**Comment by alistairmcmillan** [comment]
@djroed  We know exactly why this error is being caused. It isn't a mystery. There is a bug in macOS.

When you load a screensaver that is written using Swift, System Preferences loads the Swift libraries into its process. Unfortunately there are multiple copies of the Swift libraries for each release of Swift. And System Preferences will only load one set of the libraries at a time.

So if you open System Preferences with a screensaver selected that needs version 1 of the Swift libraries then System Preferences will load version 1 of the libraries, but if you select a screensaver that needs another version of the libraries you will get the error saying "You cannot use the ... screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver."

The only way to get System Preferences to load a different version of the libraries is to close it and start again. But to make sure it loads the correct version of the libraries needed by Aerial, you need to open it with Aerial selected or another screensaver that uses the same version of the libraries.

This is what you must have done. The "another screen saver" you mention must use the same version of the libraries that Aerial uses. So when you selected Aerial the correct version was loaded.

The bug has been reported to Apple. The rdar number is 25569037. It is now one year and three weeks old.

**Comment by djroed** [comment]
Ok. That's fine. My point was that I followed your instructions to open system prefs/screen saver, select Arial ScreenSaver, close System Prefs (leaving Arial Selected), then opened it expecting to see Arial work, per Your instructions. It did not work. I did this a number of times. Just did not work, period. I think this is where many people reporting having the same experience as me are getting confused. Perhaps it works every time for you, that's great. But you should understand, as many users are reporting, that the procedure you are recommending just doesn't work every time. That's all I am saying. I don't understand the where's and why's, bug or not,  but I do understand what I experienced. So maybe others can keep my experience in mind and hopefully not give up on Aerial. I think it's the best screensaver going on the Mac or any platform right now.

**Comment by alistairmcmillan** [comment]
And that's why my instructions ended with "Please try this and let us know how you get on." So that if it doesn't work I can try to help people figure out why. :)

You are right a few people try this and it doesn't work. My best guess is that if it doesn't work then something else is loading the Swift libraries into the System Preferences process and not just a screensaver.

It's easy to confirm if this is what is happening, and even work out what is doing it. If someone follows the instructions I posted above and STILL gets the "Please contact the vendor to get a newer version of the screen saver." message, then they just need to...

1) Open Activity Monitor with SystemPreferences still showing the error
2) Select the SystemPreferences process
3) Click the Information button
4) Select the "Open Files and Ports" tab
5) Copy the files and ports information into a text editor (there will be a LOT of files listed) and search for "libswift". This will show where the Swift libraries are being loaded from. It will look something like this...

```
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/MacOS/iOS Saver
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftAppKit.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftCoreGraphics.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftDarwin.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftDispatch.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftFoundation.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftObjectiveC.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftQuartzCore.dylib
txt
/Users/alistair/Library/Screen Savers/iOS Saver.saver/Contents/Frameworks/libswiftSecurity.dylib
txt

```

Alternatively they can copy and paste that info from the "Open file and ports" tab and send it to alistairmcmillan75@gmail.com and I'll look through it myself to work out what is causing the issue.

**Comment by djroed** [comment]
And that is exactly why I posted my experience, due to your invitation :)  Thank you for posting the other steps. I do set up and maintain all kinds of Macs for people. If the issue with Aerial happens again, I'll send you the data. I didn't mean for my post to reflect badly on you in any way. I understand it is a bug in the OS that Apple hasn't responded to yet. I appreciate that you took the time and effort, and used your skills to bring Aerial to the Mac as a screen saver. I always set Aerial as the default screen saver, and it's a pleasure to see the look on my clients faces when I demo it for them.

**Comment by alistairmcmillan** [comment]
Thanks, but it's John Coates' screensaver. I just try to help answer people's questions here and on other random projects. John deserves all the credit for Aerial.

**Comment by djroed** [comment]
Ah, my bad. Thanks or your helping contribution.  And all Kudos to John !
