### ISSUE TITLE
You cannot use the Aerial screen saver with this version of macOs

### ISSUE THREAD

**Issue by mzdhr** [JohnCoates/Aerial#344]
You cannot use the Aerial screen saver with this version of macOs
mine is: 
macOS Sierra
version 10.12.4
iMac 21.5 late 2013

**Comment by flamerock** [comment]
Im on that same version, my only difference is that I am on a 15" MacBook Pro late 2012 (Retina).

**Comment by alistairmcmillan** [comment]
@mzdhr @flamerock 

1) Select Aerial in System Preferences.
2) Close System Preferences.
3) Re-open System Preferences.

The error should now be gone.

If you still see the error please let me know.

**Comment by alistairmcmillan** [comment]
If you are curious why this is happening, it's a bug in macOS caused by multiple different versions of the Swift libraries. You can read more about it here.
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

It was reported to Apple over a year ago. They still haven't fixed it.
