### ISSUE TITLE
It does not work on EI Capitan

### ISSUE THREAD

**Issue by UltraREX** [JohnCoates/Aerial#39]
At first, thank you bring this to mac, but I found a probelm after install or copy to ~/Library/Screen Savers.

**Comment by ritz078** [comment]
Its working fine for me . just double click on the file and it itself gets installed. No need to copy it.

**Comment by kasaijana** [comment]
Same here. Installing an preview is working, but its not starting like my regular screensaver. Display stays black.

**Comment by tobsen** [comment]
Do you have have Litte Snitch or an other firewall installed?

**Comment by yeluolei** [comment]
not working for me too with copy to  ~/Library/Screen Savers and with install is stay black

**Comment by jaromeroes** [comment]
For me it install when double clicking, but the video stops after 1-2secs of loading, is this normal?

**Comment by kasaijana** [comment]
@tobsen Thanks, that was the point. Didn't notice it...

**Comment by damdeez** [comment]
Got a similar issue. I am behind a firewall though, could that be an issue? Also using multiple displays.

**Comment by blklane** [comment]
Didn't work for me due to Little Snitch, but after updating the rule works perfectly, thanks!

**Comment by TheForth99** [comment]
I am on Mac Book Air with El Capitan and the screen saver starts and the animation runs between 1 and 3 seconds than stops or freezes, no recovery or continuation. No Little Snitch installed, firewall is the one that comes with El Capitan. Any thoughts?

**Comment by alistairmcmillan** [comment]
@UltraREX @damdeez @jaromeroes @yeluolei Did you get the screensaver working?

**Comment by damdeez** [comment]
My issues still persist BUT they appear to be happening behind a firewall only. On my home network the screensaver works fine.

**Comment by TheForth99** [comment]
Yes, thought it to be a firewall/router related issue, but I have tried it
at multiple homes and the results seem to be random. I have more the
impression that it has to do with resource loading on the laptop, the
network latency or the server where the video gets served from. I say that
mainly, because it seems random between the various themes. Sometimes they
work, sometimes they don¹t. Are the various themes/videos locally stored or
are they network server, or are they only the first time network served and
then cached on the local drive?

From:  Damir Harambasic <notifications@github.com>
Reply-To:  JohnCoates/Aerial
<reply+00ab8a5b0a31819a756732e39783a7d94d0305c085a583b992cf0000000112d480079
2a169ce06c796c5@reply.github.com>
Date:  Thursday 11 February 2016 at 5:59 PM
To:  JohnCoates/Aerial <Aerial@noreply.github.com>
Cc:  Berthold Langer <TheForth99@gmail.com>
Subject:  Re: [Aerial] It does not working on EI Capitan (#39)


My issues still persist BUT they appear to be happening behind a firewall
only. On my home network the screensaver works fine.


Reply to this email directly or view it on GitHub
<https://github.com/JohnCoates/Aerial/issues/39#issuecomment-182958332> .

**Comment by alistairmcmillan** [comment]
Older versions only stream the videos from Apple's servers.

Please try the latest release here. You can tell it to cache the videos on your machine. This should resolve the firewall/network issues your seeing.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by TheForth99** [comment]
OK, downloaded the new version. It seems to work. I will watch it under
various conditions and report back in a few days. Thanks for the update. -
Berthold 

From:  Alistair McMillan <notifications@github.com>
Reply-To:  JohnCoates/Aerial
<reply+00ab8a5ba56ab05a648fdb8fd266518d2786418616d4da2392cf0000000112d48ab79
2a169ce06c796c5@reply.github.com>
Date:  Thursday 11 February 2016 at 6:45 PM
To:  JohnCoates/Aerial <Aerial@noreply.github.com>
Cc:  Berthold Langer <TheForth99@gmail.com>
Subject:  Re: [Aerial] It does not working on EI Capitan (#39)


Older versions only stream the videos from Apple's servers.

Please try the latest release here. You can tell it to cache the videos on
your machine. This should resolve the firewall/network issues your seeing.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5


Reply to this email directly or view it on GitHub
<https://github.com/JohnCoates/Aerial/issues/39#issuecomment-182974495> .

**Comment by yeluolei** [comment]
the new version work for me now~

**Comment by alistairmcmillan** [comment]
@yeluolei Try enabling the caching option. Once you have a complete copy of the videos on your machine, you should be unaffected by network issues.

**Comment by yeluolei** [comment]
@alistairmcmillan that works!
