### ISSUE TITLE
Not working on my MacBook Air 2017

### ISSUE THREAD

**Issue by opedrohen** [JohnCoates/Aerial#393]
Hey! I love Aerial, but the live images are not working on my 2017 MacBook Air. They freeze. I think its a problem of hardware that doesn't support high images like this. I don't now what to do :(

**Comment by alistairmcmillan** [comment]
Pretty sure your MacBook should be able to play the Aerial videos okay.

Make sure you have the latest version... https://github.com/JohnCoates/Aerial/releases/tag/v1.2

Try caching the videos so they are just being played from your hard drive instead of streamed from Apple's CDN partner. You can find the caching options inside the screensaver preferences including a "Download Now" button that will pull them all down to your MacBook as quickly as your network allows.

Let us know how you get on.

**Comment by remidsouza** [comment]
I got myself a MBP just last weekend, upgraded to High Sierra and installed the aerial screensaver that works perfectly on my 2010 iMac and 2015 MBA. On the MBP, I see the image flash and then the screen is filled with cross line (resembling static). The MBP has no graphic auto switching have installed v1.2 as suggested above but can't seem to get the screensaver working. Any advice?

**Comment by alistairmcmillan** [comment]
@remidsouza The graphical glitches are discussed here... #377 . It appears there is a problem with the High Sierra drivers for the Intel chipset. Hopefully Apple will fix this in a point release.

**Comment by AsydRayn** [comment]
Having the same issue with MBA 2017. Just screen scramble...sometimes it works, but it's random and intermittent.

**Comment by alistairmcmillan** [comment]
@AsydRayn People are discussing this bug here... #377 

No reply from @opedrohen. Closing.
