### ISSUE TITLE
Local Manifest

### ISSUE THREAD

**Issue by esetnik** [JohnCoates/Aerial#509]
Create a manifest file of media asset urls instead of downloading the manifest. Inspired by @glouel https://github.com/JohnCoates/Aerial/issues/463#issuecomment-424744678 and https://github.com/JohnCoates/Aerial/issues/494#issuecomment-425480512

The goal would be to reconcile all available 1080p and 4k assets into a single manifest so that we don't need to lose out on videos which are no longer available in newer manifest urls.

**Comment by glouel** [comment]
Just to clarify, I think we should pull each JSON exactly once (or use already downloaded file, which will give us offline mode). Maybe put them in a subfolder for each "json" (there are 3 that we know of tvOS12, 11, 10)

In case of the tvOS12 .tar file we are using right now, inside there's also a bundle of localized strings. On tvOS 12, those includes extra descriptions as the video progresses forward, those are linked to timestamps/keys in the JSON. 

So having those is pretty important too as we can use them to display those descriptions.

**Comment by esetnik** [comment]
@glouel what's the specific advantage of downloading the content vs. just creating our own list and storing it in the repo? It seems easier and less fragile to just create our own manifest than to rely on merging multiple downloads (which might disappear at any time).

**Comment by glouel** [comment]
Considering the JSON is what is used by tvOS, I'm not convinced it's more fragile. Should Apple deprecate old version of tvOS, they'll probably pull the plug on the videos and JSON. 

But it's just a LOT of contents with the bundle strings included in the tar. If you can, check the TVIdleScreenStrings.bundle file (1.4 MB). 

I'm also not convinced that bundling that file with the project is a good idea in terms of copyright (it's definitely a step further than including URLs as we currently do).

**Comment by glouel** [comment]
Agreed on all this.

Here's how I see it : 
- Fix AerialVideo to allow having videos that aren't available in every format 
- At first startup, pull each json, save locally (and we can try loading that instead of pulling first to get offline mode)
- Also provide our extra info (based on id, we add data for space/land day/night etc)
- We then can reconcile everything in a local manifest that will then be used from now on

I think in order to get that to work, we can make the list much larger and put icons on the right side showing day/night etc, and maybe if available in 4K, etc. 

One other change that will be needed in that merged list, the ability to play "best available format". Let's say I have 4K HEVC as a setting, but I want to add an old 1080p video, we should then play that.

**Comment by glouel** [comment]
@esetnik I made a small patch to stop redownloading the tar file at every opportunity, following our discussion. I think it's a good first step towards better manifest loading but there's a lot to be improved.

**Comment by glouel** [comment]
Closing as fixed in release 1.4
