### ISSUE TITLE
Display Day or Night based on Desktop DarkMode setting

### ISSUE THREAD

**Issue by aaroncrespo** [JohnCoates/Aerial#516]
Probably less of a priority feature request than the Time based issues.

**Comment by glouel** [comment]
With tvOS12 (if you use the 1.4 beta), Apple no longer provides the day/night distinction, which is why we had to remove that information from the list on the left of the configuration sheet. 

We're looking into adding that back at some point but until we have that, we can't do much more about either time or Dark Mode (which is a nice idea).

**Comment by glouel** [comment]
Please try this build for both Dark Mode and by time day/night support : 
https://github.com/glouel/Aerial/releases/download/1.4beta10/Aerial.saver.zip

**Comment by glouel** [comment]
Closing as fixed in release 1.4
