### ISSUE TITLE
HEVC Main10 Enhanced Support Detection

### ISSUE THREAD

**Issue by esetnik** [JohnCoates/Aerial#522]
https://github.com/JohnCoates/Aerial/pull/521#issuecomment-427419327
> I added "may" as the detection state is uncertain right now, per discussion on a couple of threads. The API only allows to test for HEVC, not specifically HEVC Main10 profile (so it answers yes on my iMac despite not being supported). I can make it green again if you think that's better, but leaving the may (I think the extra description I gave should be enough warning)

We could consider implementing a HEVC Main10 hardware whitelist and fallback to "may" since it seems that we don't have a good way to determine the support level programmatically.

Alternatively, maybe we can implement a heuristic to predict support. E.g. play one of the cached videos for 30s and monitor CPU usage of the VTDecoderXPCService. The difference between partial and full Main10 support is significant. I get 1.4% CPU during 4k HEVC Main10 playback on my 2018 MBP.

**Comment by esetnik** [comment]
Part of the motivation for this is to launch Aerial with a sensible set of defaults for the system. A large majority of issues filed on the project are related to playback performance problems due to missing hardware support.

**Comment by glouel** [comment]
I think hardware whitelist is probably the best we can do right now, as things are unpredictible otherwise. 

Linking to a couple of posts recapping what we know on GVA, I think there's a private API to check if the presented asset will be hw accelerated or not, but quite didn't find it ! 

This comment and below recap a lot of what we know so far : https://github.com/JohnCoates/Aerial/issues/512#issuecomment-426052836

This one https://github.com/JohnCoates/Aerial/issues/503#issuecomment-426356557 seem to show that on 2016 Macbook Pros, with Skylake (no HEVC Main10 support) and Polaris 11 (should support Main10 !), it defaults to Skylake. There's an API it seems to switch the hwdecoding GPU too (linked in one of these), would need some testing.

**Comment by esetnik** [comment]
HEVC Main10 causes major performance issues on all hardware without full support so I think we should default Aerial to 1080p H.264 (or maybe 1080p HEVC) on any device which fails the whitelist.

**Comment by glouel** [comment]
Agreed 👍 
Right now we default to 1080p H.264 for everyone which is the safest thing to do.

**Comment by NightRaider73** [comment]
Is this ready to be closed? @glouel

**Comment by glouel** [comment]
Nope still working on this.

**Comment by glouel** [comment]
Will post a test version later with this, got a pretty good detection mechanism in place now.

**Comment by glouel** [comment]
Closing this with 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta1/Aerial.saver.zip
