### ISSUE TITLE
1.4 & 1.4.1 "Space" descriptions

### ISSUE THREAD

**Issue by benjaminbogdanovic** [JohnCoates/Aerial#545]
Starting with the betas of 1.4, the description on the space videos just says "Space". I have removed the screensaver, and the cache, the reinstalled, but still have the issue. I also have the issue on another Mac.

**Comment by glouel** [comment]
You mean on the list on the left ? Can you post a screenshot of what you see ? It says space > space ?? 

Also, macOS version ?

Here's what I have here FYI on 2 macs (10.13.6 and 10.14.1beta):
 
![capture d ecran 2018-10-16 a 20 46 29](https://user-images.githubusercontent.com/37544189/47039653-b9eceb00-d184-11e8-8c65-b7a7279b03be.png)

**Comment by benjaminbogdanovic** [comment]
The list is okay, it is the deception when viewing the screensaver.

MacOS 10.14

<img width="780" alt="screenshot 2018-10-16 at 19 56 31" src="https://user-images.githubusercontent.com/16837687/47040214-a38f6100-d17d-11e8-99e3-cfdc4d162c06.png">

<img width="1280" alt="lwscreenshot 2018-10-16 at 19 58 56" src="https://user-images.githubusercontent.com/16837687/47040357-f832dc00-d17d-11e8-9d07-4ee500e61f18.png">

**Comment by glouel** [comment]
Thanks for your quick reply. In the Text panel, do you have the "Display in preferred language when available" selected ? If so, what does the line just below says ?

Also, just to confirm, you don't see this in other videos ?

Thanks for reporting this, I'll have a look.

**Comment by benjaminbogdanovic** [comment]
No, it’s not checked. I have tried it with it checked, and I have the same issue. The line underneath says preferred language: English (United Kingdom).

On the other videos I’m only getting the city names, not the detailed descriptions that are visible in the sidebar.

Something to note; in the cached folder, there are only videos. There used to be JSON files and the like, with metadata about the videos. Have you moved these?

**Comment by glouel** [comment]
Ha that explains it ! I definitely haven't and they definitely should be there. Did you perhaps change the cache folder to another place ?

FYI, the extra strings are contained in the  ~/Library/Caches/Aerial/TVIdleScreenStrings.bundle file

So since you don't have those, it fallbacks to the short name. 

You still see Aerial working because the JSONs are saved in the preference files (something that remains of the old original version) and I use that if available and don't try to redownload the files. In your specific case though that's an issue.

Easy fix, delete ~/Library/Preferences/ByHost/com.JohnCoates.Aerial.(UUID).plist

This will reset all settings and redownload/reprocess the JSONs and gives you back the descriptions. You'll also see extended descriptions in the "old" videos like London as a bonus !

I'll try to add a better mechanism to redownload the .tar/jsons in the next version, sorry about that again !

**Comment by benjaminbogdanovic** [comment]
I did not move the cache folder. The issue must have arisen when I cleared the cache and removed the screensaver via the finder, but not the plist, before installing the first release you made.

I have done why you have suggested, and it has fixed it! Thanks!

I guess most people will not have this issue. I only cleared out the cache manually to remover excess videos from before, because it did not work through the screensaver preferences.

**Comment by glouel** [comment]
Makes sense, by removing the cache the files were gone but not the plist. 

While unusual, still better to have a fix in a upcoming release. Thanks for your report on this !

**Comment by benjaminbogdanovic** [comment]
Also the flaw in removing screensavers on a Mac, I does not remove the associated files.

You're welcome!

**Comment by NightRaider73** [comment]
where are the other files?

**Comment by glouel** [comment]
I'm not sure we can cleanup anything at uninstall, I'll have a look !

**Comment by benjaminbogdanovic** [comment]
The error pane will be useful!

Do you have to remove the old version before installing a new version?

I understand when you are updating to a new versions, maintaining the plist is useful to ensure the settings stay them, but for people who want to fully remove it, an uninstall option may be nice.

On a related note; is it possible to have an update feature from the preferences pane?

**Comment by glouel** [comment]
> Do you have to remove the old version before installing a new version?

You don't, but you probably need to restart the System Preferences (close and reopen) in order to properly reload the plist (ironically !) and the ressources (you may see the wrong version show up and an unresponsive UI). As far as we know, that's a bug with the way Swift plugins are loaded. 

It fixes itself the next time you launch System Preferences and we have no workaround so far. I'll try to make a sample project and submit a radar to Apple when I have a sec. 

> I understand when you are updating to a new versions, maintaining the plist is useful to ensure the settings stay them, but for people who want to fully remove it, an uninstall option may be nice.

The thing is, Aerial is not a standalone app, it's a "plugin" for System Preferences. So the install/uninstall mechanism is a bit more restricted. That's why when you double click the .saver, it starts System Preferences who then asks you if you want to install/replace existing version. 

> On a related note; is it possible to have an update feature from the preferences pane?

Same thing as above, we can't really do that for the same reason. We can probably do a new version check (and probably download the new version), but won't be able to install. I'm thinking about adding the version check in the new error pane and point people to the new version. 

As of today, the supported mechanism for auto update is brew cask. It may lag a bit though (by a few hours usually). They seem to have a few issues right now with their integration server but hopefully 1.4.1 will be there ASAP, we have the pull request ready : https://github.com/Homebrew/homebrew-cask/pull/53694

**Comment by glouel** [comment]
> That makes sense. Maybe some instructions would suffice?

We do have that !
https://github.com/JohnCoates/Aerial/blob/master/Readme.md#uninstallation

I've updated it with the location of the plist. 

> A notification that there is a new version would be good. VirtualBox for example directs users to a website to download the latest version, which I find bizarre for a company as large as Oracle can not have a proper updater for a standalone app! Adobe does the same with the Flash updater in the System Preferences pane, but that is pretty much dead.
> 
> That lag would not be noticeable for most users to be fair.
> 
> I use coderelease.io to tell me about your releases.

Marking as an enhancement for a future version.

**Comment by glouel** [comment]
> Still not working for me. The files are not there for me. Where else could they be?

You have the same issue of the titles not showing, that's right ? 

First, go to the Cache panel, click "Show in Finder", that will open your current cache. This is where the missing files should go. 

Or are you looking for the plist to delete it ? 

`/Users/YOURUSERNAME/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist`

Where YOURUSERNAME is your user name, and {UUID} is a series of numbers/letters. 

Another place to look at, maybe, `/Library/Preferences` although I'm not sure it would go there. Maybe if you installed the screensaver for all users, although I'd think every users would have it's own plist.

**Comment by NightRaider73** [comment]
I already tried both places. weird

**Comment by glouel** [comment]
Well, here's a workaround, download : https://sylvan.apple.com/Aerials/resources.tar

Put that file in the cache folder (look the Show in Finder button in my previous comment). Then untar the file and keep the tar too. If you need help untaring let me know.

**Comment by NightRaider73** [comment]
thx

**Comment by NightRaider73** [comment]
Put both in?  Or just one?

**Comment by glouel** [comment]
Put the tar and untar in place. 

You just need the `TVIdleScreenStrings.bundle` to solve the issue in practice. That file needs to be in the cache folder.

**Comment by NightRaider73** [comment]
I did it and it still isn't working it this right:
![screen shot 2018-10-16 at 2 55 17 pm](https://user-images.githubusercontent.com/44180668/47049945-8e054180-d153-11e8-95b3-8cab767429d6.png)

**Comment by glouel** [comment]
nearly there. move the files from the resources folder in the main cache directory (copy them one level down if you see what I mean ?).

**Comment by NightRaider73** [comment]
Thank you so much it is working for me now!

**Comment by glouel** [comment]
You're welcome :)

**Comment by glouel** [comment]
> Maybe put that guide in to the readme doc.
> I mean troubleshooting

Good idea, done  : https://github.com/JohnCoates/Aerial/blob/master/Readme.md#troubleshooting

**Comment by glouel** [comment]
Closing as fixed in 1.4.2beta1 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.2beta1
