### ISSUE TITLE
"You cannot use the Aerial screen saver with this version of macOS."

### ISSUE THREAD

**Issue by dennisN75** [JohnCoates/Aerial#567]
I got still the same problem with the error message.
I use Mac OS 10.3.3 and can see in the preview the error message.

I tried different versions, also the newest beta 4.

What can I do?

**Comment by glouel** [comment]
@dennisN75 Per the [troubleshooting section](
https://github.com/JohnCoates/Aerial#troubleshooting), this is a bug in your macOS version, there's a workaround though: 

> "You cannot use the Aerial screen saver with this version of macOS." error: Select Aerial, close System Preferences with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screensavers in macOS/OS X reported to Apple as rdar://25569037.

This was fixed by Apple in later 10.3.X releases.

**Comment by dennisN75** [comment]
I saw this workaround but it doesn't work.

**Comment by dennisN75** [comment]
And i had a typo in mac version. Of course i have 10.13.3

**Comment by glouel** [comment]
Yeah I figured it was 10.*13*.3. 

I'd highly suggest you update to .4 or .6, it's a macOS bug with Swift screensavers, nothing we can do about that one. There were many issues at the time of their release, it looks like it started getting fixed in 10.13.4. It's definitely fixed in 10.13.6. This also happened on Mojave beta (thankfully fixed there too). 

See this issue here for example : https://github.com/JohnCoates/Aerial/issues/377

**Comment by dennisN75** [comment]
Ok thank. Then i will update.

**Comment by glouel** [comment]
Try enabling the clock first, but yes you should defintely consider updating.

**Comment by dennisN75** [comment]
enabling clock doesn't work.

**Comment by glouel** [comment]
Closing this, please reopen if you still have an issue.
