### ISSUE TITLE
Two feature requests

### ISSUE THREAD

**Issue by PencilNotPen** [JohnCoates/Aerial#611]
1) Ability to play 4K HEVC (both streamed and cached) only when connected to power/charging. Perfect for pre-hardware-HEVC models who want 4K screensavers (Retina display is more than 1080p) when they're charging, but don't want their laptop to die from 4K decoding when running on battery power. With this setting, Aerial would cycle through all screensavers, both 4K and 1080p, when charging, but cycle only through 1080p screensavers when running on battery. (Whilst still respecting other preferences re: cached, streamed etc).

2) Ability to select more than one option under "Time", when possible/appropriate. Obviously "Manual" and "Night Shift" are not possible together, but "Night Shift" and "Dark Mode" should be selectable at the same time. This way, I will see night screensavers once Night Shift is activated, but ALSO if I manually turn on Dark Mode for any reason, will also see night screensavers even before Night Shift times. In fact, every "Time" option should be selectable at the same time as "Dark Mode", but not with each other.

Thanks!

**Comment by glouel** [comment]
Hi @PencilNotPen 

- Add the ability to have a separate video format on battery : Should be doable, I'll look into it for 1.4.5.

- Have dark mode independent of time calculations/override : I'm unsure of how to implement that UI wise. I agree that dark mode is a bit different than the other time modes and could be cumulated, but it was quite convenient to put everything at the same level !

Maybe some checkbox like "Always show night videos on dark mode" at the bottom of the pane, with some introductory text. Maybe @SeanMSmith would have an idea of how to phrase that ?

**Comment by glouel** [comment]
@PencilNotPen check 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta2/Aerial.saver.zip

I also added a power saving mode (fully dim brightness + black screen) on battery/low battery.

**Comment by esetnik** [comment]
It'd also be nice to fallback to still images which fade on battery. I think it'd be a good option to provide for people that don't want to consume any extra power while on battery. I actually turned off Aerial on my laptop because it was killing my battery whenever I left it open. We could probably render out a few stills from each video after they are cached and then use those cached stills as an optional fallback while on battery.

**Comment by glouel** [comment]
This could be a nice feature indeed as an intermediate between 1080pH264 and Power Saving. 

If you want to implement it, be careful though as AerialView is pretty tricky when it comes to handling previews, lifecycles and multiple monitors. Took me a while to get it bug free. It not we can add that to the nice to have project board.

**Comment by dVIAN13** [comment]
I like fade in/out of images... 

maybe have a 'default image' for each video, and have it run for the length of the video... but not a must have. obviously not going to fit everyone's need, but not just black... on the board it goes!

a 'bug' is the tooltip when hovering over the '?' where power saving is.. it has the same value as the video quality one.

**Comment by glouel** [comment]
> a 'bug' is the tooltip when hovering over the '?' where power saving is.. it has the same value as the video quality one.

Oops my bad, I copied/pasted it, will look :)

> also, beta3 is looking good! what did you settle on for the 'fix' for <10.14?

You can see in image here : https://github.com/JohnCoates/Aerial/issues/606#issuecomment-435003114

Had a revelation under the shower, that while our window couldn't get focus any way I tried, maybe opening a new one would do the trick. And it did :) So on high sierra there will be "..." buttons next to textfields (or a big button as in screenshot for location) that open small panels to do the edits.  

> I like the idea of fade in/out of images...
> 
> maybe have a 'default image' for each video, and have it run for the length of the video... but not a must have. obviously not going to fit everyone's need, but not just black... on the board it goes!

Yeah it could be cool. I think that since we have timecodes for text, we could, for each video, get a screenshot at each poi time. Then we can fade those images for X seconds with the text description !

Totally randomly would do the trick I guess and avoid repetitiveness.

**Comment by SeanMSmith** [comment]
> Maybe some checkbox like "Always show night videos on dark mode" at the bottom of the pane, with some introductory text. Maybe @SeanMSmith would have an idea of how to phrase that ?

"Show only night videos on Dark Mode" would be better than "Always show night videos on dark mode".

However (perhaps since I'm not yet on Mojave), I'm not sure I understand the interaction between this check box and the Light Mode/Dark Mode radio button. I presume the check box is for folks who have some other radio button selected (.e.g. "Calculate from" with Civil dawn/dusk) but who may then manually turn on Dark Mode during the day, yes?

But then what about users who may to choose to manually turn _off_ Dark Mode at night? Shouldn't this check box then force Aerial to show only day videos? In that case, perhaps the wording should be something like "When manually turning Dark Mode off or on, show only corresponding day or night videos".

**Comment by glouel** [comment]
> "Show only night videos on Dark Mode" would be better than "Always show night videos on dark mode".

Ok sounds good !

> However (perhaps since I'm not yet on Mojave), I'm not sure I understand the interaction between this check box and the Light Mode/Dark Mode radio button. I presume the check box is for folks who have some other radio button selected (.e.g. "Calculate from" with Civil dawn/dusk) but who may then manually turn on Dark Mode during the day, yes?

Yes exactly. I think that the checkbox should be greyed out if you pick light/dark mode in the radio above, to make things simpler.

> But then what about users who may to choose to manually turn _off_ Dark Mode at night? Shouldn't this check box then force Aerial to show only day videos? In that case, perhaps the wording should be something like "When manually turning Dark Mode off or on, show only corresponding day or night videos".

Just to clarify, macOS doesn't have any option to automatically switch to dark mode, even with night shift, by itself. So it's always manual. 

The idea was to override and force night (thus darker videos) if dark mode even on day. I think the opposite is less of an issue and would get really confusing with the normal light/dark option ?

**Comment by SeanMSmith** [comment]
I think I understand now. (So many choices!)

Greying out the checkbox when the Light Mode/Dark Mode radio button is selected is an excellent idea.

**Comment by glouel** [comment]
Yeah I think we're close to "featuritis" as I keep adding more stuff, will need to get more selective in the future but I thought those two made sense ;) 

Especially the first one which I hadn't thought of (I had thought of the Power Saving thing so I merged the two).

**Comment by PencilNotPen** [comment]
Sorry for not replying before, and thanks for taking the suggestions on board. Yes, I believe "Show only night videos on Dark Mode" should represented in UI by a check box, not a radio button (is that the name of that?). It should be tickable in addition to any one radio button, including "Do not adapt videos based on time", with the exception of "Light Mode/Dark Mode".

When ticked, and if Dark Mode is manually activated (the only way to activate it), only dark videos should be shown.

When ticked, and if Dark Mode is not activated, videos should be shown based on fallback to radio button. I do not think it should force day videos in this scenario.

When unticked, videos should be shown based on fallback to radio button regardless of Dark Mode status.

As far as the power saving feature goes, I'm not fussed about the rendering out of stills and fades, as the point of the Aerial screensavers to me is the movement, and the preference panes are becoming extremely full. A simple check box for "Only show 1080p when on battery power" would be enough. The opposite scenario does not need an option "Only show x when on mains power", because it can already be controlled by manually selecting screensavers, or using "Check only 4K".

Where can I grab the latest beta to try out? Thanks again guys!

**Comment by glouel** [comment]
You'll see the checkbox work as you expect then ;) 

Latest beta here, 1.4.5 beta 4 : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta4/Aerial.saver.zip

In general, latest releases you can bookmark this : https://github.com/JohnCoates/Aerial/releases

**Comment by PencilNotPen** [comment]
Hi! Thanks, I've got it running now. The "Always show night videos on dark mode" check box does not seem to persist between quits of System Preferences. Quitting and reopening System Preferences seems to always show it unticked again.

I also suggest that the wording be changed to more natural English:

"Always show night videos on dark mode"

Should be:

"Always show night videos in Dark Mode"

**Comment by SeanMSmith** [comment]
@PencilNotPen, you're quite right that "…in Dark Mode" would be more natural than "…on Dark Mode"!

"Always show night videos…" is ambiguous, however, since it doesn't explicitly exclude the possibility of _also_ showing day videos. (I.e., it could be taken to mean, "When Night Mode is off, we'll only show day videos, but when Night Mode is on, we'll always show night videos also.")

"Show only night videos in Dark Mode" is unambiguous, and more natural than the "Show only night videos _on_ Dark Mode" that I carelessly suggested earlier.  :)

**Comment by PencilNotPen** [comment]
Yep, I agree! Capitalise Dark Mode, change on to in, and change Always to Only.

**Comment by glouel** [comment]
Damn thanks for the bug indeed the preference wasn't properly restored, will be fixed in next version, probably tomorrow if I have a sec (and will update text accordingly to conversation, thanks both ;) )

**Comment by glouel** [comment]
1.4.5 is out with those changes
