### ISSUE TITLE
I have the latest version of Mojave and when dropping the Aerial Savers file into my screensaver folder I receive an error message. It says I cannot use Aerial with this version of OS. I know that was reported before and resolved but could you take another look. 

### ISSUE THREAD

**Issue by nnichols14** [JohnCoates/Aerial#612]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
@nnichols14  Which folder ? And when do you see the message ?

Did you try this as written in the troubleshooting section : 

> "You cannot use the Aerial screen saver with this version of macOS." error: Select Aerial, close System Preferences with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screensavers in macOS/OS X reported to Apple as rdar://25569037.

**Comment by diba320** [comment]
Same for me, troubleshooting no solution. Last version of OSMojave

**Comment by glouel** [comment]
Did you try this with latest version ? @diba320 

"You cannot use the Aerial screen saver with this version of macOS." error: Select Aerial, close System Preferences with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screensavers in macOS/OS X reported to Apple as rdar://25569037.

This works on Mojave.

**Comment by glouel** [comment]
@diba320 Please try to provide the following information so I can help you figure this out :

- Can you clarify that you see this error instead of the preview video in this screenshot ? Or do you see it somewhere else ? 

![screen shot 2018-10-29 at 13 17 23](https://user-images.githubusercontent.com/37544189/47649971-1f76a980-db7f-11e8-97be-d1f90b943c9d.png)

This is where you should select Aerial on the left, close and reopen this pane. Correct ?
- Was this your first install of Aerial or not ? 
- If not, did you uninstall all previous versions ?
- Which method of install did you use (zip, or brew, did you install for your user, or all users) ? 
- The icon you clicked in System Preferences > Screen saver on the left pane, was it a picture of San Francisco or the Earth ?

Off the top of my head, I'd recommend you check your `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers` to make sure you don't have an old version around. This can happen if you switch from one method to another (zip to brew etc, as you may not make the same choice that brew makes).

**Comment by diba320** [comment]
Great support!

I see even in the preview pane the error message with black background. The „Aerial“ icon has no preview look as well.
I installed the unzipped file in the respective folder, all users.



Mit freundlichem Gruß

Dietmar Barro

**Comment by glouel** [comment]
@diba320 
Can you try this : 
- close System Preferences
- uninstall from /Library/Screen Savers (just remove the Aerial.saver file, if it's not there, look in your user folder, see my previous message)
- instead of copying, unzip in your download folder, and double click Aerial.saver

This will open System Preferences, which will ask if you want to install for you or all users. Please try your user only this time. System Preferences will install Aerial for you in the correct place and open the window I showed above. On that one, select Aerial, and if you see the error message, then close system preference with Aerial selected and reopen it. This should work for you. 

Either installing for all is an issue now, or manually copying the file is (could be some permission issue too). Could be some change in 10.14.1 that I didn't see, also. Double clicking should work, if it does I'll update the instructions.

**Comment by diba320** [comment]
Double click gives me an error message, the aerial file is damaged cancel or move to basket … with 1.4.4 and beta

Mit freundlichem Gruß

Dietmar Barro

**Comment by diba320** [comment]
Solved, … obviously a unzip problem with „archive browser“. Unzipped with WinZip and everything went smoothly.
THX again for the quick replies.
Mit freundlichem Gruß

Dietmar Barro

**Comment by diba320** [comment]
Used safari, but use "archive browser" as standard for unzipping.

**Comment by glouel** [comment]
Thanks for your feedback. I guess you disabled "Open safe files" in Safari Preferences then. The unarchiver is a pretty good free alternative too. 

I updated the install instructions based on your experience, so people are aware of this : 
https://github.com/JohnCoates/Aerial#manual-installation
