### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#637]
![screen shot 2018-11-10 at 11 23 30 am](https://user-images.githubusercontent.com/44180668/48305227-bfb3c300-e4db-11e8-8e53-d5a9f54b3385.png)

Is "Power Saving" a mode?  If so I suggest Capitalizing the "saving" to be consistent

[Debug Mode Sticking.zip](https://github.com/JohnCoates/Aerial/files/2568685/Debug.Mode.Sticking.zip)

With this screen recording after the "debug mode" is selected and unselected the "Show Debug" is still sticking. 
@glouel I don't know if this is intended but just didn't know if you noticed it:)

**Comment by glouel** [comment]
Popups and buttons are All Word Caps and labels are not in macOS rules, that's why it's that way.

As for the debug thing, it's working as intended. If you uncheck debug mode it will stop logging from then on, but the logs generated prior to this are still displayed, and so will be warning and errors (you can generate a warning by unchecking every video for example, you'll see a show warning button instead). The button name reflects the highest level of log that was collected until then.

**Comment by NightRaider73** [comment]
Okay
