### ISSUE TITLE
Scrollbar UI Issue and Tooltip Suggestion

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#642]
@glouel Thanks again for all of your continued work on this project.

I wanted to formally post this, to help you better track the scrollbar issue. :)
1) As discussed previously, the scroll bar when dragged with cursor, overlaps some of the UI tags.

2) To further expand on a comment posted earlier, would it be possible to have the 'total downloaded'  pie-shaped UI element's Tooltip display the progress in a total percentage complete or a x of x downloaded, format? I'm thinking total percentage complete would just be the simple percentage of total number complete out of total number selected to download.(I know you mentioned you don't get percentage of individual files). that's just a suggestion, and I was just wanting your opinion on whether it'd be useful to have it there. The current, visual, representation is good with me.

**Comment by glouel** [comment]
Hey @dVIAN13 !

So yeah good idea cause I kinda had forgotten 1)! To recap:

- About 1), yeah, because of localization, I may need to make the list larger anyway, so I'll fix that one at the same time.
- Tooltip showing "x/y videos downloaded", yeah, that should be possible and not that hard indeed and should be more helpful. 

Extra NTH : I could *probably* do a %age for the current downloaded item (so let's say 3 items total in queue, 1 done, 2 to go, queue is 1 at a time [that could be changed although I'm reluctant about it... the jsons download 3 at a time for example ;)], the progress would move from 1/3 to 2/3 as the second item gets downloaded. This doesn't take total file size into account but would be better than it is right now. Still a bit messy code wise so will have to think about it. Marked for next release !

And thanks a lot to you, I have to say that you managed to keep my spirits up the other day ;) Take care!

**Comment by glouel** [comment]
@dVIAN13 so been a while but I finally got to fix this with beta 3 : 

- realigned the 4K indicator for the scrollbar
- the "individual" download indicator is now round to free more space for video names
- the "global" download indicator (bottom left of window) now has a tooltip
- the "global" download indicator now shows the live progress

https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta3/Aerial.saver.zip

**Comment by dVIAN13** [comment]
@glouel thank you! I’ll check it out when I’m back in town. Great work!

**Comment by glouel** [comment]
Thanks ! Here's the screenshot I forgot to post (with in progress french translation)😅:

![capture d ecran 2018-11-15 a 18 53 57](https://user-images.githubusercontent.com/37544189/48574155-b88f1980-e90e-11e8-85e6-e768471fbf10.png)

**Comment by dVIAN13** [comment]
@glouel I was able to install today, and it looks great! thanks for all of those improvements! I am wondering how hard it would be(or useful for that matter) for the videos's download order to be modified? currently it is in alphabetical order, however, it would be nice(not a requirement), to have it start at the top, and work it's way down... ;) thoughts?

**Comment by glouel** [comment]
Hmm, I thought that's how it worked already 😅

I'll have to check but yeah top to bottom was my initial intent, I may have broken it with the secondary name thing, will have a look.

**Comment by dVIAN13** [comment]
@glouel hahahaha.. no worries! I think you're right.. it was different behavior originally.. but to confirm, it's actually downloading them alphabetically based on the 'name' of the video.. so it jumps all over.. :) and would change based on the language! haha. thanks for looking into it!

**Comment by glouel** [comment]
That makes sense should be an easy fix 🙈

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta4/Aerial.saver.zip

**Comment by dVIAN13** [comment]
confirmed! thanks @glouel !!!
