### ISSUE TITLE
Text getting cut off on 10.9

### ISSUE THREAD

**Issue by avenged110** [JohnCoates/Aerial#684]
#### Required information
- Mac model: MacBookPro11,3
- macOS version: 10.9.5 13F1911
- Monitor setup: Built-in display

#### Description of issue
There are a number of areas where the text is cut off when using OS X 10.9, as shown in the screenshots. This is an issue that seems to show up a lot on 10.9 using newer software. There's also a couple of tiny, random things like "1 minutes," a missing colon, and some alignment issues.

![1](https://user-images.githubusercontent.com/19438529/49704689-f6f4bd00-fbca-11e8-9796-ac5f48d5a4b4.png)
![2](https://user-images.githubusercontent.com/19438529/49704692-f6f4bd00-fbca-11e8-818c-2d80ed54452d.png)
![3](https://user-images.githubusercontent.com/19438529/49704690-f6f4bd00-fbca-11e8-9549-94b5d38f30f6.png)
![4](https://user-images.githubusercontent.com/19438529/49704691-f6f4bd00-fbca-11e8-9805-b0b9054697a3.png)
![5](https://user-images.githubusercontent.com/19438529/49704688-f6f4bd00-fbca-11e8-8ddd-e5a82d67aef1.png)
![6](https://user-images.githubusercontent.com/19438529/49704687-f6f4bd00-fbca-11e8-8fb5-37d656d67cd4.png)

**Comment by glouel** [comment]
> #### Required information
> * Mac model: MacBookPro11,3
> * macOS version: 10.9.5 13F1911
> * Monitor setup: Built-in display
> 
> #### Description of issue
> There are a number of areas where the text is cut off when using OS X 10.9, as shown in the screenshots. This is an issue that seems to show up a lot on 10.9 using newer software. There's also a couple of tiny, random things like "1 minutes," a missing colon, and some alignment issues.

Hey, thanks for your report. It indeed looks horrible on 10.9 as your screenshots show, sorry about that.

There are multiple types of issues, I'll try to sum them up:
- Cut text in labels: if I remember correctly, pre 10.11, macOS used to use Lucida Grande before switching to Helvetica Neue. Looks like it was slightly wider and things get cut. The text label width is calculated automatically by Xcode, and it looks like in newer versions of Xcode they just calculate that based on current system font and that breaks on older systems, which is why you probably see that on a lot of new software. 

I've made a test build below with larger labels and we'll see if it helps, although it's going to be a pain to get stuff correctly aligned in the future so I can't guarantee it will get permanently fixed.

- Vertical alignment on non retina: a bit of the same thing, things are slightly off by a pixel on non retina screen (the text of the popups is misaligned with the labels next to them), I have noticed that on 10.13 on my Macbook Air too but I've found no way to workaround that. If I align correctly for retina, it just looks off on non retina. That's also the issue you see with the + button and not much I can do right now for that. 

- Underlined macOS versions, not sure what you wanted to highlight here ?

- 1 minutes : that's a bug for everyone ;) I'll try to add a fix to that

- Text overlaying checkboxes on the video list : can you click those or are they unclickable? Again, hard to know why this happens so unsure how to fix that. 

There are other things that silently break on old macOS versions too such as the clock not working I think, and probably a couple others. I didn't want to remove support for the old versions but newer Xcode versions makes it quite hard to keep supporting them...

In the meantime, give that build a try, it should fix most of the labels (1st issue) : 
https://github.com/glouel/Aerial/releases/download/v1.4.6test7/Aerial.saver.zip

**Comment by avenged110** [comment]
I am very appreciative that you still support 10.9. I can live with there being some issues in exchange for that, I mostly just wanted to make sure you were aware in case there was something you could do (such as with the labels). The test build appears to have fixed those issues, by the way, so that's awesome.

The underlined macOS versions weren't really an issue, just inconsistent. One includes the name (Mojave) as well as the version number, the other doesn't. Personally, I would assume the version number would do, but that's just a small peeve of mine and doesn't really matter.

For the checkboxes, if I click the box, it realigns properly, but leaves the box unchecked. If I click it again, it checks it and returns to the incorrect alignment. At this point, that box becomes unresponsive, with the only way to uncheck it being to use the "Uncheck All" toggle or restarting Sys Prefs. This holds true for each box, respectively.

Thank you for the help. It's always nice to find legacy support for cool features.

![screen shot 2018-12-10 at 8 36 42 pm](https://user-images.githubusercontent.com/19438529/49778802-d0627f00-fcbb-11e8-8b5b-f864386df4c8.png)
![screen shot 2018-12-10 at 8 36 52 pm](https://user-images.githubusercontent.com/19438529/49778807-d48e9c80-fcbb-11e8-8298-41d77608298c.png)

**Comment by glouel** [comment]
> I am very appreciative that you still support 10.9. I can live with there being some issues in exchange for that, I mostly just wanted to make sure you were aware in case there was something you could do (such as with the labels). The test build appears to have fixed those issues, by the way, so that's awesome.

Cool ! 
 
> The underlined macOS versions weren't really an issue, just inconsistent. One includes the name (Mojave) as well as the version number, the other doesn't. Personally, I would assume the version number would do, but that's just a small peeve of mine and doesn't really matter.

True, I should probably fix that too thanks.

> For the checkboxes, if I click the box, it realigns properly, but leaves the box unchecked. If I click it again, it checks it and returns to the incorrect alignment. At this point, that box becomes unresponsive, with the only way to uncheck it being to use the "Uncheck All" toggle or restarting Sys Prefs. This holds true for each box, respectively.

That's wild. No guarantee but I'll try to see if I can think of a workaround. If not you'll have to use the menu below instead.

> Thank you for the help. It's always nice to find legacy support for cool features.

Np!

**Comment by glouel** [comment]
I'll be closing this, please feel free to let me know in the future if something else breaks !
