### ISSUE TITLE
System Preferences crash

### ISSUE THREAD

**Issue by SimmPe** [JohnCoates/Aerial#694]
@JohnCoates 
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (15 Zoll, 2016)
- [ ] macOS version: 10.14.2 (18C54)
- [ ] Monitor setup: Integrierter Bildschirm 15,4-Zoll (2880 x 1800) + Display: HP S340c 34-Zoll (3440 x 1440) | Grafikkarte: Radeon Pro 455 2048 MB

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I can see the menu for some seconds but then it disappears...
This is the error is was able to copy to the clipboard from the Error button on the lower left side of the menu.

21:40:34 : Location services may be disabled, Night Shift can't detect Sunrise and Sunset times without them
21:40:36 : Error Domain=NSCocoaErrorDomain Code=4 "„CFNetworkDownload_LGBNjJ.tmp“ konnte nicht nach „Aerial“ bewegt werden, da letzteres Objekt nicht existiert oder der Ordner mit dem letzten Objekt nicht existiert." UserInfo={NSSourceFilePathErrorKey=/var/folders/fh/7frkm8p151bf04bwgnlw4rqm0000gp/T/CFNetworkDownload_LGBNjJ.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/_SimmPe_/Movies/Aerial/tvos10.json, NSFilePath=/var/folders/fh/7frkm8p151bf04bwgnlw4rqm0000gp/T/CFNetworkDownload_LGBNjJ.tmp, NSUnderlyingError=0x6000012630f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
21:40:40 : Error Domain=NSCocoaErrorDomain Code=4 "„CFNetworkDownload_gvlBx6.tmp“ konnte nicht nach „Aerial“ bewegt werden, da letzteres Objekt nicht existiert oder der Ordner mit dem letzten Objekt nicht existiert." UserInfo={NSSourceFilePathErrorKey=/var/folders/fh/7frkm8p151bf04bwgnlw4rqm0000gp/T/CFNetworkDownload_gvlBx6.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/_SimmPe_/Movies/Aerial/tvos11.json, NSFilePath=/var/folders/fh/7frkm8p151bf04bwgnlw4rqm0000gp/T/CFNetworkDownload_gvlBx6.tmp, NSUnderlyingError=0x600001274f30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

<img width="783" alt="image" src="https://user-images.githubusercontent.com/45951347/50115001-737c4100-0246-11e9-84ef-b99c0f56c337.png">

**Comment by glouel** [comment]
Hi, thanks for your report and sorry about that.

Few questions because you're not giving me much context here...
- was this the first time you installed Aerial ? Did you have a previous version before ?

Something that seems incredibly weird is that path : /Users/SimmPe/Movies/Aerial/tvos11.json
- Did you change the default path for this or not ? And then it failed after that ? 

 By default your Cache path should either be /Users/you/Library/Caches/Aerial or /Library/Caches/Aerial

If somehow you moved the folder to /Users/SimmPe/Movies/Aerial/, does that folder exist or not ? If it does, is the folder read/writable ? 

I would suggest wiping your cache directory AND your preference file (it's in /Users/you/Library/Preferences/ByHost/) to reset to defaults.

**Comment by SimmPe** [comment]
yeah. just restarted system preferences -> et voila: Warning is gone
