### ISSUE TITLE
Screen Saver doesn't run on macOS High Sierra 10.13.1

### ISSUE THREAD

**Issue by char1eslu** [JohnCoates/Aerial#714]
"You cannot use the Aerial screen saver with this version of OS X." message
If you get a message saying You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver. that is a known bug with macOS that was reported to Apple in April 2016 as rdar://25569037. As of November 2017 the bug is still not fixed. To work around the bug:

select the Aerial screensaver in System Preferences
close System Preferences with Aerial selected
reopen System Preferences and the preview should work now

The workaround suggested above doesn't work here anymore ，could you help me?

**Comment by glouel** [comment]
Hi @char1eslu 

This is a bug in some early versions of MacOS, it was fixed in 10.13.4 and is definitely fixed in the latext 10.13.6. You can check this message https://github.com/JohnCoates/Aerial/issues/567#issuecomment-431921805 for more information about it, but as far as I remember, only updating to a later point update (at least .4) was the solution as it wasn't a bug in Aerial as far as we know. 

Hope this helps !
