### ISSUE TITLE
Changing cache location seems to be broken

### ISSUE THREAD

**Issue by bgondy** [JohnCoates/Aerial#719]
I've just installed aerial with `brew cask install aerial` on a fresh install of Mojave.

When I change the cache location, nothing is moved to the new one and when I download all videos, they'r are still stored in the default cache location (`/Library/Caches/Aerial`).

The reason why I need to change cache location is that I use a Micro SD card ([nifty minidrive](https://www.amazon.com/gp/product/B017HOBQAY/)) to free up the internal disk and store cold data and some cache (aerial, spotify, …).

I've tried to create a symlink from my external drive to `/Library/Caches/Aerial/` but I ran into errors and this has no meaning since this is a built-in feature.

Maybe I'm doing something wrong but I've tried to reinstall aerial without success (brew uninstall + removing `/Library/Caches/Aerial` and user prefs as mentioned in project's README.md).

**Comment by glouel** [comment]
Hi @bgondy 

Just to clarify, "Change location" does not move your existing files. It changes the saved location. 

Here's how to make it work : 
- Change the location (the path MUST exist)
- Fully quit Aerial (that means fully closing System Preferences)
- Move your files if you want to (you don't have to)
- Restart Aerial in Sys Pref. 

You should see the new path taken into account and at the very least Aerial will have redownloaded the JSONs at the new location if empty. 

Also, don't do the symlink thing.

With that said, I would strongly recommend against using a device that may be unplugged at any time. Aerial 1.4.6 absolutely needs it's cache folder to be present in order to work and will unceremoniously crash if your Micro SD isn't present. 

The 1.4.7 betas has a much saner fallback mechanism, if your path is no longer available, it will fallback to the default location and use that. Your old path will be lost and you'll have to set it again. 

Hope  this answers your questions.

**Comment by bgondy** [comment]
Thanks for clarifying. I was not closing System Preferences, only screensaver options. It works as expected. Maybe this could be mentioned in the troubleshooting section.

Regarding to the external device, it doesn't aim to be unplugged: paperclip would be required to do it.

**Comment by glouel** [comment]
> Thanks for clarification. I was not closing System Preferences, only screensaver options. It works as expected. Maybe this could be mentioned in the troubleshooting section.

Depending on systems, just closing the options is enough as opening again will start a new instance. Not on other systems.

In any case, I did add a long section about cache location that will hopefully clarifying things for others, thanks for your feedback ! https://github.com/JohnCoates/Aerial/issues/719#issuecomment-462152875
