### ISSUE TITLE
Feature request: User-defined video sets

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#733]
**Feature request: User-defined video sets**

_Summary:_

With the large number of Aerial videos now available (73!), it would be handy to be able to define and choose from custom sets of Aerial videos.

_Details:_

Sometimes I want to see only Nighttime space videos, at others all space videos, or only city videos (but not of Los Angeles freeway traffic!), or only videos of natural landscapes, or at still other times an eclectic mix.

It would be convenient to be able to define and name arbitrary sets of videos, and then to be able to select from the gear menu a set of videos to play.

For myself, this is a **low-priority** feature, but if it could be implemented easily, it would be convenient to have.

Thanks!

**Comment by glouel** [comment]
@SeanMSmith 

I have to admit I was a bit reluctant, it's always the same issue with that kind of features, because videos may "change" with new versions etc, one would have to maintain it's sets when new jsons drop from Apple. But considering we didn't get any new one in nearly 3 months, I got to it yesterday. 

So here's how it look : 
<img width="377" alt="Capture d’écran 2019-04-19 à 14 28 55" src="https://user-images.githubusercontent.com/37544189/56425106-35099800-62b3-11e9-9689-315a34132e21.png">

You can create a new set (save your current playlist), update them (this screenshot), delete, or activate  a set. Let me know what you think. 

https://github.com/JohnCoates/Aerial/releases/tag/v1.4.7beta9

**Comment by glouel** [comment]
Closing this, reopen if needed.

**Comment by SeanMSmith** [comment]
This is excellent.

Thank you very much.
