### ISSUE TITLE
Feature Request: Add "Vertically Opposed" and extra information show duration

### ISSUE THREAD

**Issue by fok** [JohnCoates/Aerial#765]
#### Description of issue / Feature request

Would be great if a "Vertically Opposed" setting would be available for Text/Extra information.
Also a separate show duration for the extra information would be nice.

**Comment by glouel** [comment]
Hi @fok 

Vertically opposed is problematic because one can add a custom string that shows in the same corner of the clock, and we also allow custom font size, and Aerial has to run on all screen size, even the tiny ones. So if you put everything on the same line you have to handle collision between those strings, with potentially no visually good solution to handle them, which is why I didn't add this option. 

I'm not sure about showing video duration, can you clarify what you had in mind ?

**Comment by fok** [comment]
Hi @glouel 

I'm aware that collision might be tricky to handle for vertically opposed. I would just accept that the strings could overlap if they are too long (or the display too small). My resolution is high, I downsized the font to 18pt, and the extra text I want to show is short.
Alternatively collision handling could be made pretty basic: Either just cut both strings at 50% (or something like 40-45 % to keep some distance) of the screen (and mybe wrap text to multiple lines) or don't show the text on the right side of the screen when the one on the left side is too long.

I didn't mean video duration, sorry for the confusion. I meant the duration the text is being shown (eg. 10 seconds). What I would like to do: Show the description of the screen saver for 10 seconds in the bottom left corner, but show my email address always in the bottom right corner, so colleagues in the office know that this is my MacBook. I hope this clarifies?

**Comment by glouel** [comment]
> I'm aware that collision might be tricky to handle for vertically opposed. I would just accept that the strings could overlap if they are too long (or the display too small). My resolution is high, I downsized the font to 18pt, and the extra text I want to show is short.

Understood, but I have to make it work for everyone. 

> Alternatively collision handling could be made pretty basic: Either just cut both strings at 50% (or something like 40-45 % to keep some distance) of the screen (and mybe wrap text to multiple lines) or don't show the text on the right side of the screen when the one on the left side is too long.

I already do wrap multiple lines for descriptions, yes, because of large fonts. To implement correctly, this is a non trivial amount of work as the animation system has many moving parts so I'll give you a maybe if/when I overall the animation system, but you'll have to make do with the current options in the meantime.

> I didn't mean video duration, sorry for the confusion. I meant the duration the text is being shown (eg. 10 seconds). What I would like to do: Show the description of the screen saver for 10 seconds in the bottom left corner, but show my email address always in the bottom right corner, so colleagues in the office know that this is my MacBook. I hope this clarifies?

The goal of the 10 seconds option is to never have anything that always sticks on screen, because screensavers should avoid that for burn-in/marking reasons. If you pick always, extra information will not get animated unless you set random corner mode (in that case we need to, obviously). I suggest you use that if you want your email always on screen right now. 

I'll consider this one for next version, but because of the random corner mode again, this is not a quick implement.

**Comment by glouel** [comment]
Looks like I forgot to close that issue, Aerial now allows fine grained control for each info types in 1.8+
