### ISSUE TITLE
Add option to press escape on keyboard when in preferences

### ISSUE THREAD

**Issue by lorenzolewis** [JohnCoates/Aerial#77]
Just an enhancement. I noticed a lot of screensavers (specifically OS X defaults ones) you can press the esc key to exit the preferences menu. Just something to make it a little more refined and streamlined.

**Comment by geo4orce** [comment]
Just looked thru other [native] settings and noticed that this is normally the case on screens that have buttons **Cancel** and **OK** (e.g. *Network -> Advanced*)

However, Esc doesn't work on screens that only have **Done** button (e.g. *Mission Control -> Hot Corners*).

So maybe the point of this issue is to change the buttons from "Done" to "Cancel/OK"

**Comment by alistairmcmillan** [comment]
This seems like a simple little request. But it requires the PreferencesWindowsController to be almost all rewritten.

The implication of Cancel and OK buttons is that you hit OK and it saves your changes, and you hit Cancel and it forgets your changes. But the way the PreferencesWindowsController is written right now is that any changes are made immediately. Which makes sense.

For example: if it was rewritten to have Cancel and OK button, what should happen if someone has enabled the cache feature, downloaded all the movies and then hits the Cancel button?

**Comment by geo4orce** [comment]
Great point! I say close this ticket. Won't fix. It is perfectly fine now.
