### ISSUE TITLE
Aerial can not find my manual downloaded cache

### ISSUE THREAD

**Issue by xiaochunjimmy** [JohnCoates/Aerial#781]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac 2017 Retina 5K
- [x] macOS version: Mojave 10.14.5
- [x] Monitor setup: iMac 27-inch (5120x2880)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I used a manual location for my cache videos, and I downloaded the videos manually with the links in tvos10.json.
But when I open the preference of Arial, the video list still show `+` icon button rather than `↓`. 
The preview window play videos using Network rather than cached files.
</br>
Here's the screenshot of my cache files.
<img width="657" alt="WX20190518-205134@2x" src="https://user-images.githubusercontent.com/6701827/57970179-e255f580-79b0-11e9-97e8-9cad7d8d53f9.png">
</br>
Here's the screenshot of my Aerial preferences.
![image](https://user-images.githubusercontent.com/6701827/57970204-1fba8300-79b1-11e9-8389-d4a14acf2481.png)
</br>
This is the AerialLog:
20:40:50 : UI logToDisk: true
20:42:11 : <AerialView: 0x7fc4ec61ee80> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000060880, asset = <AVURLAsset: 0x600000060780, URL = streaming://sylvan.apple.com/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov>>), userInfo = nil
21:01:31 : <AerialView: 0x7fc4ec61ee80> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000060880, asset = <AVURLAsset: 0x600000060780, URL = streaming://sylvan.apple.com/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov>>), userInfo = nil
21:03:33 : <AerialView: 0x7fc4ec61ee80> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000060880, asset = <AVURLAsset: 0x600000060780, URL = streaming://sylvan.apple.com/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov>>), userInfo = nil
21:03:38 : <AerialView: 0x7fc4ec61ee80> played did reach end
21:03:38 : <AerialView: 0x7fc4ec61ee80> notification: name = AVPlayerItemDidPlayToEndTimeNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000060880, asset = <AVURLAsset: 0x600000060780, URL = streaming://sylvan.apple.com/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov>>), userInfo = nil
21:03:38 : <AerialView: 0x7fc4ec61ee80> observeValue Optional("readyForDisplay")
21:03:38 : <AerialView: 0x7fc4ec61ee80> Setting player for all player layers in []
21:03:38 : shouldRestrictByDayNight : true (night)
21:03:38 : initvideocache
21:03:38 : <AerialView: 0x7fc4ec61ee80> streaming video (not fully available offline) : https://sylvan.apple.com/Videos/comp_GMT329_113NC_396B_1105_ITALY_v03_SDR_FINAL_20180706_SDR_2K_AVC.mov
21:03:38 : <AerialView: 0x7fc4ec61ee80> observing current item <Aerial.AerialPlayerItem: 0x600000136de0, asset = <AVURLAsset: 0x6000001369a0, URL = streaming://sylvan.apple.com/Videos/comp_GMT329_113NC_396B_1105_ITALY_v03_SDR_FINAL_20180706_SDR_2K_AVC.mov>>
21:03:38 : <AerialView: 0x7fc4ec61ee80> playing next video for player Optional(<AVPlayer: 0x6000002689f0>)
21:03:38 : AssetLoaderDelegate deinit
21:03:39 : Processsing contentInformationRequest
21:03:39 : expected content length: 103228938 type:com.apple.quicktime-movie
21:03:39 : Processsing contentInformationRequest
21:03:39 : expected content length: 103228938 type:com.apple.quicktime-movie
21:03:44 : connectionDidFinishLoading
21:03:45 : <AerialView: 0x7fc4ec61ee80> observeValue Optional("readyForDisplay")
21:03:45 : locale.languageCode en

**Comment by glouel** [comment]
Hi @xiaochunjimmy !

First thanks a lot for the log and all the details you provided. 

So it looks like you only downloaded the videos from tvOS10.json, not from the other two. I would suggest you also get the videos from the `entries.json` first, those are the most recent ones and it will fill the list for you.

By default Aerial uses the most recent videos available, and that means that some of the older ones from the tvOS10.json will get unused, because Apple replaced them with newer versions of those videos (some are color corrected, some are longer/shorter, etc). Aerial can't use those because most of the time they don't align with the text descriptions. But there are some videos in those json that are still used, which is why we download it too. 

If you look at the log, Aerial is looking for this file "comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov" which comes from the tvOS12 json. You do not have this file in your directory.

So grab those from entries.json, and if you want everything, from tvOS11.json too. The files you want from the json are those where the line starts with `"url-1080-H264" : `. Make sure you quit and reopen System Preferences (not just Aerial panel, the full System Preferences window) so that Aerial can pick your newly downloaded videos. 

By downloading all videos manually, you will have duplicates (the old files from tvOS10).  When you are done, you can go to the Advanced tab and use the Trash old videos options on the right. This will delete the duplicate video versions and will let you keep only the videos that you need.

![Capture d’écran 2019-05-18 à 15 34 07](https://user-images.githubusercontent.com/37544189/57970551-bface800-7982-11e9-865c-ed68976d0816.jpg)

Hopefully this makes sense. If you need any more explanation feel free to ask !

**Comment by xiaochunjimmy** [comment]
Than you so much~
I redownloaded videos from the entire.json and Aerial recognized the caches.
</br>
I simplified the JSON file content with download links only so that other users can copy and paste the links directly to download software.
[Aerial-Download-Links-1080p.H264.txt](https://github.com/JohnCoates/Aerial/files/3195335/Aerial-Download-Links-1080p.H264.txt)

**Comment by glouel** [comment]
Glad this fixed it for you !
