### ISSUE TITLE
[feature request] seperate monitor support

### ISSUE THREAD

**Issue by mattleaf** [JohnCoates/Aerial#794]
Apologies for the ticket, I'm confused about the way multi-monitor support works. 

Correct me if I'm wrong - when I choose a seperate display to show Aerial - ie second monitor or Main display, the respective other display goes black. I can wiggle my mouse in front of the black display, but otherwise it's unusable.

Is this expected behaviour? 

My intention is to display aerial on a second monitor but continue working on the main display. 

Is this possible?

I'm guessing because Aerial is a 'screen saver' then the answer is no, but it would be a cool feature. 

I tried rebooting, logging in / out, and various settings. But choosing one over the other seems to render the other display inactive. I don't particularly understand the use case.

**Comment by glouel** [comment]
Hi @mattleaf 

Indeed, that's expected behavior. A screen saver can only run when macOS says so, and stops running when macOS says so (Aerial is not in control of this). So as soon as you move your mouse, macOS will kill the screen saver and bring back the desktop. As far as I know, in macOS you can only put the whole system to sleep and not individual screens.

The use case is for people who don't want to have aerial running on some of their displays (maybe only main screen, or leave main screen to sleep on a laptop and only play on external one, etc). Another example would be they use an external display connected through USB that may not be great at playing videos. See this issue if you want to know more about that use case : https://github.com/JohnCoates/Aerial/issues/732

Note that with the next version of macOS you may be able to use your iPad too as a secondary monitor, this may be helpful there too.

**Comment by mattleaf** [comment]
Appreciate the quick response! 

In any case, I really love Aerial. I grab the files from the cache and throw them on my TV for some home visuals. 

Might as well mention I do have some troubles with audio there, from what I can gather since the files don't have any audio, my TV throws an audio error because it doesn't understand 'no audio' as a supported audio-type. Video still plays, just get a pop-up for every file. I'm basically reMuxing the files with a silent audio file to eliminate the pop-up.

Obviously not your problem, but maybe would help others out there in the wide world if the file came with silent audio. Maybe it adds to the file size and therefore not ideal?

Either way, love the work.

**Comment by glouel** [comment]
> Might as well mention I do have some troubles with audio there, from what I can gather since the files don't have any audio, my TV throws an audio error because it doesn't understand 'no audio' as a supported audio-type. Video still plays, just get a pop-up for every file. I'm basically reMuxing the files with a silent audio file to eliminate the pop-up.
> 
> Obviously not your problem, but maybe would help others out there in the wide world if the file came with silent audio. Maybe it adds to the file size and therefore not ideal?

So the files come from Apple's server this way (they are used on the Apple TV's screensaver), with no sound indeed. This is where we get them as is, as we don't host anything, we can't modify them. Hope that makes sense!

**Comment by mattleaf** [comment]
Cool, understood. ReMuxing it is :)
