### ISSUE TITLE
how to play cached videos

### ISSUE THREAD

**Issue by ylongbee** [JohnCoates/Aerial#804]
hi everyone,
There's some trouble when I use this beautiful screensaver.
1、I cashed some videos, but when Aerial runs it can not play the video I have cashed and just display a picture (display just a pic may because my network in China).

2、Could Aerial only use the cashed videos when it runs automatically ?  How to set it?

- [ ] macOS version: Mojave 10.14.5
- [ ] Aerial version: 1.4.9

**Comment by glouel** [comment]
> hi everyone,
> There's some trouble when I use this beautiful screensaver.
> 1、I cashed some videos, but when Aerial runs it can not play the video I have cashed and just display a picture (display just a pic may because my network in China).

I guess it tries to stream and stalls, that's why you only get a picture. 

There's probably a mirror of Aerials just for China. Do you know if Apple TV is sold there ? If not, there might not be.

> 2、Could Aerial only use the cashed videos when it runs automatically ? How to set it?

Yes, go to the Cache tab, and check:
- Never stream videos
- Never stream previews

Aerial will only play what's cached. 

> * [ ]  Aerial version: 1.4.9

1.5.0 is out by the way.

**Comment by glouel** [comment]
Please reopen if you still have an issue.

**Comment by ylongbee** [comment]
thanks, it works
