### ISSUE TITLE
Cache Location Changes During Update

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#815]
When jumping to 1.5.1beta4 (as well as a previous beta) it seems my cache location keeps getting changed. 

Due to limited space on my computer, I cache the files on an external hard drive that is always connected via USB-C to my 2018 Mac mini. During this update as well as a previous update, I noticed a great loss of disk space shortly after. When I investigated further I noticed that my Aerial cache had been automatically reset to its original location during the update caching the files on my internal SSD instead. 

Is there a way to ensure that this doesn't occur in future updates?

**Comment by glouel** [comment]
My guess is you are still on Mojave, you probably want to stay on 1.5.0 then. With the 1.5.1betas I'm mostly trying to deal with Catalina and the changes due to containairization. So some things may break there specifically around caches as I'm likely going to have to rewrite the whole thing (have a look in the Catalina issue for more).

It's possible one of the beta had a fault, but right now with 1.5.1beta4, your path should not change **if it exists**. So I'm a bit unclear on what you are saying, do you think the path switched once and you didn't see it, or are you saying that setting your path, then running Aerial, it switches back every time ?
 
One temporary change I made in betas to try and debug the Catalina mess is to save the path if I had to compute a new one. 

So if at some point, your disk is not accessible, and Aerial launches, in previous versions it would have created a Cache somewhere and used that, but it would not save that path. So, if next time your disk was there, it would keep trying that path. 

With the betas, if it fails once, it recompute a cache where it can, then saves that and your path is forgotten. Is it possible your drive wasn't there just once ? In any case I'll remove the temporary saving thing for next beta, but expect that things will probably change drastically at some point with Catalina regarding cache stuff.

**Comment by ZV00** [comment]
> My guess is you are still on Mojave, you probably want to stay on 1.5.0 then. With the 1.5.1betas I'm mostly trying to deal with Catalina and the changes due to containairization. So some things may break there specifically around caches as I'm likely going to have to rewrite the whole thing (have a look in the Catalina issue for more).

You are correct that I am on Mojave still, running the other betas but kept things save on my mini for the time being. 

>It's possible one of the beta had a fault, but right now with 1.5.1beta4, your path should not change if it exists. So I'm a bit unclear on what you are saying, do you think the path switched once and you didn't see it, or are you saying that setting your path, then running Aerial, it switches back every time?

I am not entirely sure _when_ it switched, but in the previous beta all files were correctly caching to the external drive, upon the installation of the new beta I noticed that they started caching to the internal SSD. I don't believe the drive disconnected at any point, so my assumption was that the installation somehow reset the cache location back to its default location rather than the customized location of the external drive. 

>If your drive gets disconnected (maybe it just goes to sleep and macOS thinks it's not there ?) I'd suggest you disable streaming so that you never fill up a second cache. That second backup cache will have at worse one video cached and you'll be able to use that as a "fallback" should you remove your drive.

Streaming was already enabled (i.e. "Never stream videos" was unchecked), but I have now also disabled Cache as they play, perhaps that will help in the future. Though, I am a little confused, are you saying it _should_ be checked?

**Comment by glouel** [comment]
You should CHECK "Never stream videos", so that it never streams videos. 
And you should leave UNCHECKED "Cache as they play" so that in the event it has no video, it will stream one (despite the setting above), cache it on disk, and reuse it all the time in that "backup" path.

It's never an install thing with Aerial, as things are recomputed all the time at launch. I assume you changed your path with 1.5.1beta4 and it stayed there ? 

Easy test : Go to UI, make sure your path is there, close syspref and launch screen saver. Reopen syspref, see if your path is still there. 

It's very possible I broke custom path with one of the previous betas (I don't *think* I did but who knows :)), other possibility is your drive may go to sleep or something sometime, Aerial can't use it, and fallbacks (and goes there all the time afterwards in betas, which it should never do).

If you see the path not sticking I can put a beta 5 up without the path saving thing I mention, so that it will always try your path even if it failed once before (the old way).

**Comment by glouel** [comment]
By the way, if you have debuglog always enabled, you could pinpoint the moment it switched cache. I guess you didn't have it enabled ?

**Comment by ZV00** [comment]
>You should CHECK "Never stream videos", so that it never streams videos. And you should leave UNCHECKED CHECKED (sorry for the edit, you got me confused :D) "Cache as they play" so that in the event it has no video, it will stream one (despite the setting above), cache it on disk, and reuse it all the time in that "backup" path.

Done. Hopefully that solves future issues. 

>It's never an install thing with Aerial, as things are recomputed all the time at launch. I assume you changed your path with 1.5.1beta4 and it stayed there ?

Yes it has changed since making the modification. But in a previous beta build I also noticed it reset. The first time I figured it was on my end, the second time I started wondering if it was a bug.

>It's very possible I broke custom path with one of the previous betas (I don't think I did but who knows :)), other possibility is your drive may go to sleep or something sometime, Aerial can't use it, and fallbacks (and goes there all the time afterwards in betas, which it should never do).

Definitely possible that this is what is causing it. I almost would prefer an error message to be generated somehow if that occurs than the reset of the cache location? I don't know if that's possible given the limitations (esp. with Catalina)

**Comment by glouel** [comment]
> > You should CHECK "Never stream videos", so that it never streams videos. And you should leave UNCHECKED CHECKED (sorry for the edit, you got me confused :D) "Cache as they play" so that in the event it has no video, it will stream one (despite the setting above), cache it on disk, and reuse it all the time in that "backup" path.
> 
> Done. Hopefully that solves future issues.

It should make you safe whatever happens yep !

> > It's never an install thing with Aerial, as things are recomputed all the time at launch. I assume you changed your path with 1.5.1beta4 and it stayed there ?
> 
> Yes it has changed since making the modification. But in a previous beta build I also noticed it reset. The first time I figured it was on my end, the second time I started wondering if it was a bug.

Yeah definitely was unintended. I was saving the path when I was trying to understand why preferences weren't saved (before I figured out the containairization thing). Should not have shipped that sorry ;)

> > It's very possible I broke custom path with one of the previous betas (I don't think I did but who knows :)), other possibility is your drive may go to sleep or something sometime, Aerial can't use it, and fallbacks (and goes there all the time afterwards in betas, which it should never do).
> 
> Definitely possible that this is what is causing it. I almost would prefer an error message to be generated somehow if that occurs than the reset of the cache location? I don't know if that's possible given the limitations (esp. with Catalina)

The thing is, the way it works now, Aerial *needs* a path to simply *not crash*. I could implement an earlier check, and put up a black screen with an error message if the path isn't there instead. 

I might do that as part as the cache rewrite thing.

**Comment by ZV00** [comment]
Yeah just a thought. Could also be an option to go with either set by the user. 

For me I only care as my SSD is small, 128GB, which means 20GB of files fills it really quickly lol. So for smaller SSDs like mine, having a way to keep it from randomly filling would be preferable, though it is definitely not a requirement.

**Comment by glouel** [comment]
Agreed about the option thing.

And definitely understand the SSD thing. Depending on how things go with Catalina, I might also add an option to limit cache size and periodically download new videos out of your selected list.

**Comment by glouel** [comment]
@ZV00 So here's beta5 with that specific fix : 

https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta5/Aerial.saver.zip

Aerial will no longer save a "workaround" cache if your directory is no longer there. You may need to set it again once (but it won't change anymore, promise !)

There are some other changes though as I started splitting the cache, JSONS and AerialLog.txt now go to ~/Library/Application Support/. Video download likely broken too. More info in the Catalina sticky. 

I'll be closing this one as this was a beta bug, feel free to comment/reopen if you see something wrong.
