### ISSUE TITLE
I have the latest version of Aerial running on the most recent Mac OS Update, 10.14.6

### ISSUE THREAD

**Issue by ccoberley** [JohnCoates/Aerial#842]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by ccoberley** [comment]
I have a 2018 model 15" Macbook pro with maximum configuration running 10.14.6 MacOS.
Screen saver is BEAUTIFUL let me first say that, and you should put links for a paypal donation or something. It looks so utterly mindblowing rendered on two 27" 5k displays from LG.

All was working very well and fluid until I recently modified my setup. Thunderbolt 3 from each display into each opposite side (separate controllers) of the MacBook Pro. Last night I added dual RAID 1 setup to my system for Time Machine. I believe this may be the culprit

I have two 5TB drives in Raid 0 backing up to one 10TB Drive, and I have configured the whole setup as RAID (2x5 TB striped = 10TB, then the other 10TB is set up to mirror)

I believe when I did this, I experienced a significant performance hit for the screen saverr.

My guess, and maybe you can help add any credence to this theory: I am just trying to push too much data down the thunderbolt cable - Time machine doing essentially "dual RAID" (2 6TB drives mirroring to one 10 TB drive over USB C). 

The drives are all plugged into the back of my monitors, and I am using them as USB C hubs.

I was hoping that thunderbolt and USB C would be able to handle the bandwidth of 2 x 5k displays + the three hard driver plugged in, buy it appears to greatly bog down and make the screen saver "stutter" - I get about  3 frames per second (literally). 

I unplugged the external drive to validate my assumption that too much data was coming over one thunderbolt 3 cable. However, this did not seem to help, and instead of being very fluid as before, the screen saver is still only producing about 3 franes per second.

I have disabled auto-graphics switching, forcing the Macbook Pro to use the Radeon Pro Vega 4GB video card, but still no luck.

Is there something in settings or perhaps another app or something that may be interfering with the fluidity of the screen savers? Previously they were silky smooth and amazing looking.

Please keep up the good work. Best screen saver I've ever had.

Carter

**Comment by glouel** [comment]
> I have a 2018 model 15" Macbook pro with maximum configuration running 10.14.6 MacOS.
> 
> All was working very well and fluid until I recently modified my setup. Thunderbolt 3 from each display into each opposite side (separate controllers) of the MacBook Pro. Last night I added dual RAID 1 setup to my system for Time Machine. I believe this may be the culprit
> 
> I have two 5TB drives in Raid 0 backing up to one 10TB Drive, and I have configured the whole setup as RAID (2x5 TB striped = 10TB, then the other 10TB is set up to mirror)
> 
> I believe when I did this, I experienced a significant performance hit for the screen saverr.
> 
> My guess, and maybe you can help add any credence to this theory: I am just trying to push too much data down the thunderbolt cable - Time machine doing essentially "dual RAID" (2 6TB drives mirroring to one 10 TB drive over USB C).
> 
> The drives are all plugged into the back of my monitors, and I am using them as USB C hubs.
> 
> I was hoping that thunderbolt and USB C would be able to handle the bandwidth of 2 x 5k displays + the three hard driver plugged in, buy it appears to greatly bog down and make the screen saver "stutter" - I get about 3 frames per second (literally).
> 
> I unplugged the external drive to validate my assumption that too much data was coming over one thunderbolt 3 cable. However, this did not seem to help, and instead of being very fluid as before, the screen saver is still only producing about 3 franes per second.
> 
> I have disabled auto-graphics switching, forcing the Macbook Pro to use the Radeon Pro Vega 4GB video card, but still no luck.
> 
> Is there something in settings or perhaps another app or something that may be interfering with the fluidity of the screen savers? Previously they were silky smooth and amazing looking.

Hi Carter

Let me try and understand your setup exactly with some extra questions (->) so we can figure this out:

- 2018 model 15" Macbook Pro 10.14.6 MacOS
-> I will assume Aerial 1.5.0 (not the beta)

- two 27" 5k displays from LG connected via TB, one monitor per port
-> Are you using just those two screens or also the internal MacBook Pro screen too ? 

- 2x5TB drives in Raid 0 
-> About that, you mention that's plugged into one of your monitor, what kind of enclosure are you using for these ? Those are connected as USB-C ? 
-> Also, are you using these as storage or did you install macOS there (instead of your MBP ssd) ?
-> Fairly important question, where did you setup your Aerial cache, is it on your MBP SSD, or on that RAID 0 volume?

If I got this right, things worked with that setup but you've added:

- 1 10 TB drive mirroring the 2x5TB
-> You seem to imply it's in the same enclosure than your 2x 5 TB or did I get this wrong. And this is configured as a... RAID 1 over your RAID 0 ? You also mention time machine so I'm a bit lost here. You're setting this RAID config with disk utility on your mac ? A screenshot would be nice. Also please clarify exactly what kind of drives you are using and what is connected to which monitor. 

I'm not exactly sure what your setup looks like but RAID1ing a RAID0 (I assume all are platter hard drives) is not a good idea. You are severely limiting your disk writes in that configuration and that itself may be an issue, and reads may be terrible.

Now with all that said, 3 FPS is terrible and if you were disk limited, I would assume Aerial wouldn't be the only slow thing on your mac right now (depending on your usage, of course). I have several ideas to help you troubleshoot this but let's try and get your setup right in my head before we go there !

Thanks !

> Screen saver is BEAUTIFUL let me first say that, and you should put links for a paypal donation or something. It looks so utterly mindblowing rendered on two 27" 5k displays from LG.

There's actually one next to my name on the readme, it's pretty well hidden. I don't feel good asking for donations more directly as I didn't start the project, although I'm taking care of it now ;)

**Comment by ccoberley** [comment]
Hi there, thanks for the quick response and also for making this screen saver available. It is my all time favorite.

Yes, two 27" 5k LG displays, connected by TB, one to each side of the macbook pro (1 TB cable per controller)

I am also using the Mackbook Pro 15" screen.

The two x 5 TB drives are external Lacie portable hard drives. I have them set to RAID 0, so 10TB

I took that 10 TB RAID set, and then "RAIDED it again" with an external 10TB Western Digital drive.

So, the two 5tb making up 10TB are also being mirrored to the other 10TB external drive

All 3 drives are in their own chassis and connected by USB C to the back of one monitor.

I used MacOS RAID assistant to set this up. I am frankly not sure if what I am doing is actually a "good idea" since I'm RAIDing the two 5TB drives, and then RAIDing them again to mirror to a 10 TB drive. However, it seems to be working.

So, all 3 drives are plugged into one of the LG displays (it has 3 usb C and 1 TB port).

The idea is that I have 2TB of SSD on the Macbook Pro, and then 10TB of redundant storage externally as time machine backup. I also backup to the cloud, but I do like the convenience of Time Machine.

Yes, I have the cache for the screen saver set up on the internal SSD.

I was thinking that I was basically maxing out the bandwidth of the TB / USB connection by sending all the data to the drives in RAID config, while at the same time pushing 2x 5k displays. But I do believe that the specs for TB / USB C have enough bandwidth, so this should not be an issue.

I will have to check out the readme and send a donation.

Thanks for the heads up on RAID1ing a RAID0 -- I tried it because I am basically a little crazy and wanted to see if it worked, but suspected it would create read and write issues. Despite that, it actually is working pretty well now, but I am going to "Un-RAID" them and then just have the two 5TB in RAID0, and the 10TB as stand alone. Time Machine has a setting where it can take turns backing up to separate drives and that sounds like the better option performance wise.

Regardless, the problem 'magically went away' after just letting the machine chug on the Time Machine backup all night long. This morning when I came out, the screen savers are running fluid and smooth as ever.

I am guessing there was just a lot of system overhead in first setting up the RAID devices and then also making the initial 555GB backup. 

So, whatever was causing the issue has vanished (at least for now).

**Comment by glouel** [comment]
Hi again, answers below
 
> The two x 5 TB drives are external Lacie portable hard drives. I have them set to RAID 0, so 10TB

Ok, if you are using two separate USB drives, you're paying a bit of a penalty by doing RAID 0 here but that should be "fine" for Aerial in any case, even if you had your cache there. 

> I took that 10 TB RAID set, and then "RAIDED it again" with an external 10TB Western Digital drive.

This I would probably recommend against. I'd suggest you don't RAID, but either use Time Machine to backup from the 2x5 to the 10, or some other sort of tool (Super Duper, etc) as that should make things massively faster for you in daily usage. 

In terms of performance, there's a bit of a penalty that you are paying from the USB to SATA bridges chips in those external drives, to which you have to add the thunderbolt transport, etc... So that doesn't help.

> I used MacOS RAID assistant to set this up. I am frankly not sure if what I am doing is actually a "good idea" since I'm RAIDing the two 5TB drives, and then RAIDing them again to mirror to a 10 TB drive. However, it seems to be working.

It should work but is probably not very fast nor the best use of those drives. It really depends on what you need in terms of performance from them. There are benchmark tools like this one http://katsurashareware.com/dl/AmorphousDiskMark.zip for example that will show you the speed of your volume in different tasks. 4K should be the most interesting, especially compared to 4K32 (32 being the size of the queue).  

> So, all 3 drives are plugged into one of the LG displays (it has 3 usb C and 1 TB port).

I'm not 100% sure of how macOS handles USB data over thunderbolt, but I would highly recommend keeping the 3 drives behind the same monitor. 

> The idea is that I have 2TB of SSD on the Macbook Pro, and then 10TB of redundant storage externally as time machine backup. I also backup to the cloud, but I do like the convenience of Time Machine.

Ok that part has me lost here, if you are double RAIDing, what are your time machining from/to ?

> Yes, I have the cache for the screen saver set up on the internal SSD.

Ok that definitely clear things up. 

> I was thinking that I was basically maxing out the bandwidth of the TB / USB connection by sending all the data to the drives in RAID config, while at the same time pushing 2x 5k displays. But I do believe that the specs for TB / USB C have enough bandwidth, so this should not be an issue.

Yes, that's definitely not your issue. Thunderbolt has more than enough bandwidth and since your Aerial cache is on SSD, there should be no issue there. 

> Thanks for the heads up on RAID1ing a RAID0 -- I tried it because I am basically a little crazy and wanted to see if it worked, but suspected it would create read and write issues. Despite that, it actually is working pretty well now, but I am going to "Un-RAID" them and then just have the two 5TB in RAID0, and the 10TB as stand alone. Time Machine has a setting where it can take turns backing up to separate drives and that sounds like the better option performance wise.

Hehe, it's always good to try ! I have to say I'm a bit curious about the performance you got. You can use the benchmark I linked above to compare performance between those different solutions, that should be interesting ! 

> Regardless, the problem 'magically went away' after just letting the machine chug on the Time Machine backup all night long. This morning when I came out, the screen savers are running fluid and smooth as ever.

Ok but I don't get what were you time machining from to where ? Internal SSD to the double RAID ? 

If that's correct, I'm pretty sure that Time Machine writes a lot of small files, so in general, it's the worse case scenario for a USB drive, and if you double RAID it, it probably makes it much worse (when you write to a RAID 1 ,each write is delayed by making sure both drives actually wrote the data, while RAID 0 will write to one then the other). So it's possible you were suffering from some Queue Depth issue depending on what protocol your USB drives uses (whether your drive uses Bulk Only Transport protocol, or UASP). 

The fact it's smooth now makes me think that was your issue. The only other thing I could think of, considering you were storing your cache on internal SSD, is that you were on a slow internet connection and were trying to play an uncached video that was streaming slowly from the internet. 

> I am guessing there was just a lot of system overhead in first setting up the RAID devices and then also making the initial 555GB backup.

The first time you run Time machine is pretty hard on any configuration in any case so that makes sense that it was extra hard here. Aerial was "competing" for disk I/O with the rest of the system (those videos are large in 4K!). 

> So, whatever was causing the issue has vanished (at least for now).

If it ever comes back just let me know (and if you happen to try the performance benchmark I linked in various situations, feel free to post some screenshots of the results).
