### ISSUE TITLE
Unable to paste into Edit extra message dialogue and broad unicode support

### ISSUE THREAD

**Issue by marcb** [JohnCoates/Aerial#843]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MacBook Pro (Retina, 15-inch, Mid 2015)
- [X] macOS version:  10.13.6 (17G8030)
- [X] Monitor setup: Laptop internal only

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Open preferences for the screen saver, in `Text` section, `Extra information`, `Show an extra message`; select `…` to edit the text. In the subsequent dialogue box attempt to paste via (`⌘V`) keyboard sequence previously copied text.

Workaround possible via the `Edit` menu and selecting `Paste`. But this doesn't work all the time.

If the text contains Emoji or other unicode characters it doesn't get saved.

Subsequent updates also don't updated...
[aerial text edit issue.mp4.zip](https://github.com/JohnCoates/Aerial/files/3563038/aerial.text.edit.issue.mp4.zip)

**Comment by glouel** [comment]
Hi @marcb 

Sorry about that! 

Bit of background, Swift screensavers aren't officially supported by Apple, and there are bugs with some versions of the OS because of this. In 10.13 and prior, Aerial's preference panel cannot get the focus, you can see in your video that the tab is grey as if the window was not selected. 

This a bug I tried to workaround every which way I could think of but that didn't work. That's why there's a "..." thing that pops a new window. This is a 10.13 thing only and Apple fixed the bug in Mojave. Should you upgrade someday, there's no longer the "..." button as you can see in here :

![Capture d’écran 2019-09-01 à 11 55 11](https://user-images.githubusercontent.com/37544189/64074736-9012b900-ccaf-11e9-9080-c48652d21f71.jpg)

There, you can directly paste in the field and pasting works correctly. On your video, the little window is hidden so I don't see what's happening, but pasting *regular text* should work there, I think reliably ?

But ! Unicode and Emojis, for some reason, don't work. I tried this here, and typing an Emoji doesn't show anything in the text box so that's probably why your paste fails there. I'm completely surprised by this one, as I thought macOS handled unicode by default, I must have missed a checkbox somewhere, considering I'm pretty sure I did try Emojis in the JSON descriptions and it worked there.  

I'll have a look to see if I can fix this and get back to you. 

In the meantime, I'd suggest you try pasting regular text only and tell me if that's reliable at least ?

Thanks!

**Comment by glouel** [comment]
@marcb quick update:

I did try here on 10.15 Catalina, and Emojis/unicode do work here. I tried to replicate exactly what you did, paste from TextEdit some unicode + emoji and that works : 

![Capture d’écran 2019-09-01 à 12 40 18](https://user-images.githubusercontent.com/37544189/64075277-6c9f3c80-ccb6-11e9-90ac-9be0f0df153e.jpg)

I was wondering if TextEdit was the issue, because if you check, the Emoji has it's own font in TextEdit, Apple Color Emoji, which is different from the text you are pasting, but when you paste to a "single font" text field, macOS converts that correctly to basic unicode, removing the font attributes, and keeping the Emoji correctly interpreted. 

Pasting works with both `cmd + v` and right click the field and select `paste` here. In all cases, the text is saved correctly and is displayed in the screen saver.

I booted up my old 2011 Macbook Air under Mojave and that scenario works correctly there too. Including inserting via the emoji picker by pressing `ctrl + cmd + space`. 

So that gets us back to the particular workaround issue, I did a quick check here by reenabling the "..." in all versions, and I found another unrelated bug that might be what you saw. If you type anything, then just press "Close", it won't be saved. However if you just press `Tab` to "leave" the textfield (don't click "Close"), you can see the main window's field getting updated in real time. So I think that I may just have messed up here by not applying the change with the "Close" button is pressed. 

Can you confirm pressing tab fixes it ? If so I will fix this for next version, really sorry about that! I'll also check the other workaround paths to make sure that works as intended.

**Comment by marcb** [comment]
Thanks for the detailed explanation.

I can confirm the `Tab` before `Close` works, even from copying from TextEdit. 🤓

**Comment by glouel** [comment]
Thanks for confirming I will fix that bug ASAP !
