### ISSUE TITLE
'Trash old videos' clears cache

### ISSUE THREAD

**Issue by GabrielSiq** [JohnCoates/Aerial#880]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (15-inch, 2019)
- [x] macOS version: 10.15.1
- [x] Monitor setup: MBP + Thunderbolt Display

#### Description of issue / Feature request

This might be just a matter of me misunderstanding a feature. I had all available videos cached in 4K. I recently found out the feature of 'Trash old videos' under the Advanced tab, which I thought meant freeing space from older versions of videos that aren't used anymore. After pressing the button, all of the cached videos were gone and I've then re-started the download of all of them.

Additionally, and this should probably be a separate issue, I'm unable to update to 1.6.3. It downloads the update but when I click to update and relaunch, it closes and no matter how much I wait, it doesn't relaunch. After a while I close System Preferences and re-open aerial configs, and it's still at 1.6.2.

**Comment by glouel** [comment]
Hi @GabrielSiq 

> This might be just a matter of me misunderstanding a feature. I had all available videos cached in 4K. I recently found out the feature of 'Trash old videos' under the Advanced tab, which I thought meant freeing space from older versions of videos that aren't used anymore. After pressing the button, all of the cached videos were gone and I've then re-started the download of all of them.

First, sorry about that. 

This doesn't sound right at all, I'll need to check ! You mentioned you had 4K (HDR disabled I guess) cached, and just pressed Trash old videos, correct ? Since you are using Catalina, I assume you cached those recently (after Catalina install) right ?

> Additionally, and this should probably be a separate issue, I'm unable to update to 1.6.3. It downloads the update but when I click to update and relaunch, it closes and no matter how much I wait, it doesn't relaunch. After a while I close System Preferences and re-open aerial configs, and it's still at 1.6.2.

Yes, this is a known bug in Catalina sadly, auto updates fail because of the new sandboxing. You need to update manually for the time being. I'm hoping we can fix this soon.  There's a lot of issues around Catalina, you can read a summary here : https://github.com/JohnCoates/Aerial/issues/880

**Comment by GabrielSiq** [comment]
No worries - first of all I appreciate the project and just wanted to flag in case anything is wrong. I'm not upset in the slightest.

'Use HDR if available' is checked. 4K HVEC is selected.

I had them cached before Catalina but if I remember correctly (and sorry, my memory isn't that reliable) I had to cache it again after updating to Catalina, so I think those were fairly recent. It said there were 80 old videos found. Could have been the videos from before the update to Catalina, I didn't really check the folder. I clicked trash old videos and then the next time screen saver kicked in I noticed a certain lag, which indicated it was trying to stream the 4K video and cache was gone. 

Regarding the auto update - I was aware of the issue but didn't know the definition of autoupdate. I thought it meant some background update and actively clicking the update button wasn't considered autoupdate. Now I got it. If I download the latest release from here and update it, would my settings (and cached videos) survive?

**Comment by glouel** [comment]
> No worries - first of all I appreciate the project and just wanted to flag in case anything is wrong. I'm not upset in the slightest.
> 
> 'Use HDR if available' is checked. 4K HVEC is selected.

Ok I think that might be the issue. It's quite possible I didn't update the trash code for HDR, I'll have a look tomorrow ! I had another bug relating to HDR so it's quite possible there's something there. 

> I had them cached before Catalina but if I remember correctly (and sorry, my memory isn't that reliable) I had to cache it again after updating to Catalina, so I think those were fairly recent. 

So, if you enable HDR, you have to recache videos (they are different files) so that could be it. Also, files that you had previously were on a location that Aerial couldn't write/delete to now with the sandbox thing, so it's quite possible there's something wrong in there. 

> It said there were 80 old videos found. Could have been the videos from before the update to Catalina, I didn't really check the folder. I clicked trash old videos and then the next time screen saver kicked in I noticed a certain lag, which indicated it was trying to stream the 4K video and cache was gone.

I see, so the new files were gone. Could you go into the Cache tab in Aerial, and tell me what the read only cache location is (the one that shows with > in the middle). If you click show in finder, what do you see there ? Possibly your old files ?

Catalina may have wiped your cache (or not, it wiped mine in Catalina beta, didn't for a friend who waited for 10.15.1 to upgrade) too at install which doesn't help.  

> Regarding the auto update - I was aware of the issue but didn't know the definition of autoupdate. I thought it meant some background update and actively clicking the update button wasn't considered autoupdate. 

You're right. All the updates, either automatic or manual through Sparkle (the subproject that downloads and install, see more here if curious : https://sparkle-project.org) are currently broken.

> Now I got it. If I download the latest release from here and update it, would my settings (and cached videos) survive?

Yes ! Just download the file here : https://github.com/JohnCoates/Aerial/releases/download/v1.6.3/Aerial.saver.zip

You can then double click the .saver and it will overwrite the old version. Settings and cache will be preserved. I highly recommend you close System Preferences before double clicking the .saver. If you don't, you'll have to close and reopen System Preferences to get it to load correctly. 

Thanks for the report, I'll let you know when I find the bug and hopefully I can fix it for everyone !

**Comment by GabrielSiq** [comment]
Thanks for the explanation. It all seems more clear now.

Regarding the cache location, both places seem to point to the same folder, which seems to contain the videos currently being downloaded.

**Comment by glouel** [comment]
Ok thanks for confirming, looks like I accidentally trash the hdr videos I guess, looking for regular instead. I’ll keep you updated !

**Comment by glouel** [comment]
Hi @GabrielSiq 

So I had a look and there were many bugs around the move/trash feature and I ended up finding a few others. As you experienced, HDR videos would always be detected/moved/trashed as if they were outdated video files. This is fixed. 

There were a few places where Aerial was still looking in the old read only cache folder and not the sandboxed one, for example cache size which was incorrect as a result (if your optional read only cache was set differently than in the sandbox).  

I made a few other changes to try and clarify things based on your feedback and others:
- I clarified in the Catalina issue (https://github.com/JohnCoates/Aerial/issues/801) that all automatic updates, whether silents or the ones you manually checked/approved through Sparkle would always fail in Catalina for the time being. 
- I clarified the language about HDR to clearly say that those are separate files. I also added an help button with more info about how these files are different (all 4K videos are 10 bit encoded, but HDR ones are using Dolby Vision). 

![Capture d’écran 2019-11-01 à 13 05 21](https://user-images.githubusercontent.com/37544189/68023757-7807e780-fca8-11e9-8147-d0aab89baf62.jpg)

You can manually update by installing this on top of your version : https://github.com/JohnCoates/Aerial/releases/download/v1.6.4/Aerial.saver.zip

You should now see that you have 0 outdated files after install. Please let me know that this works correctly for you.

**Comment by GabrielSiq** [comment]
The behavior works as you described. I see 0 outdated files and cache size is correctly detected. Do you know what the default for the old cache is? I feel like there are remaining files there that I might need to manually delete.

One quirk from the update, though: I closed system preferences as instructed before updating. When I opened it back up, there were two Aerial screensavers listed that seemed to point to the same thing (both showed 1.6.4 as version). I deleted one of them.

**Comment by glouel** [comment]
> The behavior works as you described. I see 0 outdated files and cache size is correctly detected.

🎉

>  Do you know what the default for the old cache is? I feel like there are remaining files there that I might need to manually delete.

So the previous cache location was either `~/Library/Caches/Aerial/` or `/Library/Caches/Aerial/`, depending on when you installed first.

You will have to delete those files manually though, as Aerial can no longer delete those files itself in Catalina because of sandboxing (which brought that whole mess of bugs). You can safely delete everything there. 

> One quirk from the update, though: I closed system preferences as instructed before updating. When I opened it back up, there were two Aerial screensavers listed that seemed to point to the same thing (both showed 1.6.4 as version). I deleted one of them.

That's... intriguing, certainly never heard of that one before ! One thing I can think of is that at the very first install time, when you double click a saver file, you can either install for your own user or all users. But when you upgrade, System Preferences should tell you that you have an older version installed and if you want to overwrite. 

Assuming you said yes, it should replace it. If you said no, I don't know what happens to be honest ! One thing to keep in mind is that you can only have one version of the screensaver in memory at a time (that's why I ask to close syspref, if you don't, it won't reload correctly) so that makes things a bit weirder, maybe somehow you had both versions on your system but both would say 1.6.4 because you can only have one opened at a time anyway (it's a Swift bug with syspref). 

Or could be a SysPref bug, install is very much out of our hands. That's super weird in any case, if you see that next time, feel free to reopen a bug report !

**Comment by GabrielSiq** [comment]
Hmmm, interesting... I can only find two folders named Aerial. One is in `Library/Application Support` and mostly contains old logs, jsons, but no videos. The other is in `/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support` and has all my current videos.

Regarding the install, I got asked the first case only: install to this user only or all users. No question about upgrade. I had SysPref closed. One thing to mention, is that when I extracted the zip file in my download folder, it got renamed `Aerial 2.saver` due to a previously existing file in the same folder.  As a result, the file under `/Library/Screen Savers` generated after I double clicked it is also called `Aerial 2.saver`. Could that be the reason?

**Comment by glouel** [comment]
> Hmmm, interesting... I can only find two folders named Aerial. One is in `Library/Application Support` and mostly contains old logs, jsons, but no videos. The other is in `/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support` and has all my current videos.

My guess is the old Caches folders were wiped by Catalina's upgrade process. You can safely delete the one in `Library/Application Support`

> Regarding the install, I got asked the first case only: install to this user only or all users. No question about upgrade. I had SysPref closed. One thing to mention, is that when I extracted the zip file in my download folder, it got renamed `Aerial 2.saver` due to a previously existing file in the same folder. As a result, the file under `/Library/Screen Savers` generated after I double clicked it is also called `Aerial 2.saver`. Could that be the reason?

100%. That's why it didn't prompt you to upgrade, it's based on filenames ;) When you double click a .saver, System Preferences just copies it in your screensaver folder (and with a different name, you weren't prompted to overwrite). That's why you had 2. And they both showed as 1.6.4 because you opened the Aerial 2 first.

You should close/reopen syspref and check version, to make sure you deleted the correct one.
