### ISSUE TITLE
Aerial screensaver starts off smooth but gets choppy after a few minutes

### ISSUE THREAD

**Issue by TurboAsterix** [JohnCoates/Aerial#882]
Aerial screensaver starts off smooth but gets choppy after a 5 minutes on Mac Mini Late 2012 with 16 GB RAM and 500 GB Samsung 850 Evo SSD. This occurs both with Mojave and Catalina 10.15.1.

Exactly the same topic was discussed here, but as it is still reproducible and issue #428 is not fixed or explained:
[Issue 428](https://github.com/JohnCoates/Aerial/issues/428)

- Is it always choppy from the start or just gets choppy at some point ?
It get's choppy after exactly 5 min of playback.

- Are videos cached ?
Yes, H264 videos all cached. Cached or streamed does not show any change.

- Multimonitor ? If so which mode ?
Yes, play on All Display, Mirrored, Fill Screen.
Changing those settings does not have any effect on the choppy playback. It always gets stuttering after 5 min. Even disabling one of the displays and leaving it just black and playing the video only on the main display still produces the stuttering after exactly 5 min.

- Are you using 1080p H264 as prefered video format ?
Yes

I tried increasing the process priority of the Vtdecoderxpcservice with renice, disabling Time Machine, Spotlight, killing iCloud Photo Analysis etc. All this does have no effect and the stuttering always again occurs after exactly 5 min. If it would be a system resource bottleneck, then definitely playing only the video on one display instead of two should have massively reduced the system load. I am not convinced that it is a CPU/GPU/disk/network resource issue.

The Aerials trace file does not show anything useful, except that it started the Animation.

Enabling the Mac OS based screensaver system clock (in Mac OS setting, not in Aerials settings) does not change anything. I had stuttering after a while, too, on a Macbook Pro 13 inch Mid 2012: Here enabling the Mac OS based clock fix the issue.

The Mac Mini has a Core i5" (3210M) CPU with Intel HD Graphics 4000, then MacBook Pro Mid 2012 has basically same CPU and same integrated Graphics.

Other system standard screensavers like Arabesque show similar behaving.
Too me this looks overall like a strange Mac OS bug or strange Mac OS behavior that needs to be mitigated, since later Mojave versions and affecting the Mac Minis.

Best regards,
TurboAsterix

Before logging an issue please check that:
- [X] You have the latest version installed
1.6.4 is installed; no beta versions found. 

- [X] Your issue isn't already mentioned in our [issues]
It is mentioned in 428, but without working solution or workaround. 

- [X] Your problem isn't mentioned in the [troubleshooting section]
It is mentioned, but purposed fix does not fix the problem. Not a CPU load problem, not a iCloud Photo Analysis problem, not a Spotlight related.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model:
Mac Mini Late 2012
- [X] macOS version:
Catalina 10.15.1 
- [X] Monitor setup:
27 inch Fujitsu Display L27T1-LED at 1920x1080 and Lenovo L1951p Wide at 1440x900.

**Comment by glouel** [comment]
Hi @TurboAsterix 

> Aerial screensaver starts off smooth but gets choppy after a 5 minutes on Mac Mini Late 2012 with 16 GB RAM and 500 GB Samsung 850 Evo SSD. This occurs both with Mojave and Catalina 10.15.1.
> 
> Exactly the same topic was discussed here, but as it is still reproducible and issue #428 is not fixed or explained:
> [Issue 428](https://github.com/JohnCoates/Aerial/issues/428)

There can be multiple causes of choppiness and Catalina introduced a few others, so I'm not exactly sure this is the same bug (that was fixed in Mojave actually, for that one thread). 

> * Is it always choppy from the start or just gets choppy at some point ?
>   It get's choppy after exactly 5 min of playback.

This one is super weird. Exactly 5 mins is not something I've ever heard about in the various choppiness scenarios.  
 
> * Are videos cached ?
>   Yes, H264 videos all cached. Cached or streamed does not show any change.
> * Multimonitor ? If so which mode ?
>   Yes, play on All Display, Mirrored, Fill Screen.
>   Changing those settings does not have any effect on the choppy playback. It always gets stuttering after 5 min. Even disabling one of the displays and leaving it just black and playing the video only on the main display still produces the stuttering after exactly 5 min.
> * Are you using 1080p H264 as prefered video format ?
>   Yes

Ok. Since then I'll add one more question, did you enable HDR or not in Catalina ?

There's known stuttering with HDR on some machines, I thought this was limited to AMD Graphics Macs but someone with an Intel integrated graphics reported a similar issue yesterday here : https://github.com/JohnCoates/Aerial/issues/801#issuecomment-551320935

If you have it enabled, can you try disabling it and letting me know ?

> I tried increasing the process priority of the Vtdecoderxpcservice with renice, disabling Time Machine, Spotlight, killing iCloud Photo Analysis etc. All this does have no effect and the stuttering always again occurs after exactly 5 min. If it would be a system resource bottleneck, then definitely playing only the video on one display instead of two should have massively reduced the system load. I am not convinced that it is a CPU/GPU/disk/network resource issue.

On the one hand, the 5 mins thing would suggest some sort of delayed task starting. But this is very weird. As far as ressources, the GPU decoding on Intel is done through a fixed unit so that's usually not an issue. iCloud Photo Library may have tried to use those units in // in some cases was something that I've seen a long time ago, but not recently. 

> Enabling the Mac OS based screensaver system clock (in Mac OS setting, not in Aerials settings) does not change anything. I had stuttering after a while, too, on a Macbook Pro 13 inch Mid 2012: Here enabling the Mac OS based clock fix the issue.

That's interesting, again I'd ask about HDR too on your MBP ? There are multiple weirdness happenning right now on more recent Intel graphics Mac, see here : https://github.com/JohnCoates/Aerial/issues/871

My rough guess is that 2015 and before are probably on another driver than 2016+ Macs with Intel graphics and the issues are different. 

> The Mac Mini has a Core i5" (3210M) CPU with Intel HD Graphics 4000, then MacBook Pro Mid 2012 has basically same CPU and same integrated Graphics.
> 
> Other system standard screensavers like Arabesque show similar behaving.

At exactly 5 mins ??? That's...

> Too me this looks overall like a strange Mac OS bug or strange Mac OS behavior that needs to be mitigated, since later Mojave versions and affecting the Mac Minis.

Please let me know about HDR and I'll try to think about what we can do, but if you see the same issue with Arabesque then I'm afraid it's a MacOS bug and the best way forward may be to fill a radar. 

Thanks !

**Comment by TurboAsterix** [comment]
> This one is super weird. Exactly 5 mins is not something I've ever heard about in the various choppiness scenarios

I just tried again, now both display enabled again and mirrored.

I had Aerials stuttering starting always at 5:02, this time it was 5:03. But for it is always +/- 1 second which is most likely manual stopwatch measurement error. I told exactly 5 mins because I started the watch when moving the mouse into the corner, it still takes 1-2 seconds until the screensaver comes up.

And just reproduced the same with Flurry (not sure if translation from German "Wirbel" is correct), Mac OS standard screensaver, stuttering exactly after 5:02. 

> Ok. Since then I'll add one more question, did you enable HDR or not in Catalina ?
HDR is disabled on both the Mac Mini and the Macbook, the Macbook is anyhow still on 10.14.6. 
I tried HEVC / HDR playback, but I can't even play the cached file in quicktime without massive stutter. Here I guess the Mac Mini 2012 has no hardware decoding support and is just lost ... 

Best regards,
TurboAsterix

**Comment by glouel** [comment]
> > This one is super weird. Exactly 5 mins is not something I've ever heard about in the various choppiness scenarios
> 
> I just tried again, now both displays enabled again and mirrored.
> 
> I had Aerials stuttering starting always at 5:02, this time it was 5:03. But for it is always +/- 1 second which is most likely manual stopwatch measurement error. I told exactly 5 mins because I started the watch when moving the mouse into the corner, it still takes 1-2 seconds until the screensaver comes up.

Agreed, 3 sec is definitely in the margin. The fact that it's always around 5 mins is truly weird. Reason I asked is here it tends to be "after a while" (the HDR version of the lag), but sometimes it's starts with lag too and time looked pretty random (although I never timed it).  

> And just reproduced the same with Flurry (not sure if translation from German "Wirbel" is correct), Mac OS standard screensaver, stuttering exactly after 5:02.

Ok I see (called "Faisceaux" here in french ;)). 

The fact that you get it with bundled screensaver either point to a weird timed bug or some background task started by system (or some power management thing kicking in maybe ?). 

Speaking of power management, one thing coming to mind is that there are a couple of options there. Can you check if you have "shutdown disk drives as soon as possible (that's the second entry here in sys pref > the lamp thing), and if you have power nap activated or not. Maybe playing with those could help ?

> > Ok. Since then I'll add one more question, did you enable HDR or not in Catalina ?
> > HDR is disabled on both the Mac Mini and the Macbook, the Macbook is anyhow still on 10.14.6.
> I tried HEVC / HDR playback, but I can't even play the cached file in quicktime without massive stutter. Here I guess the Mac Mini 2012 has no hardware decoding support and is just lost ...

Makes sense. Thanks for answering.

So barring the power settings, I would very much suggest you send a bug report to Apple from "feedback assistant.app" (it's bundled with Catalina). I can give you a hand if you need help going through that. It does collect some information on your specific system so it's better if you're filling it from the machine that exhibits the issue.

**Comment by TurboAsterix** [comment]
Speaking of power management, one thing coming to mind is that there are a couple of options there. Can you check if you have "shutdown disk drives as soon as possible (that's the second entry here in sys pref > the lamp thing), and if you have power nap activated or not. Maybe playing with those could help ?

Yes, had the same thought. Energy settings Computer/Display are at Never/Never. 
Shutdown disk drives is disabled, Power Nap is disabled. 

Will try the Feedback Assistent. I know macOS is in controls the Intel Speedstep Feature and I think or it looks like it just throttles the CPU. When I click on the stuttering screensaver, only that the login prompt is coming back without unlocking, then it returns to normal performance and stuttering is going way.

Best regards,
TurboAsterix

**Comment by glouel** [comment]
It's possible some throttling is happening, there are some low power states on the GPU too. I don't recall exactly how power states worked for the GPU of that particular Intel generation but in general, they should not affect the decoding unit (if it's hardware decoded) though, hmm. 

The fact that it does return to normal when you "wake it up" points to something of that caliber though. Recording clock speeds/power states for the duration of the screensaver could clear that up but I don't know if there's such a tool on macOS (activity monitor is pretty limited). 

Just to be cautious, I did try to replicate the 5 mins thing here with both the screensaver you mentioned but didn't hit the issue. Let me know when you get some feedback from the assistant, hopefully we can clear things out.

**Comment by TurboAsterix** [comment]
You're right when thinking about the GPU power states. 
I installed the Intel Power Gadget and it supports a logging to file. 
I added a screenshot and my log file to this issue, maybe you see something in addition. In short words, during the stuttering phase, the CPU ramps done but the GFX frequency ramps up. When clicking on the screen and waking the machine up, this is reversed and everything is back to normal. 

Here are my observations:

**21:16:00 Start of screen saver** 
According to the peak in CPU utilization, 21:16:00:524 seems be the exact point in time of start.
During normal (not stuttering playback) for 05:02 minutes:
- Average CPU frequency 1872 MHz
- Requested CPU frequency 1955 MHz
- GFX frequency is 350 MHz

21:21:02 Stuttering starts exactly 05:02 min after screen saver start, visible at peak in CPU usage
At prior test it showed 86% CPU peak utilization, this test and log file shows 61%.
In common between different test is always a short peak in CPU utilization.

During stuttering playback (I let it stuttering for exactly 1 min):
- Average CPU frequency 1500 MHz
- Requested CPU frequency 1593 MHz
- Average GFX frequency 1082 MHz

21:22:00 Click on screen to get login prompt

21:22:03 Stuttering stops
During resumed normal (not stuttering playback):
- Average CPU frequency 2034 MHz
- Requested CPU frequency 2090 MHz
- Average GFX frequency 404 MHz

Best regards,
TurboAsterix
![Intel Power Gadget](https://user-images.githubusercontent.com/50270648/68509637-afaafc80-0271-11ea-9cbb-665dbf7fb138.png)
[Aerials_CPU_GFX_log_file.xlsx](https://github.com/JohnCoates/Aerial/files/3826200/Aerials_CPU_GFX_log_file.xlsx)

**Comment by glouel** [comment]
@TurboAsterix that's super interesting, thanks for the xls file, that brings me back a bit to my old job ;)

Some quick remarks : 
- first you noted that the CPU clock drops a bit (but at no time you are CPU bound if you look at CPU usage). This is actually normal on those CPU families. Because they share a common TDP enveloppe for both the IA/CPU cores and the GT/Graphics "cores", using the graphics cores lowers the available power for the IA cores, so you see a slight dip. That's a known behavior of those CPU and is of no issue. It is however indicative of a GPU load on the GT cores (more on that later).
- second you noted the GPU clock going way up. That's fairly significant. The so called "gpu acceleration" of H.264 decoding is done by what Intel markets as QuickSync, this is a fixed function block (a separate part of the GPU) that is independent from the GPU cores. So as you can see, when the playback starts, your "gpu cores" (GT) stay idle at 350 MHz. 
- at 21:22 (thanks for highlighting those lines btw !) though as you pointed out, the GPU clock spikes up. This is definitely not something that's linked to video playback in my opinion. Something else is using your GPU cores. 

Now if you look at column "I" (Processor Power aka package power, so CPU (IA) and graphics (GT)), you'll see that in the 16-22 period, the whole package is pulling about 5-7W which is fairly constant (you have the classic random spike but it's in that ballpark for a large amount of time. IA column, which is column "L" is about 1.5-3W roughly during that period.

Yet, when all goes wrong (if you put aside a 1/2s spike), your package power goes way up 9-10W. And your IA cores remain in the same ballpark as before, if not below (again, see my first point about shared power enveloppe).

So from that I think it's a pretty strong conclusion that your GT cores are running some shader code for something (and the 1/2s of CPU spike you see at the start of the stuttering is pretty consistent with something waking up on cpu, getting prepared before getting shipped to the GT cores). From that I think the best way forward would be to look for what process gets started (if any, and I have a strong suspicion that something is) around 5min after you start your screensaver. 

I can think of a couple of things, beside the photo library sync, Apple also does on device "recognition" of things in pictures (objects, people) using shader code. That task may be started around that point in time, and that would definitely wreck the video playback (while the fixed unit is independent, they do share the same memory path for example). I'm not sure there's a way to disable that though, off the top of my head. 

There's probably a way to figure out what gets started when, and that would probably be the best way forward to keep investigating this. In my opinion, there's definitely some shader code running on your GPU and that's the issue behind the whole thing.

**Comment by TurboAsterix** [comment]
@glouel : Thanks for the very detailed reply and I am learning a couple of things from it! 

I enabled SSH on the MacMini and did via a remote login a ps -ef at about 4:45 min screensaver runtime and did another ps -ef after the stuttering started. Then I reduced it to the delta between the two lists. Attached is the delta. 

Candidates: 
I actually already outruled Google Drive File Stream, but I see it running with an interesting parameter --type=gpu-process. I am unsure if disabling File Stream deactivates as well everything, like Google Drive File Stream Helper.app. However, I installed Drive Stream pretty new and I had the stuttering problem already before. I will try getting everything deactivated again relative to File Stream, although I don't think it is the root cause. It is as well started with system startup, however there could be delayed tasks.

My second favorite candidate is:
/System/Library/PrivateFrameworks/VideoProcessing.framework/Versions/A/mediaanalysisd

It looks more promising, as it gets started at the time the stuttering starts and as well matches your thinking. 

[ps_analysis_delta_stuttering_vs_non_stuttering.xlsx](https://github.com/JohnCoates/Aerial/files/3827268/ps_analysis_delta_stuttering_vs_non_stuttering.xlsx)

Best regards,
TurboAsterix

**Comment by glouel** [comment]
Happy to help. And mediaanalysisd would match well with the symptoms indeed. 

I'd suggest disabling it just to try, found this which work (or not, hopefully it still does, Catalina is weird with system processes) : https://discussions.apple.com/thread/7965601

**Comment by TurboAsterix** [comment]
Thanks. I can confirm it root cause is mediaanalysisd. 
photoanalysisd is as well running, but it seems to have no impact.
 
I used the recovery terminal to remove the /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist file and this seems to prevent that the process is started. 
Once I have more patience, I restore the file and will let the machine run with a blank screensaver for a couple of days and will check if it ever comes to an end. I tried this before but only for one night ... that seems to be too short. Some people in posts recommended to let it run multiple days.

But great, Aerials is working smoothly again for > 30 minute :-))

Best regards,
TurboAsterix

**Comment by glouel** [comment]
> Thanks. I can confirm the root cause is mediaanalysisd.

Woohoo 🎉

> photoanalysisd is as well running, but it seems to have no impact.

I guess the photo one is for photos... and the other one for videos ? Could explain the difference (way more bandwidth needed on videos). 

> I used the recovery terminal to remove the /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist file and this seems to prevent that the process is started.

I'll add a mention to this in the FAQ for others when I get a sec, great !

> Once I have more patience, I restore the file and will let the machine run with a blank screensaver for a couple of days and will check if it ever comes to an end. I tried this before but only for one night ... that seems to be too short. Some people in posts recommended to let it run multiple days.

Do you happen to have a lot of videos stored on that machine maybe ? 

> But great, Aerials is working smoothly again for > 30 minute :-))

Nothing else matters 😅

Glad to hear it's fixed now, take care !
