### ISSUE TITLE
[Feature Request] 21:9 video for UltraWide Monitors

### ISSUE THREAD

**Issue by jonktsui** [JohnCoates/Aerial#904]
Firstly, thank you for this awesome project! 

Any options for 21:9 videos for ultrawide monitors? When setting videos to fill screen, the videos look very blurry. Fit to screen has the black bars on the side :(

**Comment by glouel** [comment]
Hi @jonktsui !

> Firstly, thank you for this awesome project!
> 
> Any options for 21:9 videos for ultrawide monitors? When setting videos to fill screen, the videos look very blurry. Fit to screen has the black bars on the side :(

What's the resolution of your 21:9 monitor ? If you go into the main video tab, you can change the video resolution from 1080p to 4K HEVC (or 4K HDR, with wilder colors, the option in red on the right). Those 4K videos should not look blurry when fit in a 21:9 monitor (they may look weird because of the cropping though). 

![Capture d’écran 2020-01-20 à 12 50 37](https://user-images.githubusercontent.com/37544189/72724497-c039f600-3b83-11ea-843d-e5273f51555a.jpg)

Note that not all videos are available in 4K, you can tell Aerial to ignore old 1080p videos by pressing the thing on  the left, it pops a menu where you can decide to only select 4K videos. Then, only those higher resolution videos will play for you. You can also add your own videos from that menu.

Hope this helps

**Comment by jonktsui** [comment]
Hey! Thanks for the update. I had selected 4k and it did show it a bit zoomed in and oddly cropped due to the zoom in :P

I guess these videos are taken from TVOS so it's really whatever options apple has.

**Comment by glouel** [comment]
> Hey! Thanks for the update. I had selected 4k and it did show it a bit zoomed in and oddly cropped due to the zoom in :P
> I guess these videos are taken from TVOS so it's really whatever options apple has.

Yep, you are losing a significant portion of the videos on top and bottom, but I don't think it looks *that* bad ;) You can manually select/deselect videos that you think aren't suited to that format if it helps.
