### ISSUE TITLE
customize text shadow

### ISSUE THREAD

**Issue by greg-wolff** [JohnCoates/Aerial#920]
is there any way to customize the text shadow or is it baked in? i would like to decrease its intensity, it's a bit too prominent for my taste, and if I can match the font to my company's brand then i'd like to modify the shadow to be likewise

**Comment by glouel** [comment]
Hi @greg-wolff 

So right now it's not configurable at all, just something I set myself. I did consider making it an option but I'm struggling a bit UI wise so I haven't added it yet. 

While I'm ok having one common setting for all the info types for shadows, I really don't want to add one per info type (like a different shadow for clock and battery for example) as it's just too much and I'm trying to stay reasonable with features and settings. There are a few other options that are "common" to all the Infos, such as the margins and fades that I temporarily moved into the advanced tab (Info appearance tweak section).

Because the Infos shows as a list on the left column, I thought maybe having an advanced section somewhere in there that would show those. An easy out would be put a unmovable "Common" section at the top (I don't think common is a great name but you get the idea) with margins and the other stuff. But if I put them on top, it gives them importance (and they'll be selected as default when you open that tab, which would make them very visible).

So I thought put an "Advanced" at the bottom of the list, but since the list is reorderable, I'd have to make the last one non reorderable which is a bit of clunky and ugly, even maybe with a separator. I did consider having it "stuck" to the bottom of the list but that doesn't feel super mac like. 
  
All this probably sound like rambling, sorry, in the meantime I'll probably add another field in advanced (it's super crowded) while I figure this out. Stay tuned, I'll get back to you.

**Comment by greg-wolff** [comment]
hey @glouel, thanks for the really quick reply! perhaps the text styles could be handled by having the omnipresent section at the bottom of the list, similar to the "Users & Groups" settings tab. I think it could even work with a separator, but I understand it might be a messy development workflow because you noted it's reorderable. perhaps using the other pattern of having a plus, minus, and settings icon for the list could work as well, allowing users to add multiple messages (and perhaps hook them up to simmple api calls or something). then the text styles could live under the dropdown for settings on the list. either way, i appreciate your attention to detail and am excited to see the text shadows in the advanced tab

here's some mockups of my ideas

![image](https://user-images.githubusercontent.com/7684791/74368033-b755d200-4d87-11ea-9258-5b54c2b65473.png)

(ignore the context menu on the second example, just showing the idea)

**Comment by NiklasBr** [comment]
I'm on a Windows PC right now, but isn't Aerial using the Mac OS Fonts Window when clicking the cog wheel? It already has all the settings required. Can those be used?

![](https://images.techhive.com/images/article/2015/01/textedit_fonts_characters-100564566-large.png)

**Comment by glouel** [comment]
> hey @glouel, thanks for the really quick reply! perhaps the text styles could be handled by having the omnipresent section at the bottom of the list, similar to the "Users & Groups" settings tab.

Yes !!! I was pretty sure I saw something like that somewhere in macOS, but couldn't remember where. That's exactly the one I was thinking about with the thing bolted down with a separator ! I'll have to investigate that one.

> I think it could even work with a separator, but I understand it might be a messy development workflow because you noted it's reorderable. perhaps using the other pattern of having a plus, minus, and settings icon for the list could work as well, allowing users to add multiple messages (and perhaps hook them up to simmple api calls or something).

I've been going back on forth on the idea. The code is ready for the concept of adding/removing and having multiple, yep, that was part of my big rewrite, including potentially having multiples of stuff (except for the location info which is a bit special because it can be random, all the other ones can be multiples). My thinking was, on 1.7 at least, only messages truly makes sense to duplicate (although a case could be made with the fact that you can set things differently on multiple screens, say you have 2 screens and you want one clock top left and top right on the other screen, etc).

As I'm adding more and more Info types (that was the goal of the whole thing, I was currently implementing a very niche countdown feature), I was thinking about that again and that some of these types, instead of being disabled by default, should just not appear by default. 

> then the text styles could live under the dropdown for settings on the list. either way, i appreciate your attention to detail and am excited to see the text shadows in the advanced tab
> 
> here's some mockups of my ideas
> 
> ![image](https://user-images.githubusercontent.com/7684791/74368033-b755d200-4d87-11ea-9258-5b54c2b65473.png)
> 
> (ignore the context menu on the second example, just showing the idea)

I wholeheartedly agree ! Thanks for taking the time to make the mockup, I'll let you know when I have a beta in the next few days.

**Comment by glouel** [comment]
> I'm on a Windows PC right now, but isn't Aerial using the Mac OS Fonts Window when clicking the cog wheel? It already has all the settings required. Can those be used?
> 
> ![](https://camo.githubusercontent.com/2e604854d8f391fb34a223d08dacf35c891e9f1f/68747470733a2f2f696d616765732e74656368686976652e636f6d2f696d616765732f61727469636c652f323031352f30312f74657874656469745f666f6e74735f636861726163746572732d3130303536343536362d6c617267652e706e67)

Hi @NiklasBr !

I'm not 100% clear how those work, but there are more options that what seems available with the API I use (things like the angle of the shadow, which as far as I understand, is not available in CoreAnimation). It might be distracting to have options that are available but not used. This is not a new problem, there's a color picker too that I don't use, I need to have a look at if I can select what appears there. Thanks for your input !

**Comment by glouel** [comment]
@greg-wolff https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta1/Aerial.saver.zip contains a shadow radius option in the Advanced tab. I haven't had a chance to work on the new ui, maybe this week end.

**Comment by glouel** [comment]
@greg-wolff beta2 now has that setting option, regrouping the various text stuff that was hidden in advanced : 

![Capture d’écran 2020-02-14 à 18 53 49](https://user-images.githubusercontent.com/37544189/74556136-a2cb3280-4f5d-11ea-944a-0d809aadb45c.jpg)

https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta2/Aerial.saver.zip

**Comment by greg-wolff** [comment]
@glouel awesome! the text settings panel looks great! i have one last request, is it possible to add shadow distance and opacity? most design tools have this feature, and for me, i'd like to try and disable the shadow so setting opacity would be helpful for me. thanks for such quick replies and updates. i love aerial!
![image](https://user-images.githubusercontent.com/7684791/74571926-2c193f80-4f33-11ea-9be1-fbc57290d3bf.png)

**Comment by glouel** [comment]
I did have a look at the API and found those yep, I'll see what I can do in a future beta !

**Comment by glouel** [comment]
There you go, offsets and opacity : 

![Capture d’écran 2020-02-15 à 19 23 51](https://user-images.githubusercontent.com/37544189/74593272-f5722080-5029-11ea-8fe8-7f098d18749e.jpg)

![Capture d’écran 2020-02-15 à 19 23 43](https://user-images.githubusercontent.com/37544189/74593273-f73be400-5029-11ea-8afe-a376264d6d8c.jpg)

https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta3/Aerial.saver.zip

**Comment by NiklasBr** [comment]
Nice job! :)

Maybe add measurement labels: pixels/points/degrees to the various controls and inputs?

**Comment by glouel** [comment]
Yep good idea, it's in points for radius/offsets, and the slider goes from 0 to 100% opacity FYI. Will add that for next build.

**Comment by glouel** [comment]
Closing with 1.8.0 : https://github.com/JohnCoates/Aerial/releases/download/v1.8.0/Aerial.saver.zip
