### ISSUE TITLE
Screen Saver Displays on 1 Display

### ISSUE THREAD

**Issue by Spencer8742** [JohnCoates/Aerial#938]
When the screen saver is playing it will only show on one of the monitors (not the primary).  

Confirmed all the monitors are turned on in settings

Mac model: 2018 MacBook Pro
macOS version: Mac OS Catalina 10.15
Monitor setup: 
3 Ultra Wide Samsung Monitors 
Node Pro with AMD VEGA 64
Thunderbolt Connection to MacBook Pro

**Comment by glouel** [comment]
Hi @Spencer8742 

Can you tell me which version of Catalina you are running ? Is it 10.15.3 ? There was a bug in the beta period of Catalina where screen savers only worked on one display only, which they later fixed. So clarifying this would be nice.

If you're not running an old beta, please enable debug log/log to disk and attach a log so I can have a look. Thanks

**Comment by Spencer8742** [comment]
Version 10.15 Beta 19A47t

**Comment by glouel** [comment]
Did you mean 19A471t ? If so, that's 10.15 beta 1, and yes, that's a macOS bug in that beta. It was fixed later on (beta 4 or 5, I don't remember but I could look it up if you need). You'll have the same issue with all 3rd party screen savers in that beta, that's due to a bug in the sandboxing mechanism they introduced, legacyScreenSaver.appex. 

If you don't mind me asking, why are you running such an old beta ?

**Comment by Spencer8742** [comment]
that is a very good question, not sure why. 

disregard this im an id10t

**Comment by glouel** [comment]
No worries ;) If you don't have to run that particular version for some reason, I would very much suggest you update as it's full of bugs, and not just on the screen saver side ! Take care !
