### ISSUE TITLE
Screensaver Seems To Cause Unexpected Shutdowns

### ISSUE THREAD

**Issue by BananimusPrime** [JohnCoates/Aerial#943]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: 
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports Dual-Core i5 8GB RAM)
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports Dual-Core i5 16GB RAM)
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 Ports Quad-Core i5 8GB RAM)
- [x] macOS version:
Tested with 10.14.6, 10.15.0, 10.15.1, 10.15.2, 10.15.3
- [x] Monitor setup:
2x 27" Apple Thunderbolt displays daisy-chained & connected via Apple Thunderbolt 2 to Thunderbolt 3 adapter

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4292958/AerialLog.txt)

#### Description of issue / Feature request

My colleague & I have both experienced this issue - with this screensaver set as the active screensaver, the Mac will unexpectedly shut down after the Mac goes to the screensaver and then goes to sleep. About an hour after the Mac goes to sleep it will shut down unexpectedly. This only happens when our Macs are connected to 2 27" thunderbolt displays that are daisy-chained together - it does not occur when the MacBook is disconnected from the monitors. The screensaver is set to display a different video on each monitor, and the Macs are closed, so there are just the 2 displays. We have tried with 3 different pairs of monitors, 3 different Thunderbolt 3 to Thunderbolt 2 adapters, and with 3 different Macs. The common thread has been this screensaver, as it has been tested on a freshly installed OS, which didn't shut down unexpectedly. As soon as the screensaver was installed we noticed the shutting down. I have also used my Mac with a different screensaver for the last month and experienced no unexpected shutdowns at all.

**Comment by glouel** [comment]
Hi @BananimusPrime 

Sorry about that... This is a bit of a weird one, I've had one report about issues with a specific TB3 dock where the screens would no got to sleep. Looks like you had both some Catalina and Mojave machines in there too.

Just to make sure I get the events correctly:
- Screensaver is launched, does it's thing for a set amount of time (I'd say about 20mins, looking at your logs)
- Your screens go to sleep. At that point your Macs are still working
- Then an hour afterwards, that's when you get a shutdown

Correct ?

You also mention that you don't have the issue with other screensavers, I assume you mean with the ones bundles by Apple, correct ? Or are you talking about another 3rd party screensaver (like, say, Electric Sheep?). 

Let me know if I get the events correctly and I'll try to think of something. Did you happen to have looked in console.app for some crash logs maybe ? I thought there was a specific section in there for unexpected shutdown but I don't see it after a quick glance, but there's probably a log somewhere about what happens. I had a look at your AerialLog but there's nothing particularly wrong in there that I can gather, it's probably more in the system logs.

**Comment by BananimusPrime** [comment]
Hey @glouel 

That's exactly correct. 

Yeah I'm talking about the bundled Apple screensavers, I've not tried other third-party ones. I've just installed Electric Sheep and I'll report back as to whether the same thing happens there too. If so then it's not your problem but Apple's I guess!

I did have a look through console and an error report is generated upon restarting the Mac, but it always said it was an unknown error and didn't contain any specifics about what had happened.

**Comment by glouel** [comment]
> Hey @glouel
> 
> That's exactly correct.

Ok, reason I asked is that, Aerial is just a plugin started and stopped by ScreenSaverEngine, so in a sense it's not responsible for when it gets killed (violently !) by the OS. When your screens go to sleep, Aerial gets killed so an hour afterwards, it's not running.

With Catalina, the lifetime thing gets a tiny bit more complicated especially with 3rd party screensavers which are treated differently. There were a few bugs too with multi monitor which didn't help but nothing of the sort you are reporting. 

> Yeah I'm talking about the bundled Apple screensavers, I've not tried other third-party ones. I've just installed Electric Sheep and I'll report back as to whether the same thing happens there too. If so then it's not your problem but Apple's I guess!

Please do ! 3rd party are treated differently in Catalina (there's a bit of difference in the latest Mojave builds but it's not as weird, never really got a chance to explore that, some things were definitely different too) so it's always good to get another 3rd party one to double check.

I don't think I asked, what's the frequency of this happening ? Is it like 100% or infrequent ?

> I did have a look through console and an error report is generated upon restarting the Mac, but it always said it was an unknown error and didn't contain any specifics about what had happened.

That's quite cryptic !

If I put aside the general Apple bugs, the most likely thing would be something happening when Aerial gets killed that leaves something in an unstable state (maybe some driver crashing after a while). Aerial certainly does push some pixels but that in itself shouldn't be an issue. 

Which Thunderbolt 2 displays are you using btw ? It may sound stupid, but since you mention it crashes with 2, and not with none, have you tried with just one just to see ?

Let me know what Electric Sheep does (and also on which OS) and we'll go from there.

**Comment by BananimusPrime** [comment]
> I don't think I asked, what's the frequency of this happening ? Is it like 100% or infrequent ?

I think I'd say it's 80%-100% of the time, very very rare that I come to my computer and it has not restarted.

> Which Thunderbolt 2 displays are you using btw ? It may sound stupid, but since you mention it crashes with 2, and not with none, have you tried with just one just to see ?

They are the 27" Apple Thunderbolt Displays. I did try with just one monitor and the Mac did not restart, so it seems to be directly linked to Aerial displaying on two daisy-chained monitors.

I've tried both Electric Sheep as well as some other 3rd-Party screensavers over the weekend and the Mac didn't restart at all! I have now put Aerial back on the Mac to confirm it is shutting down.

**Comment by glouel** [comment]
> > I don't think I asked, what's the frequency of this happening ? Is it like 100% or infrequent ?
> 
> I think I'd say it's 80%-100% of the time, very very rare that I come to my computer and it has not restarted.

Ok, the good side of this, it makes reproduction a bit easier. 

> They are the 27" Apple Thunderbolt Displays. 

Ok.

> I did try with just one monitor and the Mac did not restart, so it seems to be directly linked to Aerial displaying on two daisy-chained monitors.

Interesting. 

> I've tried both Electric Sheep as well as some other 3rd-Party screensavers over the weekend and the Mac didn't restart at all! 

I see. There are a couple things that Aerial does that may be behind what you are experiencing. Before I make any suggestion/try to workaround something, I tried to dig again in your logs to get a better idea, but it looks like you were running mostly with one monitor attached only in those with recent versions. 

Would it be ok to delete your AerialLog.txt, launch the screensaver once (when daisy chained), exit after a few secs, and send that to me ? That would give me a fresh view of how your screens are detected and a better view of your settings. 

Thanks!

**Comment by BananimusPrime** [comment]
> but it looks like you were running mostly with one monitor attached only in those with recent versions.

Hmm, that's interesting as I only ever had one monitor when I was testing this problem out a while ago, I pretty much always have the two monitors connected and the clamshell closed. Either way, I've attached another copy of the fresh logs.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4313324/AerialLog.txt)

**Comment by glouel** [comment]
@BananimusPrime I see. Looks like I got confused and thought you were *not* running clamshell and was looking for a third one, and didn't pay much attention to the resolutions. So yeah, I see your two monitors. A few suggestions then, it might take some time to try them all, I tried to order them from easier to more cumbersome :

- First, I don't think you are, but check the Brightness tab in Aerial and make sure it's off and you are not using the brightness control. It's a bit of a long shot but I could see that being a potential issue. 
- In Displays, switch "Play Aerials on" from "All displays" to "Main display", this might reduce the stress on the driver/adapter
- Now that I know you are running in clamshell, I would highly suggest you try running the screensaver with the Mac open if that's possible, to see if you are still hitting the issue. Clamshell is problematic usually with macOS.
- If that doesn't work, in clamshell, I would suggest running on main display only (or use select, to switch to your internal display only), to see if you still hit the issue. 
- Last idea, could you try using 2 adapters instead of one, just to avoid daisy chaining and see if you still hit the issue ? 

That's about all I can think of right now, based on the symptoms you described, please let me know if any of this helps. Thanks !

**Comment by BananimusPrime** [comment]
Hey @glouel sorry for the delayed response, I guess you can understand everything has gone crazy for so many people and maybe you too! I think we can close this for now because despite it happening every single time the last time I tried it, I haven't actually experienced the Mac shutting down since I opened this ticket...Typical! I also don't currently have access to both of my monitors at the minute so I can't test again until who knows when.

Thank you for all of your help.

**Comment by glouel** [comment]
No worries and yep I definitely understand, things are crazy/weird here too 🙈

Feel free to reopen if you hit the issue again and take care !
