### ISSUE TITLE
Expanded Video Info

### ISSUE THREAD

**Issue by OrangeJedi** [JohnCoates/Aerial#953]
Hey, I went through Apple's resources-13.tar and managed to extract most of the info (pointsOfInterest) text. I've made a new .json file in the same format as [Resources/Community/en.json](https://github.com/JohnCoates/Aerial/blob/master/Resources/Community/en.json) with the updated information. 
Should I create a pull request, or because these are technically translations, do something else? I read the documentation and the it wasn't immediately apparent.

**Comment by glouel** [comment]
Hi @OrangeJedi 

Please don't take this the wrong way, but why did you do that ? Where you not seeing the descriptions ? 

Aerial already loads the strings bundle for your selected language and will use those pointsOfInterests when displaying videos, no need to make a json for it.

Aerial's JSONs are supplementary information (we provide titles for the videos mostly, which are not in the strings bundle), and Aerial merges all of this (the strings bundle from resources-13.tar, the Community json, etc) to display the best info available.

So no need for a PR, especially since those strings are copyrighted (and I made the strings loading /merging thing to go around all this !).

**Comment by OrangeJedi** [comment]
Ahh. I didn't realize you were pulling them from the resources-13.tar. I actually haven't used Aerial....
I'm building a [Windows version](https://github.com/OrangeJedi/Aerial) of Aerial and needed the strings for displaying the info. Currently with the the technology that I'm using I don't have a way to extract the data from the . resources-13.tar in the actual screen saver. I was looking to get the strings and saw your en.json and started from there. Once I got the strings I thought that I could post them here, I didn't realize you already had them, I guess I wasn't thinking straight.

**Comment by glouel** [comment]
Ha ! That makes sense, I was afraid the strings were not loading for you and you went to all that trouble because of it. When it comes to loading the strings files, in macOS, it's done automatically so that helps a lot. I'm not sure if you could do that on the fly in windows (there are some plist openers which you've obviously found). 

Feel free to reuse the community stuff from Aerial, I may suggest you can omit the pointsOfInterests in there as they are not relevant (they are mostly from a time where we didn't have descriptions for some videos, but that has passed), I should probably drop them but many people put work into them and they are good. The titles though, those are important.

I may point you to a couple more stuff that could be of help, check the top of this file : https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Models/AerialVideo.swift

You'll get the ID for Space, Sea videos, and night/day info for the new videos which should be helpful at some point for you too ;) 

Feel free to ping me when you feel you're getting out of beta or get things a bit more stable and I'll put a link on the page here.

**Comment by OrangeJedi** [comment]
Thanks! I saw your [post](https://github.com/cDima/Aerial/issues/201#issuecomment-581021527) on  cDima/Aerial and have been using both of those files. Huge lifesavers! I'll let you know when the project is up and running so you can put up a link.

**Comment by glouel** [comment]
Also, someone made a PR this week (that's why your issue spooked me) and did the same thing you did, but for *all* languages. Have a look here, you may find interest in it (although note said person didn't merge the titles). https://github.com/JohnCoates/Aerial/pull/950

**Comment by OrangeJedi** [comment]
Ha! Maybe I should have dug around more; might have saved me a bit of time... I might come back to then if I need titles for other languages and still haven't found a way to read the resources-13.tar
