### ISSUE TITLE
Deployable preferences to fix wake issue?

### ISSUE THREAD

**Issue by jeffk395** [JohnCoates/Aerial#958]
Current Version: 1.8.2
macOS Version: 10.15.4
Machine: MacBook Pro 13" 2019

I am deploying Aerial to all of my users via Jamf (they really love the screen saver as do I). The large majority of us are experiencing the issue that has been addressed previously where the screen saver will not wake to the password query by moving the mouse and pressing the keyboard. The only thing that works is the Wake function (either pressing the power button or sending the computer wake command via ARD). We have been able to fix this by turning off Aerial checking for updates.

What I would like to know, is there a way to make this default prior to deployment via MDM? I cannot find a preference file or any way to make this default.

**Comment by glouel** [comment]
Hi @jeffk395 !

I assume you are also deploying some firewall ? So far it looks like the hang happens when an app blocks the update check (I assume by interrupting and putting a popup, although the blocking may actually be the thing that hangs ? Never managed to find exactly what happens, I know Little Snitch does provoke the hang). 

With that said, yes, the preference file is a bit hidden in a container, it's here : 

`~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist`

There's another file in the non `ByHost` folder, one level up, ignore  this (it's Sparkle's). 

When it comes to the preference you are looking for, I'd say these two keys : 

`checkForUpdates`, bool, to `NO`
`updateWhileSaverMode`, bool to `NO`

Let me know how that works for you, if it does I'll put it up somewhere in the docs.

**Comment by jeffk395** [comment]
Thank you for the quick reply. So, no firewall installed with my MDM
deployment. It’s just the behavior of the screensaver when deployed using
Jamf. Possibly could be a conflict with on of the configuration profiles…
not sure. Or could just be Catalina being, you know, Catalina.

I deploy Aerial in the root Library rather than the User library. Is there
a way to get these prefs deployed so that it applies to ALL users and not
just current user?


On April 2, 2020 at 10:11:05 AM, Guillaume Louel (notifications@github.com)
wrote:

Hi @jeffk395 <https://github.com/jeffk395> !

I assume you are also deploying some firewall ? So far it looks like the
hang happens when an app blocks the update check (I assume by interrupting
and putting a popup, although the blocking may actually be the thing that
hangs ? Never managed to find exactly what happens, I know Little Snitch
does provoke the hang).

With that said, yes, the preference file is a bit hidden in a container,
it's here :

~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist

There's another file in the non ByHost folder, one level up, ignore this
(it's Sparkle's).

When it comes to the preference you are looking for, I'd say these two keys
:

checkForUpdates, bool, to NO
updateWhileSaverMode, bool to NO

Let me know how that works for you, if it does I'll put it up somewhere in
the docs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JohnCoates/Aerial/issues/958#issuecomment-607870216>,
or unsubscribe

**Comment by glouel** [comment]
> Thank you for the quick reply. So, no firewall installed with my MDM deployment. It’s just the behavior of the screensaver when deployed using Jamf. Possibly could be a conflict with on of the configuration profiles… not sure. Or could just be Catalina being, you know, Catalina.

Quite probable ! Screen Savers are a mess with Catalina.

> I deploy Aerial in the root Library rather than the User library. Is there a way to get these prefs deployed so that it applies to ALL users and not just current user?

As far as I remember, and I may be wrong so you may need to double check this, but my understanding is that the sandbox mechanism is a per user thing in macOS, so you need to do it for each user you deploy. The plist loading is done by macOS itself for the screensaver so not much I can do here.

But of you happen to have machines that are used by multiple users, I would highly recommend moving the cache to `/Users/Shared` so videos aren't downloaded multiple times. I would do something like this:

- Create `/Users/Shared/Aerial`
- Copy the videos when you deploy inside that folder
-  In the plist, change cacheDirectory to that folder

Now, because Catalina is all about fun, you need to do the deploying yourself in that case. Because the screensaver cannot write outside of it's user's container, Aerial will always download in the container. Aerial can *read* outside of the container (so in that case `/Users/Shared/Aerial` but not write to it). To grab the videos from one machine, go to `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial`in a machine that has downloaded the video.

Final step, you also need to tell Aerial which video set you are using (4K, HDR, etc). That's done with `intVideoFormat`, an int, it goes : v1080pH264 = 0, v1080pHEVC = 1, v1080pHDR = 2, v4KHEVC = 3, v4KHDR = 4

This is painful, I know, but it's Catalina !

**Comment by jeffk395** [comment]
This is great info - I was able to find the pref file to edit, but I cannot
find a way to defaults -write it with the correct settings. Because it’s
buried so deep, do you know what the best way to script the changes would
be? If I simply defaults -write, it creates a new file in
~/Library/Preferences/ByHost/com.JohnCoates.aerial which does not have any
effect on the module.


On April 2, 2020 at 10:29:56 AM, Guillaume Louel (notifications@github.com)
wrote:

Thank you for the quick reply. So, no firewall installed with my MDM
deployment. It’s just the behavior of the screensaver when deployed using
Jamf. Possibly could be a conflict with on of the configuration profiles…
not sure. Or could just be Catalina being, you know, Catalina.

Quite probable ! Screen Savers are a mess with Catalina.

I deploy Aerial in the root Library rather than the User library. Is there
a way to get these prefs deployed so that it applies to ALL users and not
just current user?

As far as I remember, and I may be wrong so you may need to double check
this, but my understanding is that the sandbox mechanism is a per user
thing in macOS, so you need to do it for each user you deploy. The plist
loading is done by macOS itself for the screensaver so not much I can do
here.

But of you happen to have machines that are used by multiple users, I would
highly recommend moving the cache to /Users/Shared so videos aren't
downloaded multiple times. I would do something like this:

   - Create /Users/Shared/Aerial
   - Copy the videos when you deploy inside that folder
   - In the plist, change cacheDirectory to that folder

Now, because Catalina is all about fun, you need to do the deploying
yourself in that case. Because the screensaver cannot write outside of it's
user's container, Aerial will always download in the container. Aerial can
*read* outside of the container (so in that case /Users/Shared/Aerial but
not write to it). To grab the videos from one machine, go to
~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application
Support/Aerialin a machine that has downloaded the video.

Final step, you also need to tell Aerial which video set you are using (4K,
HDR, etc). That's done with intVideoFormat, an int, it goes : v1080pH264 =
0, v1080pHEVC = 1, v1080pHDR = 2, v4KHEVC = 3, v4KHDR = 4

This is painful, I know, but it's Catalina !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JohnCoates/Aerial/issues/958#issuecomment-607881030>,
or unsubscribe

**Comment by jeffk395** [comment]
And I should also say that the computers are only used by one person, not
multiple people, so no need to relocate the Caches.


On April 2, 2020 at 3:40:06 PM, Jeff Kunkel Jr. (kunkmasterflex@gmail.com)
wrote:

This is great info - I was able to find the pref file to edit, but I cannot
find a way to defaults -write it with the correct settings. Because it’s
buried so deep, do you know what the best way to script the changes would
be? If I simply defaults -write, it creates a new file in
~/Library/Preferences/ByHost/com.JohnCoates.aerial which does not have any
effect on the module.


On April 2, 2020 at 10:29:56 AM, Guillaume Louel (notifications@github.com)
wrote:

Thank you for the quick reply. So, no firewall installed with my MDM
deployment. It’s just the behavior of the screensaver when deployed using
Jamf. Possibly could be a conflict with on of the configuration profiles…
not sure. Or could just be Catalina being, you know, Catalina.

Quite probable ! Screen Savers are a mess with Catalina.

I deploy Aerial in the root Library rather than the User library. Is there
a way to get these prefs deployed so that it applies to ALL users and not
just current user?

As far as I remember, and I may be wrong so you may need to double check
this, but my understanding is that the sandbox mechanism is a per user
thing in macOS, so you need to do it for each user you deploy. The plist
loading is done by macOS itself for the screensaver so not much I can do
here.

But of you happen to have machines that are used by multiple users, I would
highly recommend moving the cache to /Users/Shared so videos aren't
downloaded multiple times. I would do something like this:

   - Create /Users/Shared/Aerial
   - Copy the videos when you deploy inside that folder
   - In the plist, change cacheDirectory to that folder

Now, because Catalina is all about fun, you need to do the deploying
yourself in that case. Because the screensaver cannot write outside of it's
user's container, Aerial will always download in the container. Aerial can
*read* outside of the container (so in that case /Users/Shared/Aerial but
not write to it). To grab the videos from one machine, go to
~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application
Support/Aerialin a machine that has downloaded the video.

Final step, you also need to tell Aerial which video set you are using (4K,
HDR, etc). That's done with intVideoFormat, an int, it goes : v1080pH264 =
0, v1080pHEVC = 1, v1080pHDR = 2, v4KHEVC = 3, v4KHDR = 4

This is painful, I know, but it's Catalina !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JohnCoates/Aerial/issues/958#issuecomment-607881030>,
or unsubscribe

**Comment by glouel** [comment]
> This is great info - I was able to find the pref file to edit, but I cannot find a way to defaults -write it with the correct settings. Because it’s buried so deep, do you know what the best way to script the changes would be? If I simply defaults -write, it creates a new file in ~/Library/Preferences/ByHost/com.JohnCoates.aerial which does not have any effect on the module. 

You need to pass the file without the UUID as a parameter. So : 

`defaults write ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist checkForUpdates -bool false`

Should do the trick. Use defaults read to double check but it seems to work here after a quick test. Do not pass the UUID or it will create a file with the UUID in double :)
