### ISSUE TITLE
Time Suddenly Shows

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#988]
Thanks for the new version!

FYI, Aerial is now showing Clock, though I hadn't previously configured it to do so. If this is intentional, then never mind!

Aerial does still respect my previous font/position prefs for Location, so it didn't just wipe all my prefs.

New Mac Mini running latest Catalina

**Comment by glouel** [comment]
@Jimmbo ha yes, that's a side effect of a change I made to preferences. Some individual info prefs such as "Clock" will have been reset to their default, because I added a new setting to it (in yellow below). 

I did change the preferences format so that it should not happen again, but for this one it got reset for everyone, sorry ! 

To fix it, just disable here where I circled in red : 
![Capture d’écran 2020-05-25 à 18 01 41](https://user-images.githubusercontent.com/37544189/82828809-2e842180-9eb2-11ea-97b6-8515a067f633.jpg)

**Comment by Jimmbo** [comment]
Ok, great!

But maybe you should mention that sort of thing in the release notes, just to avoid having people like me ask about it!

**Comment by glouel** [comment]
Good idea, done : https://github.com/JohnCoates/Aerial/releases/tag/v1.9.0

Thanks!
