### ISSUE TITLE
No screensaver options (again)

### ISSUE THREAD

**Issue by mhp-borisbojic** [JohnCoates/Aerial#992]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- Mac model: MacBook Pro 15" (late 2018)
- macOS version: Catalina 10.15.4
- Monitor setup: LG 38" (3840x1600 Ultrawide)
- Aerial v1.9.0 (installed via .zip & doubleclick for all users)

#### Description of issue / Feature request

There are no options available for the screensaver. Rebooting didn't help as well ...?

![Bildschirmfoto 2020-05-26 um 12 21 58](https://user-images.githubusercontent.com/47522149/82889884-b4a07680-9f4b-11ea-91cb-e0d17f1e6741.JPG)

**Comment by glouel** [comment]
Hi @mhp-borisbojic 

You say "again" in your title, can you clarify what you mean by that ? Did you have a previous version installed that also exhibited the problem ? Or is it your first time installing Aerial ?

Also, if you start Aerial with a hot corner, does it work or does it show a black screen ?

In general couple of things can happen. If you have two swift screensavers, depending on how the second one is compiled, you may not be able to switch from one to the other without fully closing System Preferences. It's an old macOS bug that's partially been fixed. 

It's also possible you are experiencing a crash, it would look like this. If so, can you please launch "Console" on your mac and look for a crash log for either legacyScreenSaver or something that vaguely sounds like "pref desktop something" (can't remember the name off the top of my name). If you need more assistance looking for those let me know.

Thanks

**Comment by mhp-borisbojic** [comment]
Hey!

I wrote "again" because there was already a similar issue (that was closed): https://github.com/JohnCoates/Aerial/issues/937 ... I never used Aerial before. ;)

The saver itself works, but there are no options available.

I have no idea "where" to find any screensaver crash related logs. Could you tell me the directory / file (and yes, I know how to use the Terminal app of macOS)?

**Comment by glouel** [comment]
Ha I see ! Had to ask because it could have been related to a previous old version. 

> For whatever reason, the options are now available ... I didn't do anything?

Well, the likely thing is you were hitting the multiple swift screensaver bug. If you exited System Preferences with Aerial selected in the list on the left (by fully closing the window clicking the red button top left), then reopened, then it works because System Preferences was able to run the correct swift library. 

If you select Brooklyn again, you may not be able to access it's preferences, until you close (with Brooklyn selected) and reopen again. It's a System Preferences bug that's been here for a while : http://www.openradar.me/25569037

If you can't access options, keep selected, reload, you should be ok. Enjoy Aerial ;)

**Comment by mhp-borisbojic** [comment]
Thanks! Maybe you could add this to the Troubleshooting? :)

**Comment by glouel** [comment]
It's the first one in Very common, https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#very-common-issuesmacos-bugs although for some reason you didn't have the error message people used to get when I wrote this. Probably changed with Catalina, I'll update it thanks !

**Comment by glouel** [comment]
It's updated so closing now, thanks !
